### ISSUE TITLE
建议把 README 的默认语言改为英语

### ISSUE THREAD

**Issue by tyfulcrum** [liuchengxu/space-vim#1]
这样有利于项目发展，光凭华人社区的力量是不可能达到 spacemacs 的高度的。

**Comment by liuchengxu** [comment]
的确是个问题，非常感谢！但是感觉目前还是比较简陋，希望还能在稍微成形些再做这件事。(其实是期待英文更好的人来做这件事:smile:)

**Comment by leohxj** [comment]
借楼问下，这个项目和 https://github.com/ctjhoa/spacevim 有哪些区别？

**Comment by liuchengxu** [comment]
@leohxj 与 [spacevim](https://github.com/ctjhoa/spacevim) 借鉴的思路不同：

spacevim 以类似 vim 插件的方式试图模拟，个人觉得比较生硬，不太容易发挥众人的智慧。而 space-vim 借鉴的是 spacemacs 整个工程结构，实现了类似 Layer 的概念，具有很强的可塑性，可以方便大家贡献，共同建设。

比如在 space-vim 中添加一个目前没有的 ruby layer, 贡献者只需将针对 ruby 的一些插件与设置写入到 packages.vim 与 config.vim,  core_config.vim 稍作添加即可分享一个 vim 下开箱即用的 ruby 环境。 

此外，主观来讲，space-vim 更漂亮~~~ 😀

**Comment by NovaGeek** [comment]
作为一个使用vim不太久，也想加入贡献，楼主可否指引一下

**Comment by liuchengxu** [comment]
@NovaGeek 简短写了一份指引，欢迎大家贡献！[贡献指引](https://github.com/liuchengxu/space-vim/wiki/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%BC%95)

**Comment by liuchengxu** [comment]
已经更新 README, 欢迎大家提意见并修改。
