### ISSUE TITLE
终端里的字体怎么修改大小啊？

### ISSUE THREAD

**Issue by endice** [liuchengxu/space-vim#10]
我在`./layers/+vim/better-defaults/config.vim`和`./assets/space-vim-badge.svg:`里修改都无效><

**Comment by liuchengxu** [comment]
终端里 vim 字体是无法通过配置文件设置的，需要手动设置，详情请看[这里](https://github.com/liuchengxu/space-vim/blob/master/doc/tutorial_cn.md#安装字体)

**Comment by endice** [comment]
嗯，解决了，但是这样的话有点不方便，因为命令行字体不宜太大，但编辑器字体又想大点~~

**Comment by liuchengxu** [comment]
额，这个好像没啥好办法, 只能这么做:p

**Comment by nightire** [comment]
iTerm 可以用快捷键调字体大小啊
