### ISSUE TITLE
Some display problem when i use Consolas font type

### ISSUE THREAD

**Issue by x1zbin** [liuchengxu/space-vim#100]
#### Environment

- OS: windows and ubantu
- vim: gvim_8.0.0503_x64

#### Problem Description
When i set in **.spacevim** file that
**set guifont=Consolas:h12: b:cDEFAULT**
the gvim display something **bad** when it in **full-screen** mode
on the bottom of the gvim,it's a **white line** display on it
(it's also a small white line on the right of the gvim when i add some thing in UserConfig but not too obvious)

![image](https://cloud.githubusercontent.com/assets/25758203/24319701/63848fbc-115e-11e7-8ef2-9829db34c25b.png)

**Comment by x1zbin** [comment]
this is my **.spacevim** setting

`" You can enable the existing layers in space-vim and
" exclude the partial plugins in a certain layer.
" The command Layer and Exlcude are vaild in the function Layers().
function! Layers()

    " Default layers, recommended!
    Layer 'fzf'
    Layer 'unite'
    Layer 'better-defaults',{ 'exclude': 'itchyny/vim-cursorword' }
    Layer 'chinese'
endfunction

" Put your private plugins here, e.g., change the colorscheme.
function! UserInit()

    " Space has been set as the default leader key,
    " Comma has been set at the default localleader key.
    " If you want to change it, uncomment and set it here.
    " let g:spacevim_leader = "your leader key"
    " let g:spacevim_localleader = 'your localleader key'

    " Install private plugins
    Plug 'morhetz/gruvbox'
    Plug 'auto-pairs'
    Plug 'Solarized'
    Plug 'scrooloose/nerdcommenter'
    Plug 'majutsushi/tagbar'
    Plug 'tagbar-phpctags.vim'
endfunction

" Override the existing configurations and add extras here.
function! UserConfig()

    " color gruvbox
    set guioptions-=m
    set guifont=Consolas:h12:b:cDEFAULT
    nmap tt :TagbarToggle<CR>
    nmap ty :NERDTreeToggle<CR>
    "设置Gvim启动是最大化
    autocmd GUIEnter * simalt ~x
    nmap H gT
    nmap L gt
    colorscheme solarized
    let g:tagbar_width = 26
    let g:tagbar_phpctags_bin='F:\phpStudy\WWW\phpctags'
endfunction`

**Comment by liuchengxu** [comment]
Thanks for the pointer. I never noticed the problem before. But it has nothing to do with the guifont setting in .spacevim. You could test it. The bottom gap is always there whether you have set the guifont or not. I'm not sure if it's normal when gvim is maximized in windows, or we ignored something.

**Comment by x1zbin** [comment]
![image](https://cloud.githubusercontent.com/assets/25758203/24319868/d0816d06-1163-11e7-99d1-45d1412408e0.png)
When i cancel the guifont setting ,the white bottom gap become smaller that can be say to be disapper.
This problem also in Ubantu system.
However, the guifont setting doesn't affect my work,so i can ignore it.Thanks~

**Comment by liuchengxu** [comment]
It's a core problem with gvim. You can change the font size to reduce the impacts :).

**Comment by x1zbin** [comment]
Ok,i will try it.Thank for your patient answer.
