### ISSUE TITLE
keymap recommendation

### ISSUE THREAD

**Issue by yqrashawn** [liuchengxu/space-vim#102]
Don't remap undo, redo.
Use `C-h` as backspace in insert mode and command mode.
Or at least make them configurable.

**Comment by liuchengxu** [comment]
Currently, space-vim doesn't remap undo, but do remap redo: `nnoremap U <C-r>`, check it with `:verbose map U`. If someone doesn't want to remap it, add this to `UserConfig()`:

```vim
function! UserConfig()
   unmap U
endfunction
```

`C-h` has been mapped as `<left>` in insert and command mode, see `:verbose imap <C-h>`, `:verbose cmap <C-h>`.

**Comment by tracyone** [comment]
@liuchengxu 因为，ctrl-h这个快捷键的作用，已经被很多gnu用户习惯了，gnu有个东西叫gui readline，是一个库也是一个套快捷键，你会发现和emacs一样，比如ctrl-a是到行首，ctrl-e是到行尾，ctrl-h是删除，ctrl-f和ctrl-b是左右位置移动...等等..你可以看这个仓库：[GNU Readline keybinding ](https://cnswww.cns.cwru.edu/php/chet/readline/readline.html)，你也可以看大神tpope写的一个插件[vim-rsi](https://github.com/tpope/vim-rsi)

**Comment by liuchengxu** [comment]
@tracyone Make sense. I'll consider it.

**Comment by liuchengxu** [comment]
@yqrashawn @tracyone  Your ideas are reasonable. I have updated [vim-better-default](https://github.com/liuchengxu/vim-better-default) with `C-h` mapped to backspace, `<C-b>` and `<C-f>` mapped to backward and forward operation.
