### ISSUE TITLE
commands for `wget` and `curl` download sections are same in Getting Started Section

### ISSUE THREAD

**Issue by pankajpatel** [liuchengxu/space-vim#103]
On the website http://vim.liuchengxu.org/ the commands for `wget` and `curl` download sections are same in Getting Started Section.
<img width="814" alt="space-vim" src="https://cloud.githubusercontent.com/assets/251937/24329555/5ead761e-120a-11e7-9178-7848d2d2c534.png">

**Comment by liuchengxu** [comment]
Thanks! Updated.
