### ISSUE TITLE
Problem with certificate while install.sh

### ISSUE THREAD

**Issue by fdik** [liuchengxu/space-vim#104]
#### Environment

- OS: macOS 10.12.3
- vim: 8.0.237 of MacPorts 2.4.1

#### Problem Description

install.sh does not clone git repo.

> fatal: unable to access 'https://github.com/liuchengxu/space-vim.git/': SSL certificate problem: unable to get local issuer certificate

**Comment by liuchengxu** [comment]
`sh -c "$(curl -k https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)"`
