### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by tleb** [liuchengxu/space-vim#106]
[This commit](https://github.com/liuchengxu/space-vim/commit/310818c6d7c33564832401c8e6004c90d6308515) broke the install by renaming the `install.sh` file to `git clone`.

**Comment by liuchengxu** [comment]
Just fixed. Really sorry for my stupid mistake  :-(.

**Comment by tleb** [comment]
Damn, you are quick. While I was cloning to PR, you had already fixed it.

Installing space-vim right away. :)
