### ISSUE TITLE
vim requirement when nvim is installed

### ISSUE THREAD

**Issue by tleb** [liuchengxu/space-vim#108]
#### Environment

- OS: Fedora 25
- vim: not installed
- neovim: 0.1.7

#### Problem Description

The `install.sh` says that we must have `vim` to continue but I plan on using space-vim with neovim. Must I really install `vim`?

**Comment by liuchengxu** [comment]
Actually, you don't have to. If so, then you need to install space-vim manually.

**Comment by liuchengxu** [comment]
The quick installer has been refined for neovim, although a little late:).

**Comment by tleb** [comment]
I'm sorry, I completely forgot about this issue as I stopped using neovim. 😐
