### ISSUE TITLE
MacVim 上搜索的时候用中文输入法会有问题

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#11]
### 重现：

1. MacVim 打开文件；
1. 按 `/` 进入搜索模式；
1. 用中文输入法输入`ni(你)`。

### 期待：

搜索`你`

### 实际上：

搜索栏出现了`nnnini你`

另外我用的是 MacOS 自带的中文输入法。

**Comment by liuchengxu** [comment]
MacVim 的确有这个问题，终端下没有。

排查应该是 better-defaults 这个layer 下的 config.vim 有问题，禁用掉整个 config.vim 就没有这个问题了，但是我目前还无法确定是哪一个或那几个部分的设置导致了这个问题。

**Comment by yesmeck** [comment]
这个插件的缘故 https://github.com/haya14busa/incsearch.vim

**Comment by liuchengxu** [comment]
config.vim 里面关于这部分的设置有问题，还是这个插件自己有问题？如果是它自己有问题，那就.....

**Comment by yesmeck** [comment]
issue https://github.com/haya14busa/incsearch.vim/issues/52

**Comment by liuchengxu** [comment]
还是 open 的状态，看来没啥好办法了.... 默认不加这个插件吧，想要用的话，自行添加好了....

**Comment by liuchengxu** [comment]
已经把 incsearch.vim 的配置去掉了，应该可以 close 了~
