### ISSUE TITLE
Suggestion to keep the behavior of ; and , keys in normal mode.

### ISSUE THREAD

**Issue by yzhuang** [liuchengxu/space-vim#111]
Hi, 

Just tried space-vim and love it so far. 
One behavior that's quite unintuitive is that ; and , keys are remapped in normal mode. 

Personally (I guess most other Vimmers too), I frequently use f/F/t/T for navigation. The keys ; and , are essential for those movements.  Remapping both ; and , keys makes space-vim not very vim like.

Currently, I unmapped those mappings for myself, but I thought this config might be unintuitive for other vimmers as well.

Have you considered keeping the behavior of ; and , in normal mode?

Thanks!

**Comment by liuchengxu** [comment]
Thanks, @yzhuang . You know, `,` is the default major mode leader key in spacemacs, which is mapped to the local leader key in vim. space-vim is trying to keep consistency with it as mentioned in README. I think your idea deserves a discussion, after all, not every vimmer has an experience with spacemacs :). `;` is just my personal preference, I don't know if it's dystrophic for other vimmers.

**Comment by yzhuang** [comment]
Of course, these suggestions are based on personal experience, and may not suite everyone :) 

I use Spacemacs in evil mode, and also ended up restoring the behavior of the comma key, since it is vital to vim navigation.  I use <space><space> to invoke command mode, instead of the ; key.

In Spacemacs, the major mode leader is used to invoke per file type shortcuts.  In Spacevim, the local leader comma key is much harder to use due to the lack of guide-key / which-key: local bindings are different per file type.  Without guide-key displaying hints, the local leader is difficult to use / memorize.  What do you think?

Hopefully someone will create a vim-which-key soon.  This project looked promising, but the author seem to have stopped development: https://github.com/hecal3/vim-leader-guide

Try the built in functions f / F / t / T, and vim-sneak. See if you like them.  
Once I learned to use these navigation tools, I ditched easymotion.
Personally, I feel the f / F / t / T, keys are even more useful than h,j,k,l.  

Of course, everyone has different habits and muscle memories. Just wanted to contribute my thoughts. :)

**Comment by liuchengxu** [comment]
Without the prompt of which-key, it's truly not so satisfying. You could see the discussion about  [vim-leader-guide](https://github.com/hecal3/vim-leader-guide) in #34 . Personally, it's definitely useful, but just not that good by far. So I haven't prepared to integrate it into space-vim.

I'm quite willing to know how others use and think about vim :). Thanks for your suggestion, I'll try [vim-sneak](https://github.com/justinmk/vim-sneak) and the built in functions.

**Comment by yzhuang** [comment]
thought about this, see if you like the following suggestion:

- Leave , and ; untouched, so that f/F/t/T and vim-sneak remain useful.
- Map Enter key in normal mode to ":" for entering command mode.
- Map <Space><Space> to local leader key.

**Comment by liuchengxu** [comment]
Agree with mapping `Enter` for entering command mode. But do we have to leave `,` alone? You know, `,` has been used in some layers under `+lang` topic in order to keep consistency with major mode prefix in spacemacs. Any thoughts on this?

**Comment by liuchengxu** [comment]
Hi, @yzhuang . I have updated [vim-better-default](https://github.com/liuchengxu) with change `;` to `<CR>` for entering command mode.

**Comment by yzhuang** [comment]
Changing <CR> to enter command mode sounds good. 
I am OK with the behavior of comma, and I can unmap it myself for my own needs.  

Thanks!  :)

**Comment by duduscript** [comment]
Hi @yzhuang, I prefer using comma back search with f/F/t/T too, could you share your solution?

**Comment by yzhuang** [comment]
@duduscript  
I simply don't use the comma key anymore.
In the latest version of space-vim, the semicolon key is untouched, and I use it for searching forward. 

E.g. for searching forward, I use `f`. If I want to search backward, I'd use `F`.  With that, I only need the semicolon now.

**Comment by duduscript** [comment]
@yzhuang Thank you
