### ISSUE TITLE
[help] Running along side Vundle or NeoBundle

### ISSUE THREAD

**Issue by bweston92** [liuchengxu/space-vim#113]
#### Environment

- OS: Linux
- vim: 8.0
- neovim: n/a

#### Problem Description

So I have installed SpaceVim and wanted to add a plugin. For example ["phpcomplete"](https://github.com/m2mdas/phpcomplete-extended) so I need either Vundle or NeoBundle but how can I install these along side SpaceVim?

Sorry for any inconvenience, Brad.

**Comment by liuchengxu** [comment]
Is that a typo? Or you just get confused somehow :). SpaceVim and space-vim are two different projects. If what you have installed is space-vim, please see #112 for adding your private plugins. What's more, space-vim uses only one vim plugin manager: [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by bweston92** [comment]
Thanks, and sorry I mean "space-vim" :)
