### ISSUE TITLE
looking for a theme default for this with background to be full black #000000

### ISSUE THREAD

**Issue by dimitrieh** [liuchengxu/space-vim#114]
Anyone got a good recommendation? Or perhaps this a feature request for a space-vim native full black theme?

**Comment by liuchengxu** [comment]
If you use space-vim, put this in `UserConfig()`:

```vim
hi Normal ctermbg=0 guibg=#000000
```

Or you could add [space-vim-dark theme](https://github.com/liuchengxu/space-vim-dark) into your own vim configuration, then change the background color:

```vim
color space-vim-dark
hi Normal ctermbg=0 guibg=#000000
```

Is this what you want?

**Comment by dimitrieh** [comment]
@liuchengxu thanks! this works like a charm.. any method i could change the bg of the gutter as well?

**Comment by liuchengxu** [comment]
Add this:
```vim
hi SignColumn ctermbg=0 guibg=#000000
```
