### ISSUE TITLE
Is this project related to https://spacevim.org/ ?

### ISSUE THREAD

**Issue by sztomi** [liuchengxu/space-vim#115]
#### Environment

n/a

#### Problem Description

It looks like there is a similarly named and aimed project at https://spacevim.org/. Are the two related in any way?

**Comment by liuchengxu** [comment]
The two projects are different projects actually.  They are maintained by different people with a distinct goal. I'm both a vimmer and spacemacs user. I think you could find more elements similar to spacemacs in space-vim.
