### ISSUE TITLE
Invalid expression: g:layer_path[l:layer] . '/packages.vim'

### ISSUE THREAD

**Issue by rexlv** [liuchengxu/space-vim#116]
#### Environment

- OS: ubuntu16.04
- vim: vim8.0

#### Problem Description

After installing space-vim, I got the following errors evertime when startuping vim:
`
$ vim

Error detected while processing function spacevim#end[17]..<SNR>8_load_packages:
line    3:
E716: Key not present in Dictionary: 
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
Error detected while processing function spacevim#end[34]..<SNR>8_load_config:
line    3:
E716: Key not present in Dictionary: 
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
Press ENTER or type command to continue
`
But when I tap ENTER, everthing works fine! 
How can I deal with this? 

Features for vim like lua, python3, syntax are included.

**Comment by liuchengxu** [comment]
Have you created a new Layer locally? Please try `:LayerUpdate` in vim.

**Comment by rexlv** [comment]
:100: You inpired me! I enter `:LayerStatus` to list Enabled Layers, and found that I added a wrong layer to `.spacevim`. How can I be so careless!!! Thanks very much for your great work.
