### ISSUE TITLE
Very slow when using hyper

### ISSUE THREAD

**Issue by kristojorg** [liuchengxu/space-vim#117]
#### Environment

- OS: Mac OS Sierra 10.12.3
- vim: ???
- neovim: 0.1.7

#### Problem Description

spacevim causes extreme slowness why using hyper.app, I'm a very novice vim user and am not sure what the cause is.

**Comment by liuchengxu** [comment]
Not very sure about your use case. Do you mean [hyperapp](https://github.com/hyperapp/hyperapp)?

**Comment by kepbod** [comment]
I think he means https://github.com/zeit/hyper.

**Comment by liuchengxu** [comment]
@kepbod Thanks.

@kristojorg Could you elaborate your problem? Is it normal in terminal? Does the slowness refer to the startup of vim in hyper?

**Comment by zhenjun115** [comment]
Hyper is build using nodejs, and it run slowly compared to other iterm.

**Comment by kristojorg** [comment]
So sorry for the barebones issue, I meant to fill it in more but got distracted. I have uninstalled and reinstalled spacevim and it is now running at a normal speed. Not sure what was causing it to be so slow, but if I run in to it again I will record and report. thanks!
