### ISSUE TITLE
中文的配置是不是独立到一个叫 chinese 的 layer 里

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#12]
https://github.com/liuchengxu/space-vim/blob/2ef10e9a199be3a390e1bb27ef19ac32d0ff4ed2/layers/%2Bvim/better-defaults/config.vim#L31-L61
这里的配置对于非中文用户是不是会比较困扰？

**Comment by liuchengxu** [comment]
有道理！

**Comment by liuchengxu** [comment]
已经转移到 chinese layer 中。
