### ISSUE TITLE
Weird cursor behaviour when typing brackets or parenthesis

### ISSUE THREAD

**Issue by noncototient** [liuchengxu/space-vim#120]
#### Environment

- OS: macOS Sierra 10.12.3 (16D32)
- vim: space-vim 0.5.0 @ 800

#### Problem Description

Typing brackets or parenthesis results in a strange cursor behaviour. 

Whenever brackets or parenthesis are closed, the cursor jumps back to the first bracket and then jumps in front after the closing bracket. 

I was not able to figure out which plugin results in this behaviour. 

Also, weird cursor behaviour with lexima.vim (bracket/parenthesis autoclosing) plugin installed, where the cursor flicks between being a line and a block when deleting in insert mode.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/packages.vim#L13 , space-vim uses [auto-pairs](https://github.com/jiangmiao/auto-pairs) to obtain parentheses autoclosing when progamming Layer enabled.  Both [auto-pairs](https://github.com/jiangmiao/auto-pairs) and [lexima.vim](https://github.com/cohama/lexima.vim) work well in my case, I can't reproduce your issue. Could you show me an example? And what's your `Layers()` function?

**Comment by noncototient** [comment]
Thanks for your quick reply! 

Not sure what my layer is, I'm just using a default install. Couldn't find any docs on how to enable different layers just when doing a quick search.

Take a look at this video, you can see how the cursor jumps back and forth: http://recordit.co/6OabGXCvaZ

**Comment by noncototient** [comment]
Also quick note. The brackets and parenthesis are not autoclosing. Have to close them manually.

**Comment by liuchengxu** [comment]
Try editing `.spacevim` in your home directory, use `Layer` command to enable programming Layer:

```vim
function! Layer()
    " Default Layers
    Layer 'fzf'
    Layer 'unite'
    Layer 'better-defaults'
    " Add programming Layer
    Layer 'programming'
endfunction
```

Please refer to [layer](https://github.com/liuchengxu/space-vim/wiki/layer) for more information.

**Comment by noncototient** [comment]
Added the programming layer and the issue is now fixed. Thank you so much @liuchengxu!

Loving this vim setup, man!

**Comment by zhenjun115** [comment]
auto-pairs will help you to complete bracket when you type the first left symbol, but it won't help you to complete broken bracket. It is not an issue.

**Comment by noncototient** [comment]
For anyone who is having the same issue even when using stock Vim, this behaviour is caused by `showmatch` functionality in Vim.

Check your .vimrc and see if its there, then remove it and the cursor should start acting normally again.

**Comment by michael-t94** [comment]
> For anyone who is having the same issue even when using stock Vim, this behaviour is caused by `showmatch` functionality in Vim.
> 
> Check your .vimrc and see if its there, then remove it and the cursor should start acting normally again.

Thank you, this solved my problem.
