### ISSUE TITLE
How to show time in the status line?

### ISSUE THREAD

**Issue by zongUMR** [liuchengxu/space-vim#123]
#### Environment

- OS: mac OS
- vim: latest version 
- neovim: N/A

#### Problem Description

I install the latest vim version by brew and I have a problem is how I can show the current time in the status line? Just like '2017-3-30 23:06:11'.

Thanks a lot

**Comment by liuchengxu** [comment]
I don't think it's a good idea to show time in status line. You could use `strftime()` to obtain the goal. However, It doesn't update time if you issue no keystrokes, but as soon as you do anything at all in the editor, you will get the current time (see [here](http://vim.wikia.com/wiki/Display_date-and-time_on_status_line)). I don't know whether you can tolerate the shortcoming. I have pushed a new branch in [eleline.vim](https://github.com/liuchengxu/eleline.vim/tree/time), you can give it a go.

```vim
function! Layers()
    Layer 'better-defaults', { 'exclude': 'liuchengxu/eleline.vim' }
endfunction

function! UserInit()
    Plug 'liuchengxu/eleline.vim', { 'branch': 'time' }
endfunction
```

**Comment by zongUMR** [comment]
I see. Thanks for your reply.
