### ISSUE TITLE
Question: Why use CtrlP when FZF can do the same?

### ISSUE THREAD

**Issue by rakr** [liuchengxu/space-vim#124]
Hi,

Both FZF and CtrlP are part of space-vim packages. Both of do fuzzy finding searches.
Typing `:Files` triggers the search using FZF, <kbd>Ctrl</kbd><kbd>P</kbd> triggers the search using CtrlP.
It seems like there is one too many, my opinion would be to keep FZF and remove CtrlP.

Would love to hear your thoughts on this.

**Comment by liuchengxu** [comment]
>A command-line fuzzy finder written in Go -- fzf

[fzf](https://github.com/junegunn/fzf) is definitely an amazing command-line tool for terminal guys, whereas not everyone lives in the terminal. fzf is not so perfect in GVim in my opinion, so I remain the similar plugin [ctrlp](https://github.com/ctrlpvim/ctrlp.vim). Please let me know if I miss something.

**Comment by rakr** [comment]
Spot on, I never use gvim, so I do live in the terminal, so I never realised that FZF did not work in graphical vim.

I'm seeing different options:

* do nothing, and leave it to the user to configure FZF instead of CtrlP (that's what I've done so far)
* In space-vim, if terminal then use FZF if gvim use CtrlP

Both of these options have pros and cons, so probably worth getting other people's opinion.

**Comment by tracyone** [comment]
unite has same function of ctrlp and fzf too

**Comment by liuchengxu** [comment]
@tracyone Since the active development on unite.vim has stopped, I think we should put it on a low priority.

**Comment by liuchengxu** [comment]
@rakr  Or we could have another option: keep both of them. Here are my thoughts:

- Ctrlp.vim is usually invoked via `C-p`. I think it has no conflicts with key bindings from fzf, which is invoked by <Leader> related mappings.
- Ctrlp.vim has little impact on the performance of startup in vim and the speed of searching is also acceptable. What we have to pay are just some bits in the disk :).

**Comment by rakr** [comment]
I gave up on CtrlP a long time ago, especially if you are like me and fire Vim in your home directory and then you look for a file. with CtrlP it takes ages, so I quickly added the silver searcher to the mix and when I found FZF that was a revelation.

I don't have any issue with keeping them both, but I think that having two tools to do the same thing is on too many.

I also recognise the fact that people do have different preferences and work differently. Some prefer GUI over terminal while others have the opposite preference.

The solution I've used (to remap `C-p` to FZF works perfectly for me as it avoids my silly mistake. I'll document this in the readme if you wish.

**Comment by liuchengxu** [comment]
Yes, I also intend to write a tutorial about the plugins used in space-vim. Maybe we could put the tutorial in wiki and add this into it.

**Comment by liuchengxu** [comment]
Thanks to great junegun, now fzf can also run inside GVim using the new builtin terminal emulator of Vim 🎉 , see [this post](https://junegunn.kr/2017/09/fzf-0.17.0). Thus, now only when users use gui vim without the terminal feature, space-vim start to use [LeaderF](https://github.com/Yggdroot/LeaderF) instead, which is also a nice option. CtrlP has been separated out as a single layer already.

<img width="811" alt="2017-10-15 9 35 00" src="https://user-images.githubusercontent.com/8850248/31580790-a24bcf06-b11f-11e7-816b-875bfd3e95cb.png">

**Comment by liuchengxu** [comment]
Two years later, I create another brand new similar plugin [vim-clap](https://github.com/liuchengxu/vim-clap) which is in pure vimscirpt and the minimal dependency. It's not for replacing the others completely but merely a new option, especially good for the windows users in my opinion. You can enable it by adding `let g:spacevim_enable_clap = 1` to your .spacevim.

![substring](https://user-images.githubusercontent.com/8850248/65833395-9d4cb300-e302-11e9-9574-327d053f3389.gif)
