### ISSUE TITLE
Window jumping

### ISSUE THREAD

**Issue by zongUMR** [liuchengxu/space-vim#125]
#### Environment

- OS: Mac
- vim: 8.0
- neovim: N/A

#### Problem Description
Is there any method that I can jump to the window with more than three windows ? Just like`space w W` in spacemacs.

**Comment by liuchengxu** [comment]
In terminal, you can try <kbd>SPC w ?</kbd> or `:Windows` powered by [fzf.vim](https://github.com/junegunn/fzf.vim), which can help you jump among multiple windows.

**Comment by zongUMR** [comment]
I get it. But I think the way is better in spacemacs, because I can jump to the specific window by press one word. :)

**Comment by liuchengxu** [comment]
Agree with you :).

**Comment by tracyone** [comment]
vim-choosewin

**Comment by zongUMR** [comment]
@tracyone wonderful! thank you

**Comment by liuchengxu** [comment]
Nice! I'll add it later. But I think <kbd>SPC w w</kbd> is a better mapping for this operation as `W` is not so convenient after all.
