### ISSUE TITLE
How to paste from system clipboard in Ubuntu?

### ISSUE THREAD

**Issue by GHAIGIT** [liuchengxu/space-vim#126]
I tried right click to paste from ubuntu clipboard, but nothing happened.
So how to copy and paste with right click in space-vim?

**Comment by liuchengxu** [comment]
I don't use the mouse in vim actually. I'm afraid of giving you some help about this :).

**Comment by tracyone** [comment]
set mouse=

**Comment by yzhuang** [comment]
Clicking mouse buttons in vim is kinda inefficient anyway.

As part of vim-better-defaults:
```
plugin/default.vim:  set clipboard=unnamedplus,unnamed
plugin/default.vim:  set clipboard+=unnamed
```

This makes vim's default register work with the system clipboard.
This mean, in vim, you can just press "p" in normal mode to paste from system clipboard.
This works for me in ubuntu 16.04 LTS. 

If this does not work for you, try these two things:
1. make sure your vim has clipboard feature enabled. (type `vim --version` and see if you have +clipboard).  If you use neovim, you should be good.
2. Install xclip, `sudo apt install xclip`

**Comment by ztlevi** [comment]
The shortcut key is set to be Ctrl+Shift+c and v...
