### ISSUE TITLE
Problem about tmux theme

### ISSUE THREAD

**Issue by JayceCao** [liuchengxu/space-vim#127]
I saw that your tmux status line shows some small icons... Do it implement through vim?

**Comment by liuchengxu** [comment]
No, they're merely emojis :), see https://github.com/liuchengxu/dotfiles/blob/master/tmux.conf .

**Comment by JayceCao** [comment]
Thanks a lot ;-)

On Apr 2, 2017 09:27, "Liu-Cheng Xu" <notifications@github.com> wrote:

No, they're merely emojis :), see https://github.com/liuchengxu/
dotfiles/blob/master/tmux.conf .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/liuchengxu/space-vim/issues/127#issuecomment-290958384>,
or mute the thread
