### ISSUE TITLE
Layers +vim/better-defaults and +distributions/spacevim deal with the same

### ISSUE THREAD

**Issue by rjcoelho** [liuchengxu/space-vim#128]
Both deal with "better default key bindings" and I don't know what to use/load.

We should probably:
1) move what makes since from +vim/better-defaults into liuchengxu/vim-better-default (which +distributions/spacevim loads) and
 
2) the rest split into per-package layer under tools (easymotion, nerdtree, incsearch, rename) and include on programming layer (vim-surround, ...)

Comments ? thanks!

**Comment by liuchengxu** [comment]
Yeah, I'm also planning to reorganize the structure of layers, especially for better-defaults and programming layer. Here are my cursory thoughts:

- split vim-easymotion related and add vim-sneak to make a new layer, let's call it better-motion layer?
- split vim-snippets to make a snippet layer?

I welcome any ideas about this.

**Comment by rjcoelho** [comment]
Another idea is to move any file/tree plugin such as nerdtree or vim-range into a +tools/file-manager layer.

My goal is to kill any "miscellaneous" layer that incluir assorted things, such as the +vim/better-defaults.

**Comment by liuchengxu** [comment]
Good point!

**Comment by rjcoelho** [comment]
Maybe also move
* vim-startify and vim-better-whitespace to +distributions/better-defaults
* vim-surround, vim-cursorword and vim-multiple-cursors to programming
* incsearch to new +tools/incsearch layer
* rename.vim to +tools/file-manager

With this you can delete existing +vim/better-defaults

**Comment by liuchengxu** [comment]
Agree with moving +vim/better-defaults to +distributions/better-defaults as well as rename.vim to +tools/file-manager. 

Since programming layer is a little bloated now, I think it's better to take more time to consider its structure.

**Comment by liuchengxu** [comment]
Hi, @rjcoelho . I want to split some basic plugins from programming layer to new a +distribution/spacevim-base layer, e.g., luochen1990/rainbow, jiangmiao/auto-pairs, sheerun/vim-polyglot. Any idea?

**Comment by rjcoelho** [comment]
Well @liuchengxu create a "+programming/syntax_indentation" with vim-polyglot and a "+programming/editing" with surrounding, auto-pair and all similar.

I don't like "+distribution/spacevim-base", its a miscellaneous catch all that assumes vim will be used for programming is we follow you suggestion.

**Comment by liuchengxu** [comment]
Agree with "+programming/editing" :+1: .
