### ISSUE TITLE
 fatal: invalid reference: master

### ISSUE THREAD

**Issue by hijkzzz** [liuchengxu/space-vim#132]
#### Environment

- OS: MacOS
- vim: 8
- neovim: ???

#### Problem Description

When execute the command "PlugUpdate"
There is an error:

x python-mode
     fatal: invalid reference: master

How to fix it ?

**Comment by liuchengxu** [comment]
I think it's related to vim-plug. Try updating python-mode manually, enter `~/.vim/plugged/python-mode` and see if you can update it on your own.
