### ISSUE TITLE
Update issues when layers are moved

### ISSUE THREAD

**Issue by Grafikart** [liuchengxu/space-vim#136]
#### Environment

- OS: All of them
- vim: 8.0.X

#### Problem Description

After an upgrade `git pull origin master`, vim tries to load layers from previous directories : 
```
~/.space-vim/layers/+vim/better-defaults/packages.vim
```
It should load it from 
```
~/.space-vim/layers/+distributions/better-defaults/packages.vim
```
So I have these 2 errors : 
```
[space-vim] /Users/Jonathan/.space-vim/layers/+vim/better-defaults/packages.vim does not exist, which may cause unexpected errors.
[space-vim] /Users/Jonathan/.space-vim/layers/+vim/better-defaults/config.vim does not exist, which may cause unexpected errors.
```

**Comment by Grafikart** [comment]
After further research I found a file `.spacevim/core/autoload/info.vim` that contained the old path. Removing this file fixed this issue. Dunno why it wasn't deleted from the git pull

**Comment by liuchengxu** [comment]
I forgot document this, run `:-(. `info.vim` is not part of the repo.It's created

**Comment by liuchengxu** [comment]
Run `:LayerUpdate` to get rid of the error, I'll document it in the README or find a better solution.

`info.vim` is not part of the repo. It's created automatically when the neccessy infomation is missing https://github.com/liuchengxu/space-vim/blob/master/core/autoload/layer.vim#L126-L132 , which can let space-vim don't have to scan the whole `layers` directory to get the information every time. The shortcoming is that when the layers' structure is changed, we have to run `:LayerUpdate` manually to update it.

**Comment by liuchengxu** [comment]
Hi, @Grafikart .  space-vim now can smoothly cope with the change of *layers* structure. Please let me know if this issue still exists.

**Comment by Grafikart** [comment]
The issue doesn't exist anymore 👍
