### ISSUE TITLE
ale ont loaded when open python file

### ISSUE THREAD

**Issue by steinliber** [liuchengxu/space-vim#137]
#### Environment

- OS: macos
- vim: 8.0
- neovim: ???

#### Problem Description
I edit python file and get into insert mode, but ale not loaded 
![image](https://cloud.githubusercontent.com/assets/13215800/24939451/fa7ac980-1f6f-11e7-8f7b-28280178b3c9.png)
 Only i run :ALEENABLE , it works..

**Comment by liuchengxu** [comment]
Yeah, it's intended, because I find ale can cause tens of milionseconds delay to the startup of vim for some linters. If you don't care about it and want to enable it without lazy loading, exclude it and put it in `UserInit()`.
```
function! Layers()
    Layer 'syntax-checking', { 'exclude': 'w0rp/ale' } 
endfunction
function! UserInit()
    Plug 'w0rp/ale'
endfunction
```
