### ISSUE TITLE
Error message on startup when unite layer is not included.

### ISSUE THREAD

**Issue by yzhuang** [liuchengxu/space-vim#139]
#### Environment

- OS: OS X 10.12.4
- vim: N/A
- neovim: 0.1.7

When I remove the 'unite' layer, i get the following error on startup:
```
Error detected while processing function spacevim#end[37]..UserConfig:
line    8:
E31: No such mapping
```

fzf provides all the functionality I need, so I am trying to remove unite and ctrlP.

**Comment by liuchengxu** [comment]
It makes no sense. It should be ok with the `unite` Layer disabled. When you enable `unite` Layer, everything is fine, but the error occurs when you disable `unite` Layer?

**Comment by yzhuang** [comment]
Could not reproduce anymore after clean install. 
Closing ticket as I cannot reproduce.
