### ISSUE TITLE
如何修改左侧行号

### ISSUE THREAD

**Issue by programscape** [liuchengxu/space-vim#140]
#### Environment

- OS: ubuntu
- vim: 8.0
- neovim: no

#### Problem Description

请问怎么控制左侧行号不自动变动，变动会导致每次：行号都需要先心算一遍，非常不方便，开发者是出于什么样的目的使用此功能呢？暂未发现此功能作用。

**Comment by programscape** [comment]
已经自行解决

**Comment by liuchengxu** [comment]
可能会有这样的一个使用场景: 对当前行的附近进行某些操作，比如删除当前行下方的5行，那么此时相对行号就会比较有用了。

**Comment by programscape** [comment]
@liuchengxu 虽然已经解决过一次，不过重换系统又忘了，作者能把这个功能加入配置文件开关里么？如果代码里不方便加的话，能否加入文档中，每次都找很久才能找到方法，谢谢了。

**Comment by liuchengxu** [comment]
其实很简单, 只要知道这是相对行号, 在 `UserConfig()` 中覆盖默认设置就可以了:

```vim
function! UserConfig()
    set norelativenumber
endfunction
```

**Comment by programscape** [comment]
@liuchengxu  thanks，又麻烦作者了，还是希望能加入文档一下，方便和我同样需求的vim新人。

**Comment by liuchengxu** [comment]
好的, 其实我打算准备这一个稍微完整点的教程，不过最近有点忙，还没有一个初期版本。

**Comment by sandacn** [comment]
我来更新一下这个配置如何修改：
在 ~/.SpaceVim.d/init.vim 文件中增加：
`vimrc
let g:spacevim_relativenumber = 0
`

**Comment by liuchengxu** [comment]
@sandacn  你搞错了，[space-vim](https://github.com/liuchengxu/space-vim) 与 [SpaceVim](https://github.com/SpaceVim/SpaceVim) 是两个不同的项目。
