### ISSUE TITLE
add programing/editing error

### ISSUE THREAD

**Issue by steinliber** [liuchengxu/space-vim#149]
#### Environment

- OS: macos
- vim: 8.0
- neovim: ???

#### Problem Description

I try use `Layer 'editing'` and `Layer/editing`, but it doesn't work

**Comment by liuchengxu** [comment]
not work? Can you elaborate? The layer `editing` is split from the other layers. It should work just like before.

**Comment by steinliber** [comment]
When I add editing layer, get this error
`
Error detected while processing function spacevim#end[17]..<SNR>2_load_packages:
line    3:
E716: Key not present in Dictionary: editing
E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
Error detected while processing function spacevim#end[34]..<SNR>2_load_config:
line    3:
E716: Key not present in Dictionary: editing
E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
Press ENTER or type command to continue
`

This is my layer status
`
Enabled layers: (21/34)
[=====================]
+ spacevim
+ fzf
+ unite
+ better-defaults
+ emoji
+ goyo
+ html
+ go
+ python
+ markdown
+ airline
+ chinese
+ text-align
+ code-snippets
+ editing
+ programming
+ ycmd
+ syntax-checking
+ git
+ better-motion
+ file-manager
`

Here is my plugin status
`

x vim-polyglot:
    Invalid tag: v2.15.1 (expected: ). Try PlugUpdate.
- indentLine: OK (not loaded)
- SimpylFold: OK (not loaded)
- fzf: OK
- vim-snippets: OK (not loaded)
- rainbow_parentheses.vim: OK (not loaded)
- vim-rsi: OK
- vim_current_word: OK
- incsearch-easymotion.vim: OK (not loaded)
- incsearch-fuzzy.vim: OK (not loaded)
- vim-emoji: OK (not loaded)
- vim-autoformat: OK (not loaded)
- vim-better-default: OK
- ctrlp.vim: OK (not loaded)
- asyncrun.vim: OK (not loaded)
- vim-easy-align: OK (not loaded)
- vim-markdown: OK (not loaded)
- YouCompleteMe: OK (not loaded)
- tagbar: OK
- vim-go: OK (not loaded)
- goyo.vim: OK (not loaded)
- limelight.vim: OK (not loaded)
- vim-move: OK (not loaded)
- gv.vim: OK (not loaded)
- vim-airline-themes: OK
x vim-sneak:
    Invalid tag: 1.8.1 (expected: ). Try PlugUpdate.
- vim-nerdtree-syntax-highlight: OK (not loaded)
- vim-gitgutter: OK
- unite.vim: OK
- incsearch.vim: OK (not loaded)
- vim-airline: OK
- editorconfig-vim: OK (not loaded)
- vim-choosewin: OK
- YCM-Generator: OK (not loaded)
- ctrlp-py-matcher: OK (not loaded)
- fzf-filemru: OK (not loaded)
- nerdtree: OK (not loaded)
- nerdtree-git-plugin: OK (not loaded)
- ultisnips: OK (not loaded)
- space-vim-dark: OK
- rename.vim: OK (not loaded)
- vim-indent-guides: OK (not loaded)
- tabular: OK (not loaded)
- vim-better-whitespace: OK (not loaded)
- vim-easymotion: OK
- vim-startify: OK (not loaded)
- ale: OK
- html5.vim: OK (not loaded)
- fzf.vim: OK
- vim-fugitive: OK
- vim-markdown-toc: OK (not loaded)
- python-mode: OK (not loaded)
- rainbow: OK
- markdown-preview.vim: OK (not loaded)
`

**Comment by liuchengxu** [comment]
Try running `:LayerUpdate`.

**Comment by steinliber** [comment]
Thanks, does this mean every time layer change, i have to run this command once

**Comment by liuchengxu** [comment]
Yes, whenever the structure of `layers` directory is changed, you'll have to run `:LayerUpdate` to update the cached information. I have added the note to the error message. For now, I haven't found a solution to avoid this.
