### ISSUE TITLE
fzf、denite、unite、ctrlp 这四个是功能重复的？

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#15]

**Comment by liuchengxu** [comment]
这几个插件有部分功能是相互重叠的，针对某些场景取一个比较好的，考量的方面有 UI, 速度等等。

**Comment by yesmeck** [comment]
但是现在 fzf 是默认加载的，然后 denite、unite、ctrlp 是放在同一个 Layer 里的。也就是说我想用 ctrlp 的话就要同时启用4个，是不是只要选一个合适的就好了？

**Comment by liuchengxu** [comment]
额，目前的话，还没办法选择 Layer 中的部分插件，要不全用，要么不用... 不喜欢那么多的话，可以先不用这个 Layer, 将 ctrlp 放到 UserInit() 中就可以了。

**Comment by yesmeck** [comment]
Ok then.
