### ISSUE TITLE
NERDTree咋没了

### ISSUE THREAD

**Issue by yuchenyang1994** [liuchengxu/space-vim#152]
#### Environment

- OS: linux
- vim: 8.0
- neovim: --

#### Problem Description
前一阵子还有呢，怎么better-defaultslayer里没有了nerdtree

**Comment by yuchenyang1994** [comment]
nerd tree move to file_manager layer

**Comment by liuchengxu** [comment]
有一些结构上的调整, 可以看这里 #121 .
