### ISSUE TITLE
如何能在space-vim 直接使用鼠标复制呢？

### ISSUE THREAD

**Issue by programscape** [liuchengxu/space-vim#154]
#### Environment

- OS: Ubuntu
- vim: latest
- neovim: no

#### Problem Description

如何能直接在space-vim 上使用鼠标复制，偶尔小规模复制想使用鼠标，但发现无论如何都出不来鼠标，尝试使用v模式，但有时候能行有时候不行，已经查阅文档，但文档上也没有说明。

**Comment by liuchengxu** [comment]
#126 , 另外可以看一下这些:

- https://unix.stackexchange.com/questions/139578/copy-paste-for-vim-is-not-working-when-mouse-set-mouse-a-is-on
- http://vim.wikia.com/wiki/Auto_copy_the_mouse_selection
- http://stackoverflow.com/questions/4608161/copy-text-out-of-vim-with-set-mouse-a-enabled
