### ISSUE TITLE
更新后一点小问题

### ISSUE THREAD

**Issue by yuchenyang1994** [liuchengxu/space-vim#157]
#### Environment

- OS: ubuntu macos
- vim: 8.0
- neovim: ???

#### Problem Description

更新后，异步检查代码插件ale第一次开启不启用，必须aletoggle两次后才能正常工作

**Comment by liuchengxu** [comment]
I can reproduce and have reported to ALE.

**Comment by liuchengxu** [comment]
Please update space-vim, the issue should be fixed.

**Comment by yuchenyang1994** [comment]
thank you, it's worked
