### ISSUE TITLE
Quite slow startup on win platform

### ISSUE THREAD

**Issue by andytian1991** [liuchengxu/space-vim#158]
#### Environment

- OS: win7 
- vim: 8.0.586
- neovim: N

#### Problem Description

Quite slow startup the first time opening, but after opening it can still be very smooth to use.
Is there some plugin slowing it down?  ps. using the default .spacevim, no other persional config added.

**Comment by liuchengxu** [comment]
Can't reproduce. It's normal in my case (vim8 + win8). Use `vim --startuptime vim.log` to indentify the slowest plugin.
