### ISSUE TITLE
ctrl+i always jumps to error place while ctrl+o jumps works fine

### ISSUE THREAD

**Issue by longhai123** [liuchengxu/space-vim#159]
#### Environment

- OS: ubuntu16.04
- vim: 8.1

#### Problem Description

when I use ctrl+i to jump  to previously visited locations, it always jumps to error place. I tryed to use the :jumps command to find some rule, but also failed. Has anyone ever encountered this problem?

**Comment by longhai123** [comment]
@zer4tul

**Comment by liuchengxu** [comment]
Please post more info.

**Comment by longhai123** [comment]
Maybe someone will meet the same problem, I solved it in this way: add "nunmap <C-I>" in private/config.vim can solve the problem.
