### ISSUE TITLE
YouCompleteMe can't be invoked in JS file.

### ISSUE THREAD

**Issue by sqrthree** [liuchengxu/space-vim#163]
#### Environment

- OS: macOS Sierra
- vim: 8.0
- neovim: ???

#### Problem Description

YouCompleteMe can't be invoked in JS files. The file type of the JS file in the vim is `javascript`, but it's `js` in [/ycmd/packages.vim#L18](https://github.com/liuchengxu/space-vim/blob/master/layers/%2Btools/ycmd/packages.vim#L18).

![image](https://cloud.githubusercontent.com/assets/8622362/26033283/c4804f0a-38db-11e7-8283-1fb40439d032.png)

**Comment by liuchengxu** [comment]
PR is welcome, or I'll fix it by tomorrow.

**Comment by liuchengxu** [comment]
Done.
