### ISSUE TITLE
How can I install my own plugin, I am beiginner,Please Help!

### ISSUE THREAD

**Issue by UOvOU** [liuchengxu/space-vim#167]
#### Environment

- OS: mac
- vim: vim 8.0

#### Problem Description

I have no idea to install plugin,the example of package.vim is to complex...

**Comment by liuchengxu** [comment]
Put your own plugins in `UserInit()` of `.spacevim` in your home directory, e.g., add [oni](https://github.com/extr0py/oni):

```vim
function UserInit()
     Plug 'extr0py/oni'
endfunction
```

Then reload vimrc (`:source $MYVIMRC` or <kbd>SPC f R</kbd>)and run `:PlugInstall` to install.

**Comment by UOvOU** [comment]
Thanks,I got it.
