### ISSUE TITLE
Two requests: save/restore window size (gvim) and documentation to change menu/help language

### ISSUE THREAD

**Issue by andrecbarros** [liuchengxu/space-vim#168]
#### Environment

- OS: Windows (and linux)
- vim: 8.0.6x
- neovim: (didn´t try yet)

#### Problem Description

Add save/restore window position for gvim, right now I´m using what can be found on (works wonderfully):
"http://vim.wikia.com/wiki/Restore_screen_size_and_position"

The other request is to insert on documentation (README.md?) a proper way to customize the interface language. I´m using the following on the end of .vimrc:
set langmenu=en_US
let $LANG = 'en_US'
language messages en
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

Thank you for the best "automatic" customization of vim I have ever used!

Regards,
André

**Comment by liuchengxu** [comment]
Actually, space-vim already did this in [spacevim layer](https://github.com/liuchengxu/space-vim/blob/daceb98d9a2fa50b3969a109551812f994fb4836/layers/%2Bdistributions/spacevim/config.vim#L36-L39)  (except `language messages en`) 

Feel free to open up a PR about the gvim setting. I think it's good to add it in https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/spacevim/config.vim#L53 .

**Comment by liuchengxu** [comment]
Thanks, @andrecbarros . The functionality of saving and restoring window size has been incorporated into space-vim.
