### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#171]
#### Environment

- OS: Ubuntu Server 14.04.1
- vim: 8.0
- neovim: v0.2.1-dev

Error after install

`Error detected while processing VimEnter Auto commands for "*": E492: Not an editor command:       Startify|  endif`

**Comment by liuchengxu** [comment]
Are you sure vim-startify has been installed already?

**Comment by zhenjun115** [comment]
The problem is solved, caused by vim-startify not installed. 3x
