### ISSUE TITLE
可以把我的插件LeaderF加进去吗？

### ISSUE THREAD

**Issue by Yggdroot** [liuchengxu/space-vim#174]
https://github.com/Yggdroot/LeaderF
要比ctrlp好。

**Comment by liuchengxu** [comment]
谢谢, 这样刚好可以把 ctrlp 分离出来, 如果方便的话，不知道是否可以提个 PR?  现在 terminal 下用的是 fzf, 刚好把 LeaderF 放在 GUI 下使用.

**Comment by Yggdroot** [comment]
我还没研究过你的代码，还不知道怎么加，能给些提示吗，或者你把它加上？
~~一点也不抽象，跟ctrlp一脉相承，只是一个快捷键的名字`<leader>f`.~~

**Comment by liuchengxu** [comment]
好的，我先尝试把它集成进来, 然后你看有不合适的地方再进行改进.

**Comment by Yggdroot** [comment]
其实不谦虚的说，LeaderF的fuzzy match算法比fzf要好，可以用更少的键击次数找到目标，而且速度也不比fzf慢。唯一比不上的是fzf可以异步，就是在第一次检索还没有完成的时候可以输入，这是因为vim本身没法支持多线程，虽然是用Python实现，也无法开启第二个包含vim操作的线程。好在LeaderF里面内置了`rg`, `pt`, `ag`, `find`, `git ls-files`等命令，可以在很短的时间内建好索引，然后会缓存起来，接下来就是飞速的体验了。
而且我觉得它在找tag方面，比同类插件（ctrlp，unite等）要好很多。更多优点就不一一说明了，只能使用才能体会出来。
你的space-vim有插件使用说明吗，我可以把LeaderF的说明加进去。

**Comment by liuchengxu** [comment]
因为还不太熟悉, 只是设置了一些[快捷键映射](https://github.com/liuchengxu/space-vim/blob/LeaderF/layers/%2Btools/fzf/config.vim#L2-L8), 您可以按照您的最佳设置进行更改.

使用说明的话，可以放在 fzf layer 的 [README](https://github.com/liuchengxu/space-vim/blob/LeaderF/layers/%2Btools/fzf/README.md) 中.

在功能性上, 目前我是把 LeaderF 当成了 “GUI 下的 fzf” :), 所以没有单独创建一个 layer, 而是放到了 fzf layer 中.

**Comment by Yggdroot** [comment]
我看了下，感觉没什么要说明的了。

**Comment by liuchengxu** [comment]
已经加入。

**Comment by Yggdroot** [comment]
谢谢。
