### ISSUE TITLE
How disable undo files?

### ISSUE THREAD

**Issue by edDimensi** [liuchengxu/space-vim#181]
#### Environment

- OS: arch-manjaro
- vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun  8 2017 20:53:45)

#### Problem Description

After change files, vim create $filename.un~. How disable that function? I try :set noundofiles, this not work.

**Comment by edDimensi** [comment]
i write in userConfig section that code
```
set noundofiles
```
problem resolve.

**Comment by liuchengxu** [comment]
Given that many people seemingly don't like the undo functionality, I'll consider using `set noundofiles` as the default later. Thank you for your attention.
