### ISSUE TITLE
Behaviors on switching between command and insert mode

### ISSUE THREAD

**Issue by Marlin-Na** [liuchengxu/space-vim#184]
Hi, these are behaviors on my computer:

1. If I press "o" at the beginning of a line, then press "Esc", then "k", it will re-enter the insert mode. Thus I have press "Esc" two times to return back to command mode.
2. If I press "o" at a line, then press "Esc" two times, then press "k", it will switch the new line with the previous line.
3. I found that I can not use backspace in block insert, i.e. to use ctrl-v to select a column, then press "I", then "backspace", I would expect to delete a character in all the involved rows, but only have effect on the first row.

Are these behaviors default options/features introduced by space-vim? Any clue on how to disable these features?

Thanks!

#### Environment

- OS: openSUSE tumbleweed
- vim: 8.0

**Comment by liuchengxu** [comment]
I can't reproduce this. In my case, `o` begins a new line and enter insert mode, `esc` turns back to normal mode, `k` goes one line upward.

**Comment by Marlin-Na** [comment]
Hi,

I am attaching my `.spacevim` file below, which should be a quite simple one.. and I have also recorded a screencast

![screencast_07-09-2017_05-15-29 pm](https://user-images.githubusercontent.com/9980776/27992871-68013a16-64d0-11e7-8d0f-b7fc0e10cbb1.gif)

I forgot to mention that on my computer, a short time interval between "Esc" and "k" is required to reproduce the problem, if I wait for one or two seconds, it will behave normally.

Another hint is that when I exit insert mode with multiple "Esc" key press, then immediately press "k", vim will say "1 line indented" and switch the two lines.. see my screencast.




```vim
" Let vim and neovim share the same plugin directory

let g:spacevim_plug_home = '~/.vim/plugged'


" You can enable the existing layers in space-vim and
" exclude the partial plugins in a certain layer.
" The command Layer and Exlcude are vaild in the function Layers().
function! Layers()

    " Shipped layers in
    Layer 'fzf'
    Layer 'unite'
    Layer 'better-defaults'

    Layer 'python'
    Layer 'programming'
    Layer 'syntax-checking'

endfunction

" Private plugins
function! UserInit()

    " Space has been set as the default leader key,
    " if you want to change it, uncomment and set it here.
    " let g:spacevim_leader = "<\Space>"
    " let g:spacevim_localleader = ','

    Plug 'jceb/vim-orgmode'
    " vim-speeddating is a dependency of vim-orgmode
    Plug 'tpope/vim-speeddating'

    Plug 'Valloric/YouCompleteMe'

endfunction

" Override the default settings
function! UserConfig()

    autocmd FileType python setlocal completeopt-=preview

    set noundofile
    
    set whichwrap=b,s,<,>

endfunction
```

**Comment by Marlin-Na** [comment]
Update: combining "Esc" and "j", "k" in command mode can move a line up or down... See:

![screencast_07-09-2017_06-29-55 pm](https://user-images.githubusercontent.com/9980776/27993124-9ba3779e-64d5-11e7-82f3-987f0b2d835c.gif)

**Comment by liuchengxu** [comment]
Thanks for your patient description, but I still can't reproduce this issue on my computer (already trying with a short time interval). What's more, these misbehaviors are nonsense.

- Does it exist when you diable your own plugins, i.e., `jceb/vim-orgmode` and `tpope/vim-speeddating`. Not sure if there are conflicts between these plugins.
- Is there any particular key mappings configuration in your terminal emulator?

**Comment by Marlin-Na** [comment]
Hi, thanks for your explanation!

On my computer, the problem can be traced back to the "programming" layer. With the "programming" layer (and removing other layers and plugins in `.spacevim`), the problem still exists. While removing all layers and plugins, the problem disappeared.

I can reproduce the problem in system terminal (i.e. using `ctrl-alt-F3`), thus I think it is not related to my terminal emulator.

Another note/hint: as described previously, in insert mode, `Esc` then `k` will reenter the insert mode, however, `Esc` then `j` will insert `<F20>` characters and reenter the insert mode.  As I browse the source code, I found https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bprogramming/programming/config.vim#L42 which may be related to it? (I don't know, really, I can't read vimscript).

To be clear, I had these problems when I started to use space-vim months ago, recently I updated my space-vim and `.spacemacs` file to figure out whether they can be solved. Maybe it can be helpful locating the problem...

Last thing, the third behavior (using backspace in block insert) is not related to any layer nor plugin on my computer. It exists when I remove all plugins and layers, disappears when I do not use `.vimrc` (i.e. to use `vim -u NONE`). Would you like to reproduce it as well? See my screencast below.

![screencast_07-10-2017_05-00-49 pm](https://user-images.githubusercontent.com/9980776/28010458-98f50b68-6591-11e7-805b-7bfff63717e7.gif)

Finally, space-vim is really a wonderful work, thanks for your effort on it!

**Comment by Marlin-Na** [comment]
Another interesting behavior which may be related. I can reproduce this one disabling all layers and plugins and it disappears using raw vim, thus it is not related to the "programming" layer.

In insert mode, press `j` twice quickly will exit the insert mode... Other keys (including `k`) will not have the effect. See my screencast below, also note the delayed time between pressing `j` and update of content.

![screencast_07-10-2017_05-50-29 pm](https://user-images.githubusercontent.com/9980776/28013481-c9e73eb2-659b-11e7-8472-65a0ae49cd38.gif)

Any clue?

**Comment by liuchengxu** [comment]
>In insert mode, press `j` twice quickly will exit the insert mode.

Well, this behavior is intended, see https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L223-L227 . In insert and command mode, `jj` and `jk` will back to normal mode. If you don't like this config, reset them in `UserConfig()` :

```vim
function! UserConfig()
  iunmap jj
  iunmap jk
endfunction
```
Can you try commenting these suspicious lines https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bprogramming/programming/config.vim#L42-L47 ?

>It exists when I remove all plugins and layers.

About the third behavior, have you disabled `Layer 'spacevim'` in `~/.space-vim/init.vim` ? What does `:PlugStatus` say?

**Comment by Marlin-Na** [comment]
> Can you try commenting these suspicious lines https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bprogramming/programming/config.vim#L42-L47 ?

Commenting those lines solved my problem! Thanks! :tada:
Perhaps you can not reproduce it due to the version of vim? I don't know, though. But this is what `vim --version` shows on my computer.

```
VIM - Vi IMproved 8.0 (2016 Sep 12)
Included patches: 1-566
Compiled by 'http://www.opensuse.org/'
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -fno-strict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.24.1/x86_64-linux-thread-multi/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl    -ltinfo -lacl -lattr -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.24.1/x86_64-linux-thread-multi/CORE  -L/usr/local/lib64 -fstack-protector-strong  -L/usr/lib/perl5/5.24.1/x86_64-linux-thread-multi/CORE -lperl -lm -ldl -lcrypt -lpthread   
```

> About the third behavior, have you disabled Layer 'spacevim' in ~/.space-vim/init.vim ? What does :PlugStatus say?

Sorry, I was wrong... in `vim -u NONE` case, backspace is not available at all in insert mode. By removing (renaming) `.vimrc` file (thus using the system default setting?), the problem still exists. Thus I think this is not related to space-vim, thanks anyway. In my previous description, I just disabled all the layers and plugins in `.spacevim`, did not touch `.vimrc`. `:PlugStatus` says
```
Finished. 0 error(s).
[===]

- vim-better-default: OK
- space-vim-dark: OK
- eleline.vim: OK
```
This is a minor problem in my case. It is currently fine with me.

**Comment by tracyone** [comment]
jj everywhere😊

```vim

inoremap jj <c-[>
cnoremap <expr> j
      \ getcmdline()[getcmdpos()-2] ==# 'j' ? "\<BS>\<C-c>" : 'j'

inoremap j<Space>     j  "insert j immediately
cnoremap j<Space>     j  "insert j immediately

tnoremap   jj         <C-\><C-n>

```

**Comment by liuchengxu** [comment]
If commenting the lines works, then try:

```vim
function! UserConfig()
  set <F20>=
  set <F21>=
endfunction
```
It's inconvenient to modify space-vim directly with respect to performing an update :). I just realize that the root cause may be the keycodes in terminal Vim, see [Mapping fast keycodes in terminal Vim](http://vim.wikia.com/wiki/Mapping_fast_keycodes_in_terminal_Vim).

**Comment by Marlin-Na** [comment]
Yes, it works! Thanks a lot!

**Comment by dgdavid** [comment]
Hi @liuchengxu 

I am having the same problem that @Marlin-Na (with the same environment, openSUSE TW and vim 8)

Could you please quote the exact lines to comment? You are linking the file in the master branch, so I believe right now the lines 42-47 are not the same that you stated. Isn't it?

I suppose you are referring to a `vim-move` configuration, but I want to be sure.

Thanks.

**Comment by liuchengxu** [comment]
@dgdavid Thanks for your pointer. Yes, the exact lines are all related to vim-move. I have updated the comment above and leave it [here](https://github.com/liuchengxu/space-vim/blob/6baa0ed1ddca894314aeba730bc1d7d5a07770ef/layers/%2Bprogramming/programming/config.vim#L15-L20) too.
