### ISSUE TITLE
Idea: create .spacevim from source url

### ISSUE THREAD

**Issue by wadik** [liuchengxu/space-vim#185]
It would be great to be able to generate the custom .spacevim file during the installation. For example:

Install space-vim for both Vim and NeoVim
curl -L https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh | sh -s **--template=https://raw.githubusercontent.com/wadik/space-vim/.spacevim**

**Comment by liuchengxu** [comment]
Nice idea!  I'll work on this and any help is appreciated.

**Comment by liuchengxu** [comment]
I just rewrited [install.sh](https://github.com/liuchengxu/space-vim/blob/master/install.sh). Now when running the quick installer, if `.spacevim` is found in home directory , it will do nothing, or it will generate `.spacevim` from [the template](https://github.com/liuchengxu/space-vim/blob/master/init.spacevim). So, for your case, you can download your personal `.spacevim` before running `install.sh`:

```bash
$ cd $HOME
$ curl -o .spacevim https://raw.githubusercontent.com/wadik/space-vim/.spacevim
$ bash <(curl -fsSL https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)
```

**Comment by wadik** [comment]
Great! Thank you!
