### ISSUE TITLE
how set plug  from neobundle  in vim-plug?

### ISSUE THREAD

**Issue by huos3203** [liuchengxu/space-vim#186]
#### Environment

- OS: 10.13
- vim: 8
- neovim: ???

#### Problem Description
How do install plug from neobundle ?
See:
https://github.com/kballard/vim-swift
Add the following to your .vimrc:
NeoBundle 'kballard/vim-swift', {
        \ 'filetypes': 'swift',
        \ 'unite_sources': ['swift/device', 'swift/developer_dir']
        \}

**Comment by liuchengxu** [comment]
Well, space-vim uses [vim-plug](https://github.com/junegunn/vim-plug) as the default plugin manager. If you want to add some plugins, put them in `UserInit()`, i.e :

```
function! UserInit()
  Plug 'kballard/vim-swift', {'for': 'swift'}
endfunction
```

**Comment by huos3203** [comment]
> @liuchengxu install success!
its doc say:
```
:SwiftVersion                                                  :SwiftVersion                                                
                Prints the current Swift compiler version.  
```
but  I run this command in vim ,print this
```
E492: Not an editor command: SwiftVersion 
```
2. how set `unite_sources` ?

**Comment by liuchengxu** [comment]
Ensure you have opened a swift file, `{'for': 'swift'}` means it will load this plugin only when you open some swift file. Check the plugins' status via `:PlugStatus`, see if `vim-swift` has been loaded.

unite sources are specially required for [unite.vim](https://github.com/Shougo/unite.vim). I'm not familiar with NeoNundle (obsolete) and the swift-related unite sources (note sure [this](https://github.com/kballard/vim-swift/blob/master/autoload/unite/sources/swift.vim) is enough). When you install `vim-swift` successfully using vim-plug, try`:Unite swift/device` `:Unite swift/develop_dir`.

**Comment by huos3203** [comment]
@liuchengxu thanks! 
YES ,vim-swift has been loaded .
but  I try run `:Unite swift/develop_dir` commands :
```
[unite.vim] Invalid source name "swift/develop_dir" is detected.                                                            
[unite.vim] unite.vim: Invalid source  
```

**Comment by liuchengxu** [comment]
The error is related to unite.vim, which is not recommended. Furthermore, I reckon you have found a better choice, I mean, [swift.vim](https://github.com/keith/swift.vim), So we can close this issue :).
