### ISSUE TITLE
install swiftlint plug

### ISSUE THREAD

**Issue by huos3203** [liuchengxu/space-vim#187]
#### Environment

- OS: 10.13
- vim: 7.4
- neovim: ???

#### Problem Description

install `keith/swift.vim` plug by vim-plug
its doc say:
1. new `.swiftlint.yml` in root dir
2. To enable both at once add this to your vimrc:
```sh
    let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
```
I edit this spacevim file with：
```sh
function! UserInit()
    Plug 'keith/swift.vim'     
    let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
endfunction
```
swiftlint not work.

help me!
thanks!

**Comment by liuchengxu** [comment]
Are you sure that [syntastic](https://github.com/scrooloose/syntastic/) and [swiftlint](https://github.com/realm/SwiftLint) has been installed?

**Comment by huos3203** [comment]
Yes , I sure two plugs are installed ,syntastic by `UserInit()` in spacevim, SwiftLint by pkg.
```
Plug ‘vim-syntastic/syntastic’
```
Thanks, I think to use ALE

**Comment by huos3203** [comment]
config ALE style , in spacevim?
![1](https://user-images.githubusercontent.com/4022953/28496250-4b516dae-6f99-11e7-81df-d91e2bd04a0d.png)


but it don't show style that i want
```
>>
---
```

**Comment by liuchengxu** [comment]
Well, if you want to override [the default setting](https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bcheckers/syntax-checking/config.vim#L21-L22) in space-vim, configure it in `UserConfig()`:

```vim
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
```

What's more, check it out via `:echo g:ale_sign_error` and `:echo g:ale_sign_warning`.

**Comment by huos3203** [comment]
thank you! it 's ok!
