### ISSUE TITLE
".spacevim does not exist!!!" occured

### ISSUE THREAD

**Issue by shengyang998** [liuchengxu/space-vim#188]
#### Environment

- OS: macOS Sierra
- vim: 7.4

#### Problem Description

executed the command 
```shell
rm -rf ~/.vimrc;
rm -rf ~/.spacevim;
bash -c "$(curl -fsSL https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)"
``` 

the terminal replyed: 
```shell
==> Trying to clone space-vim
Cloning into '/Users/user_name/.space-vim'...
remote: Counting objects: 189, done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 189 (delta 26), reused 96 (delta 6), pack-reused 0
Receiving objects: 100% (189/189), 55.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (26/26), done.
[✔] Successfully cloned space-vim.
[✔] Setting up vim symlinks.
bash: line 147: /Users/user_name/.spacevim: Is a directory
[space-vim] .spacevim does not exist!!!
[space-vim] Error occurs in UserInit()!
[space-vim] Error occurs in UserConfig()!
Press ENTER or type command to continue
[✔] Now updating/installing plugins using vim-plug

Thanks for installing space-vim. Enjoy!
```

and every time I run `vi `, the error message appeared like the following:
```shell
[space-vim] .spacevim does not exist!!!
[space-vim] Error occurs in UserInit()!
[space-vim] Error occurs in UserConfig()!
```

It seems that the `.spacevim` is a directory which is not suitable for the `SpaceVim`

And in the Customize section, I've found this:
```
You can use `.spacevim` in your home directory to customize space-vim, where you can enable the existing layers, add your extra plugins and private configurations.
```
seems the `.spacevim` should be a file, but the quick installer have done it wrong? 
Should I delete the `~/.spacevim/` directly? or maybe any suggestion? Thanks.

**Comment by liuchengxu** [comment]
`.spacevim` is a file used to customize space-vim. If the quick installer is broken, please try creating `.spacevim` manually. [Here](https://github.com/liuchengxu/space-vim/wiki/.spacevim.template) is the template.

**Comment by shengyang998** [comment]
@liuchengxu haha, yes, my mistake... but both projects didn't work correctly... It was truly embarrassing

**Comment by liuchengxu** [comment]
I think you could delete the whole related file and directories, then install the either one from zero via the quick installer at your own choice. If you try install space-vim, make your vim has `+python` feature.
