### ISSUE TITLE
it not work when edit swift file by vim ?

### ISSUE THREAD

**Issue by huos3203** [liuchengxu/space-vim#189]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  2 2017 08:30:37)
osx 10.13
1. install [SourceKittenDaemon](https://github.com/jpsim/SourceKitten/releases)
2. install `sourcekittendaemon.vim` by vim-plug
3. start Daemon
```
SourceKittenDaemon start  --project /private/tmp/abcde/my.xcodeproj
```
4. `/ping`  return 'OK'

but  it not work, when i run the command `vim file.swift` . file.swift from `/files`

How i know  `sourcekittendaemon.vim`installed by space-vim  is  succeed？

**Comment by liuchengxu** [comment]
Essentially, vim-plug manages the plugins used in space-vim. Check it via `:PlugStatus`, see if [sourcekittendaemon.vim](https://github.com/keith/sourcekittendaemon.vim) has been installed.

**Comment by huos3203** [comment]
@liuchengxu YES, it show OK
```
sourcekittendaemon.vim : OK
```

**Comment by liuchengxu** [comment]
Then check the `omnifunc` option via `:verbose set omnifunc`. By default, it's empty, i.e., you'll see `   omnifunc=`.

If not empty ( should be `omnifunc=sourcekittendaemon#Complete`), based on the README from sourcekittendaemon.vim, you can trigger the omni completion  by  the default mapping `<C-x><C-o>` (Control plus x, Control plus o) after dots. See `:h 'omnifunc'`.

**Comment by huos3203** [comment]
@liuchengxu YES, it's empty!
how set `omnifunc=sourcekittendaemon#Complete`?

**Comment by liuchengxu** [comment]
It should be set automatically when you open some swift file, see [ftplugin/swift.vim](https://github.com/keith/sourcekittendaemon.vim/blob/master/ftplugin/swift.vim). Have you tested in a swift file? You can also try setting `setlocal omnifunc=sourcekittendaemon#Complete`.

**Comment by huos3203** [comment]
thanks! set success，but this plug not work！
