### ISSUE TITLE
Mac 的Iterm终端下，安装有问题

### ISSUE THREAD

**Issue by ThinkCats** [liuchengxu/space-vim#19]
使用 `sh -c "$(curl -fsSL https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)"` 命令进行安装，之后会有错误产生：
`
remote: Counting objects: 1572, done.
remote: Compressing objects: 100% (370/370), done.
remote: Total 1572 (delta 156), reused 0 (delta 0), pack-reused 1176
Receiving objects: 100% (1572/1572), 11.97 MiB | 263.00 KiB/s, done.
Resolving deltas: 100% (754/754), done.
Checking connectivity... done.
[✔] Successfully cloned space-vim.
[✔] Setting up vim symlinks.
Error detected while processing /Users/hehe/.vimrc:
line   15:
E492: Not an editor command: ^M
line   17:
E492: Not an editor command: ^M
line   19:
E492: Not an editor command: ^M
line   21:
E488: Trailing characters
line   24:
E488: Trailing characters
line   27:
E488: Trailing characters
line   31:
E492: Not an editor command: ^M
line   35:
E117: Unknown function: WINDOWS
E15: Invalid expression: WINDOWS()^M
line   65:
E171: Missing :endif
Press ENTER or type command to continue
`
回车键确认后：
`
Error detected while processing command line:
E492: Not an editor command: PlugInstall!
E492: Not an editor command: PlugClean
[✔] Now updating/installing plugins using vim-plug

Thanks for installing space-vim. Enjoy!
`
貌似是没有识别到 Vim-Plug 插件，找不到PlugInstall和PlugClean命令。手动安装Vim-Plug仍然不起作用。

**Comment by liuchengxu** [comment]
我使用的也是 iterm2,  `~/.vim/autoload/plug.vim` 存在吗？

**Comment by ThinkCats** [comment]
有的 ,路径也是对的

**Comment by liuchengxu** [comment]
那你现在打开 vim 是什么情况？

**Comment by ThinkCats** [comment]
`
Error detected while processing /Users/hehe/.vimrc:

line   15:
E492: Not an editor command: ^M
[``](`url`)
line   17:
E492: Not an editor command: ^M
line   19:
E492: Not an editor command: ^M
line   21:
E488: Trailing characters
line   24:
E488: Trailing characters
line   27:
E488: Trailing characters
line   31:
E492: Not an editor command: ^M
line   35:
E117: Unknown function: WINDOWS
E15: Invalid expression: WINDOWS()^M
line   65:
E171: Missing :endif
`

是这样的。

**Comment by liuchengxu** [comment]
只能建议确认 space-vim 与 vim-plug 都被正确下载到指定位置，你可以再次清除它们重新手动下载。

因为到目前为止还没有其他人报 issue, 我自己测试也没有什么问题，所以可能是你本地的原因。

**Comment by ThinkCats** [comment]
非常感谢回复支持，已确认是本地问题。git clone的代码可能是不完全的，从仓库下载zip包解压放到.space-vim下，使用install.sh脚本安装是ok的。😁 麻烦了
