### ISSUE TITLE
Error Occur When Install Vim Plugins

### ISSUE THREAD

**Issue by Metal-joker** [liuchengxu/space-vim#193]
#### Environment

- OS: Windows 10
- vim: vim 8.0
- neovim: neovim 0.1.13

#### Problem Description

This problem occured when I try to install space-vim

![image](https://user-images.githubusercontent.com/27676994/28753320-dfc9a4d4-7565-11e7-847a-96c0b9320b41.png)

here is my file tree

- vimfile
    - autoload
        - plug.vim
- .vimrc
- .spacevim

I must miss something, help me fix it.

Thanks

**Comment by liuchengxu** [comment]
Can you confirm that you have installed [vim-plug](https://github.com/junegunn/vim-plug#windows-powershell) successfully? The error message implys that vim-plug is broken.

**Comment by Metal-joker** [comment]
i just download the plug.vim into `~/vimfile/autoload/` as installation guide told me.

am i miss something?

**Comment by liuchengxu** [comment]
Is that a typo `vimfile`? It shoud be `vimfiles`.

**Comment by Metal-joker** [comment]
my bad, it's `~/vimfiles/autoload`. but still the same error.

**Comment by liuchengxu** [comment]
Well, what does `:scriptnames` say?

**Comment by Metal-joker** [comment]
sorry, my gmail inbox have some problems, i always can't receive your reply. :(

when i type `:scriptnames` it shows: 

```
  1: ~\.vimrc 
  2: ~\.space-vim\core\autoload\spacevim.vim
  3: ~\.space-vim\core\autoload\spacevim\info.vim
  4: ~\.spacevim
  5: C:\\Users\\hp/.space-vim/layers/+tools/fzf/packages.vim
  6: C:\\Users\\hp/.space-vim/layers/+completion/unite/packages.vim
  7: C:\\Users\\hp/.space-vim/layers/+distributions/better-defaults/packages.vim
  8: C:\\Users\\hp/.space-vim/layers/+misc/chinese/packages.vim
  9: C:\\Users\\hp/.space-vim/layers/+distributions/spacevim/packages.vim
 10: ~\.space-vim\core\autoload\spacevim\funcs.vim
 11: C:\\Users\\hp/.space-vim/layers/+tools/fzf/config.vim
 12: C:\\Users\\hp/.space-vim/layers/+completion/unite/config.vim
 13: C:\\Users\\hp/.space-vim/layers/+distributions/better-defaults/config.vim
 14: C:\\Users\\hp/.space-vim/layers/+distributions/better-defaults/keybindings.
vim
 15: C:\\Users\\hp/.space-vim/layers/+misc/chinese/config.vim
 16: D:\vim\vim80\delmenu.vim
 17: D:\vim\vim80\menu.vim
 18: D:\vim\vim80\lang\menu_zh_cn.cp936.vim
 19: D:\vim\vim80\lang\menu_chinese_gb.936.vim
 20: D:\vim\vim80\autoload\paste.vim
 21: C:\\Users\\hp/.space-vim/layers/+distributions/spacevim/config.vim
 22: D:\vim\vim80\plugin\getscriptPlugin.vim
 23: D:\vim\vim80\plugin\gzip.vim
 24: D:\vim\vim80\plugin\logiPat.vim
 25: D:\vim\vim80\plugin\manpager.vim
 26: D:\vim\vim80\plugin\matchparen.vim
 27: D:\vim\vim80\plugin\netrwPlugin.vim
 28: D:\vim\vim80\plugin\rrhelper.vim
 29: D:\vim\vim80\plugin\spellfile.vim
 30: D:\vim\vim80\plugin\tarPlugin.vim
 31: D:\vim\vim80\plugin\tohtml.vim
 32: D:\vim\vim80\plugin\vimballPlugin.vim
 33: D:\vim\vim80\plugin\zipPlugin.vim`
```
and type`:echo &rtp` it says:

```
C:\Users\hp/.vim,D:\vim/vimfiles,D:\vim\vim80,D:\vim/vimfiles/after,C:\Users\hp/
.vim/after,C:\Users\hp/.space-vim/core    
```

my vimfiles path is  `C:\user\hp\vimfiles`. looks like vim didn't loaded it.

**Comment by liuchengxu** [comment]
Yeah, your `runtimepath` is problematic. 

Have you installed vim-plug in `$HOME/.vim/autoload`? In order to make synchronization across windows and unix-like systems, I change the default installation location `~/vimfiles/autoload` from vim-plug to `~/.vim/autoload`, see [windows section, 3](https://github.com/liuchengxu/space-vim#windows):

```powershell
md ~\.vim\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\.vim\autoload\plug.vim"))
```

You seemingly installed vim-plug in `~/vimfiles/autoload` instead of `~/.vim/autoload`, in which case, vim can't find plug.vim.

Add `set runtimepath+=$HOME/vimfiles` at the beginning of `.spacevim`. See if it helps.

**Comment by Metal-joker** [comment]
i added `set runtimepath+=$HOME/vimfiles` to `.spacevim` and those error messge gone, but there's a new error...

![image](https://user-images.githubusercontent.com/27676994/28914357-f28aae1e-786d-11e7-92f5-7abd4b280797.png)

**Comment by liuchengxu** [comment]
It should be gone after you install the missing plugins. Run `:PlugInstall` and reopen vim, it should be ok.

**Comment by Metal-joker** [comment]
okay, seems its work! 

gvim looks well,

![image](https://user-images.githubusercontent.com/27676994/28918651-c4d4236a-787c-11e7-9939-806f3410de4d.png)

but vim in terminal is very strange

![image](https://user-images.githubusercontent.com/27676994/28918683-e861f442-787c-11e7-96d9-86af6eec2a0a.png)

can i fix it...
BTW, seems like you complete me isn't work

**Comment by liuchengxu** [comment]
Which type of terminal you're using? I haven't use windows for quite a while. Currently my daily use is macOS :).

YouCompleteMe is not an out-of-the-box plugin. You need to compile it at first. Actually I have also no experiences using YouCompleteMe in windows. You can refer to [here](https://www.zhihu.com/question/25437050) for more information. If you think YCM is too troublesome, [jedi-vim](https://github.com/davidhalter/jedi-vim) is an alternative for python.
