### ISSUE TITLE
Failed to open shell in vim!

### ISSUE THREAD

**Issue by amitbha** [liuchengxu/space-vim#195]
#### Environment

- OS: ubuntu gnome 17.04
- neovim: 0.1.7

#### Problem Description

With the default configuration, failed to open shell in nvim by pressing <SPC '>.
The error messages is "E492: Not an Editor command: shell"

**Comment by liuchengxu** [comment]
Thanks for the report. Fixed in https://github.com/liuchengxu/vim-better-default/commit/a5737b5e23e54e46597c23834f018676120984bf . Please update the plugin.

**Comment by amitbha** [comment]
没搞明白，这个插件 vim-better-default@a5737b5 和~/.space-vim/layers/+distributions/better-defaults/自带的这个配置有什么关系？
这个vim-better-default@a5737b5需要自己手动安装吗？

**Comment by liuchengxu** [comment]
这个插件默认已经安装了，`:PlugStatus` 可以查看已安装的插件状态。

<img width="801" alt="2017-08-04 12 30 38" src="https://user-images.githubusercontent.com/8850248/28954289-c032fd10-7910-11e7-93af-cfd133012df7.png">

[better-defaults](https://github.com/liuchengxu/space-vim/tree/master/layers/%2Bdistributions/better-defaults) 是 space-vim 中 Layer 的概念，一个 Layer 封装了针对一些方面的插件及其配置，在 `.spacevim`中启用 Layer，比如 `Layer 'better-defaults'`， 就会安装相关插件和配置。

[vim-better-default](https://github.com/liuchengxu/vim-better-default) 是一个 vim 的插件，可能名字上有些相似，但是与 better-defaults 是不同的概念。vim-better-default 是 space-vim 启用的一个 vim 插件而已。space-vim 使用 [vim-plug](https://github.com/junegunn/vim-plug) 作为插件管理器。
 
执行 `:PlugUpdate vim-better-default` 就可以更新 vim-better-default 了。或者简单点，，`:PlugUpdate` 更新全部插件。

**Comment by amitbha** [comment]
The vim command `:PlugUpdate` works. 
Thanks!

---
这有个[类似的项目](https://github.com/LER0ever/EverVim)，功能丰富，个人感觉界面更好看，对nvim支持非常好，但体积庞大（尤其是ycm插件），体系上没有space-vim清晰易用。也许可以参考借鉴 ;-)

**Comment by liuchengxu** [comment]
感谢推荐，我见过这个配置。在 space-vim 中启用 air-line 和 file-manager Layer 等，再安装 [vim-devicons](https://github.com/ryanoasis/vim-devicons)，安装字体，换个主题，看起来就跟你推荐的配置一样了。

之前有人提过 issue 建议添加 vim-devicons，但是由于需要额外安装 [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) 这样针对性的字体支持，而且可能会影响对 vim 的使用性能，所以并没有内置。如果你喜欢这种效果的话，可以自行安装字体和插件。

其实所有的 vim 配置都是大同小异，无非是对一些 vim 插件的组装。我希望在易用，实用和美观之间寻求折中。vim 的定制性很强，等你熟悉它以后，完全可以打磨出一个适合自己的配置 :).

**Comment by amitbha** [comment]
还有个同名的：[SpaceVim](https://github.com/SpaceVim/SpaceVim)，理念很相近，有些有趣的特性
其实我是键鼠流，偶尔用vim处理一下文件，没想着折腾这个
仅出于完美主义倾向，想好看好用点，嘿嘿

**Comment by liuchengxu** [comment]
关于 SpaceVim 这个项目，不想再置可否，项目本身没什么问题，但它的发起者人品有问题。这一点，搜索 space-vim 与 SpaceVim ，你会看到很多内容。

**Comment by fno2010** [comment]
@liuchengxu liuchengxu/vim-better-default@f9de3c3 (L246) crashes shell opening in neovim. Because `has('terminal')` returns 0 in neovim. Although it works well in vim 8. I guess your reason for this patch is just to be compatible with vim 8?

How about using the condition like `has('nvim') || has('terminal')` instead?

**Comment by liuchengxu** [comment]
@fno2010 Thanks for the pointer.  Welcome to open up a PR for this flaw, or I'll fix it myself soon.

**Comment by fno2010** [comment]
Sure. Move to liuchengxu/vim-better-default#16.
