### ISSUE TITLE
'pylint' error when using python-mode plugin

### ISSUE THREAD

**Issue by amitbha** [liuchengxu/space-vim#198]
#### Environment

- OS: ubuntu-gnome 17.10
- neovim: 0.2.0

#### Problem Description

Errors poped when saving python source file:
![222](https://user-images.githubusercontent.com/4060625/29299416-0a42cb68-81a1-11e7-92eb-2c677808c6d3.png)

Exec the ":pymodelint" command will cause the same error.

**Comment by liuchengxu** [comment]
Looks like similar to https://github.com/python-mode/python-mode/issues/783 . Can you check it out?

**Comment by amitbha** [comment]
That works. 
Modify the packages.vim in python layer:
`MP 'python-mode/python-mode', { 'branch': 'develop', 'for': 'python' }`
Then `:PlugUpdate` in vim.
Done!

**Comment by zhangweiii** [comment]
遇到同样的错误，`packages.vim`已经是正确的了，请问还可能是哪里我没弄好吗

```
MP 'jeetsukumaran/vim-pythonsense'
if g:spacevim.speed_up_via_timer
  MP 'python-mode/python-mode', { 'on': [] }
else
  MP 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
endif
```
