### ISSUE TITLE
always need build ycmd  when updating space-vim

### ISSUE THREAD

**Issue by macrosea** [liuchengxu/space-vim#20]
每次使用 vim +PlugInstall! +PlugUpdate +PlugClean +q 更新，都需要重新build ycmd 这个应该可以解决的。

**Comment by liuchengxu** [comment]
平时使用时没有必要这样执行这么一串进行更新,  按需要选择一个就行了. 

在 vim 中执行 `:PlugUpdate`  并不会导致 ycmd 的 rebuild.
