### ISSUE TITLE
æ key on norwegian keyboard layout not working correctly with spacevim

### ISSUE THREAD

**Issue by espenseventyr** [liuchengxu/space-vim#204]
#### Environment

- OS: ubuntu
- vim

#### Problem Description
WIth spacevim the æ key on a Norwegian keyboard jumps the cursor one word while in insert mode (like w in command-mode). With vanilla vim it inserts the character æ as it is supposed to.

How do I correct this behavior?

**Comment by liuchengxu** [comment]
Can you check `:verbose imap æ`?

**Comment by espenseventyr** [comment]
I got "Last set from ~/.vim/plugged/vim-rsi/plugin/rsi.vim."

**Comment by espenseventyr** [comment]
Commenting out "noremap!        <M-f> <S-Right>" made it work again. Thanks!
