### ISSUE TITLE
fatal:could not create leading directories of "xx\xx\plugged\xx",Invalid argument on windows gvim8

### ISSUE THREAD

**Issue by CuriousFu** [liuchengxu/space-vim#208]
#### Environment

- OS: windows 
- vim: vim8
- neovim: none

#### Problem Description

    fatal: could not create leading directories of '"E:\Vim__\.vim\plugged\vim-rsi"': Invalid argument

(http://ww1.sinaimg.cn/large/c5a702c3gy1fjssx098o1j20yg0jddhg.jpg)

**Comment by liuchengxu** [comment]
Does this issue occur when you run `:PlugUpdate` or when you install space-vim at the first time?

**Comment by CuriousFu** [comment]
Yes, i  use it on my windows platform, i just guess that it may be caused by the difference of the "\" on windows and "/" on unix, but i don't konw how the solve it.  @liuchengxu

**Comment by liuchengxu** [comment]
It works all right in my Win8 VM.

You mean this issue comes when you run `:PlugUpdate`? Previously, it works well?

**Comment by CuriousFu** [comment]
i  run it the first time . i just modified the default $HOME to my Vim folder (i.e. D:/Vim), the .vimrc (init.vim) and the .spacevim (spacevim.vim) are all sourced ok ,only the plugins can't be installed to the ".vim/plugged".

**Comment by liuchengxu** [comment]
Check `runtimepath` via `:for path in split(&rtp, ',') | echo path | endfor`.

**Comment by CuriousFu** [comment]
![](http://ww1.sinaimg.cn/large/c5a702c3gy1fjthdh5ck3j20qv0ebgm8.jpg)

**Comment by CuriousFu** [comment]
i've run the command ,the result is shown in the picture.:-)(http://ww1.sinaimg.cn/large/c5a702c3gy1fjthdh5ck3j20qv0ebgm8.jpg)

**Comment by liuchengxu** [comment]
Yeah, vim-plug works unexpectedly, so the plugins have not been cloned into `plugged` directory. 

Can you try the minimal vim-plug example? When you confirmed `plug.vim` is downloaded already in `~/.vim/autoload/plug.vim`, replace `.vimrc` with the following content and run `:PlugInstall`:

```vim
set rtp+=$HOME/.vim
call plug#begin()
Plug 'tpope/vim-sensible'
call plug#end()
```

**Comment by CuriousFu** [comment]
it is still the same issue.
http://ww1.sinaimg.cn/large/c5a702c3gy1fjti52dqk5j20u406g3yd.jpg

**Comment by liuchengxu** [comment]
Then I suggest reporting it to vim-plug :).

**Comment by CuriousFu** [comment]
i already put the plug.vim to the ~/.vim/autoload .i will try to download the plug.vim later to  replace my orginal one.Thank you so much for sparing your precious time helping me  questions.  Thank you :smile:

**Comment by CuriousFu** [comment]
@liuchengxu , i try reinstall the plug.vim to replace the orginal one , and the error disappeared and the space-vim works well on win .

**Comment by liuchengxu** [comment]
@CuriousFu Glad to hear you figure it out.
