### ISSUE TITLE
How to config how many spaces it uses when doing auto indent?

### ISSUE THREAD

**Issue by andyhu** [liuchengxu/space-vim#211]
Thanks for your hard work on this project.
I was looking for a way to config the number of spaces of auto-indent in javascript but with no luck. Would appreciate it if someone can shed some light on this. Thanks!

**Comment by liuchengxu** [comment]
Have you enabled `javascript` layer?  [Here](https://github.com/liuchengxu/space-vim/blob/master/core/ftplugin/javascript.vim) is the default setting of javascript in space-vim.

If you want to override the default ones, use `autocmd FileType javascript setl tabstop=2 softtabstop=2 shiftwidth=2` with the number changed.
