### ISSUE TITLE
Can't override the default settings by UserConfig()

### ISSUE THREAD

**Issue by zydou** [liuchengxu/space-vim#212]
#### Environment

- OS: Ubuntu14.04 (x64)
- vim: 8.0
- neovim: no

#### Problem Description
Can't override the default settings about auto line wrapping in python.
vim automatically insert a newline when I editing a long line (more than 79 characters), which is what I don't like.
Opening vim and running `:set textwidth=0` will stop auto line wrapping. But adding `set textwidth=0` to `UserConfig()` does not.

Details:
1. Add `set textwidth=0` to `UserConfig()`
2. Open vim
3. Run `:verbose set textwidth`

Results:
```
textwidth=79
    Last set from ~/.space-vim/core/ftplugin/python.vim
```
It seems that this setting below can't be override by `UserConfig()`?
https://github.com/liuchengxu/space-vim/blob/e2c7f6953e2eeaf3a4cadcfd74f3c8a677d01959/core/ftplugin/python.vim#L1

Chinese Version:
vim 在编辑超过79字符的行时将自动插入一行, 这是我不想要的.
如果在vim里运行 `:set textwidth=0` 就可以将自动换行功能关闭, 但是将 `set textwidth=0` 加入到 `UserConfig()` 却不起作用.
详细如下:
1. 将 `set textwidth=0` 加入到 `UserConfig()` 里
2. 打开vim
3. 运行 `:verbose set textwidth`

结果显示:
```
textwidth=79
    Last set from ~/.space-vim/core/ftplugin/python.vim
```
似乎下面这个文件里的设置优先级更高?
https://github.com/liuchengxu/space-vim/blob/e2c7f6953e2eeaf3a4cadcfd74f3c8a677d01959/core/ftplugin/python.vim#L1

**Comment by liuchengxu** [comment]
使用 `autocmd`:

```vim
autocmd FileType python setlocal textwidth=0
```

**Comment by zydou** [comment]
@liuchengxu Thanks very much!
Auto line wrapping is disabled after adding  `autocmd FileType python setlocal textwidth=0` to `UserConfig()`
