### ISSUE TITLE
E887: Sorry, this command is disabled, the Python's site module  could not be loaded.

### ISSUE THREAD

**Issue by programes** [liuchengxu/space-vim#214]
#### Environment

- OS: win10 64 bit
- vim: 8.1181
- neovim: ???

#### Problem Description
处理 function spacevim#begin[16]..<SNR>2_cache[6]..spacevim#cach
e#init[3]..<SNR>3_py_init 时发生错误:

第   41 行:

E887: Sorry, this command is disabled, the Python's site module 
could not be loaded.

处理 function spacevim#end[1]..<SNR>2_register_plugin[8]..<SNR>2
_packages[6]..spacevim#cache#init[3]..<SNR>3_py_init 时发生错误:

第   41 行:

E887: Sorry, this command is disabled, the Python's site module 
could not be loaded.

**Comment by liuchengxu** [comment]
Looks like similar to #23. You can try reinstalling Vim.

**Comment by liuchengxu** [comment]
Should be fixed now. Space-vim will use the vimscript function when python functionailty fails.

**Comment by programes** [comment]
Thanks，Solved my problem。
