### ISSUE TITLE
mapleader does not work

### ISSUE THREAD

**Issue by onerciller** [liuchengxu/space-vim#215]
#### Environment

- vim: 8.0

#### Problem Description
mapleader does not work i want to make comma to mapleader however i could not work it 
i defined them in userconfig func in following 
```vim
   let g:spacevim_leader = "<\Space>"
   let g:spacevim_localleader = ','
```

**Comment by liuchengxu** [comment]
The leader key is space and the local leader key is comma by default. If you want to change the leader to comma, define it in `UserInit()`:

```vim
function! UserInit()
    let g:spacevim_leader = ","
endfunction
```

**Comment by onerciller** [comment]
tjanks @liuchengxu  i solved it
