### ISSUE TITLE
E492:不是编辑器命令：Gundotoggle

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#216]
#### Environment

- OS: arch linux 
- vim: 8.0
- neovim: ???

#### Problem Description
Plug 'sjl/gundo.vim'  后打开只能在安装成功后的刚开始偶然使用成功，之后一直报错“”E492:不是编辑器命令：GundoToggle“，也删除过plug下的插件重装，还是没成功

**Comment by liuchengxu** [comment]
应该是 `GundoToggle`，而不是 `Gundotoggle`?

**Comment by pittcat** [comment]
这里打错了

**Comment by pittcat** [comment]
安装undotree也是一样的效果，没成功，还重装了一遍space-vim

**Comment by liuchengxu** [comment]
1. 测试手动下载是否正常。将 `Plug 'sjl/gundo.vim'` 加入到 `UserInit()` 以后，进入 `~/.vim/plugged` 目录，手动下载 gundo.vim `git clone https://github.com/sjl/gundo.vim.git` ，然后打开 Vim ，看一下 `:GundoToggle` 是否正常。

2. 通过 vim-plug 再多安装几个插件，看一下是否正常。

**Comment by pittcat** [comment]
我误解了，我把它加到了userconfig里面。问下userinit和userconfig有什么大的区别？在加载个性化配置的时候一般怎么放？

**Comment by liuchengxu** [comment]
`UserInit()` 放置要加载的插件信息，比如这里的 `Plug 'sjl/gundo.vim'`，`UserInit()` 实际上作用在 `plug#begin()` 与 `plug#end()` 之间，属于插件系统的初始化过程，详细内容也可以查看 vim-plug 的 README。`Layer()` 本质上也只不过是为了执行 `Plug 'sjl/gundo.vim'` 这样的信息，多了一层封装而已。

`UserConfig()` 作用在 `plug#end()` 之后，里面放置相关配置信息，可以覆盖已有设置，比如取消相对行号:

```vim
function! UserConfig()
  set norelativenumber
endfunction
```

或是添加新的插件设置, 比如启用 powerline font:

```vim
function! UserConfig()
  let g:airline_powerline_fonts=1
endfunction
```

**Comment by pittcat** [comment]
哦哦，谢谢师傅
