### ISSUE TITLE
'code-snippets' 与'ycmd'有冲突

### ISSUE THREAD

**Issue by yusihai719** [liuchengxu/space-vim#217]
#### Environment

- OS: ubuntu17.10
- vim: 8.0
- neovim: ???

#### Problem Description

同时启用snippets 与 ycmd layer 时 有冲突
表现在输入代码时有提示，就不能继续输入字母，而是把你输入的字母全部清除，关闭snippets 层就正常，

**Comment by yusihai719** [comment]
同时启用snippets 与 ycmd layer 时 有冲突
表现在输入代码时有提示，就不能继续输入字母，而是把你输入的字母全部清除，关闭snippets 层就正常，

**Comment by liuchengxu** [comment]
对于 Vim8 和 NeoVim，现在可以直接用 `auto-completion` 替代 `ycmd`，我已经很久没有用 `ycmd` 了，有机会再看吧:)

**Comment by qwIvan** [comment]
Vim8用auto-completion，怎么实现文件间跳转呢？例如Python import进来的东西，怎么调到定义处呢？
