### ISSUE TITLE
can't use auto-completion correctly

### ISSUE THREAD

**Issue by nemoelit** [liuchengxu/space-vim#220]
#### Environment

- OS: macOS High Sierra 10.13
- vim: Vi IMproved 8.0 (2016 Sep 12, compiled Oct 20 2017 22:07:02)
- neovim: ???

#### Problem Description

I want to use the layer auto-completion, so I add ` Layer 'auto-completion' ` in the .spacevim.

<img width="837" alt="screen shot 2017-10-21 at 14 29 44" src="https://user-images.githubusercontent.com/25201484/31848867-8c836588-b66c-11e7-9bf6-3cea2bc30246.png">

But it seems that something goes wrong. Here is the error messages.

Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    1:
NameError: name 'completor_api' is not defined
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    2:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    2:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    2:
NameError: name 'res' is not defined
Press ENTER or type command to continue
Error detected while processing function <SNR>62_complete[1]..completor#do[7]..completor#utils#
get_completer:
line    2:
E858: Eval did not return a valid python object
Press ENTER or type command to continue

<img width="955" alt="screen shot 2017-10-21 at 14 28 03" src="https://user-images.githubusercontent.com/25201484/31848848-1fccd230-b66c-11e7-8e07-294c4d2db5be.png">

**Comment by liuchengxu** [comment]
Seemingly [completor.vim](https://github.com/maralla/completor.vim) is broken. What does `:version say`?

**Comment by nemoelit** [comment]
<img width="960" alt="screen shot 2017-10-21 at 15 33 04" src="https://user-images.githubusercontent.com/25201484/31849477-32a401e0-b675-11e7-8c42-32af21b63f65.png">

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 20 2017 22:07:02)
MacOS X (unix) version
Included patches: 1-1207
Compiled by elit@promote.cache-dns.local
Huge version without GUI.  Features included (+) or not (-):
+acl             -ebcdic          +listcmds        +persistent_undo +termresponse
+arabic          +emacs_tags      +localmap        +postscript      +textobjects
+autocmd         +eval            -lua             +printer         +timers
-balloon_eval    +ex_extra        +menu            +profile         +title
-browse          +extra_search    +mksession       +python          -toolbar
++builtin_terms  +farsi           +modify_fname    -python3         +user_commands
+byte_offset     +file_in_path    +mouse           +quickfix        +vertsplit
+channel         +find_in_path    -mouseshape      +reltime         +virtualedit
+cindent         +float           +mouse_dec       +rightleft       +visual
-clientserver    +folding         -mouse_gpm       -ruby            +visualextra
+clipboard       -footer          -mouse_jsbterm   +scrollbind      +viminfo
+cmdline_compl   +fork()          +mouse_netterm   +signs           +vreplace
+cmdline_hist    -gettext         +mouse_sgr       +smartindent     +wildignore
+cmdline_info    -hangul_input    -mouse_sysmouse  +startuptime     +wildmenu
+comments        +iconv           +mouse_urxvt     +statusline      +windows
+conceal         +insert_expand   +mouse_xterm     -sun_workshop    +writebackup
+cryptv          +job             +multi_byte      +syntax          -X11
-cscope          +jumplist        +multi_lang      +tag_binary      -xfontset
+cursorbind      +keymap          -mzscheme        +tag_old_static  -xim
+cursorshape     +lambda          +netbeans_intg   -tag_any_white   -xpm
+dialog_con      +langmap         +num64           -tcl             -xsmp
+diff            +libcall         +packages        +termguicolors   -xterm_clipboard
+digraphs        +linebreak       +path_extra      +terminal        -xterm_save
-dnd             +lispindent      -perl            +terminfo
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_F
ORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa    -F/Sys
tem/Library/Frameworks -framework Python

**Comment by liuchengxu** [comment]
Can you try running `:python 'from completor import api as completor_api'`?

**Comment by nemoelit** [comment]
<img width="957" alt="screen shot 2017-10-21 at 16 00 30" src="https://user-images.githubusercontent.com/25201484/31849688-048b401c-b679-11e7-82ea-a759387a8520.png">

no responding

**Comment by liuchengxu** [comment]
From the error message, the cause is that `completor_api`, i.e, `api`, wasn't defined, but it's ok to import `api` from `completor`. I'll report it the upstream.  For now, I suggest using other alternative:

- [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)
- [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager)

However, NCM needs `+python3` feature and you only have `+python`. So, you can try asyncomplete.vim:

```vim
function! UserInit()
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-buffer.vim'
endfunction

function! UserConfig()
  " Use tab completion
  inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
endfunction
```

**Comment by nemoelit** [comment]
<img width="830" alt="screen shot 2017-10-21 at 16 29 13" src="https://user-images.githubusercontent.com/25201484/31849917-0aa72368-b67d-11e7-9b12-ea68c40e6025.png">
<img width="458" alt="screen shot 2017-10-21 at 16 25 11" src="https://user-images.githubusercontent.com/25201484/31849924-0ee2f664-b67d-11e7-8b86-85ea1e2226b3.png">

It seems that I still can't use the completion. What's wrong?

**Comment by liuchengxu** [comment]
asyncomplete.vim is implemented using VimScript. Although it's asynchronous, you may need to wait a few seconds to see the effect. After that, it should be able to respond quickly when you type.

![image](https://user-images.githubusercontent.com/8850248/31850171-9078e9e6-b613-11e7-9326-efa6d5858124.png)

**Comment by nemoelit** [comment]
At last, I chose to reinstall vim. Here is my solution. 

`brew install vim --with-python3`

add `Layer 'ycmd'` in `.spacevim`
```
cd ~/.vim/plugged/YouCompleteMe
git submodule update --init --recursive
brew install cmake
python3 install.py --clang-completer
```
It works. Cheers. Just close this issue. Thanks.

**Comment by maralla** [comment]
I think you should use the following code to test whether completor.vim is installed properly:
```vim
:python from completor import api as completor_api
```
**You should not add `'`.**

**Comment by maralla** [comment]
And I installed space-vim in a fresh environment with the layer `auto-completion` added, the completion worked very well.

**Comment by liuchengxu** [comment]
@maralla , thanks for your response. completor.vim also works well in my case, so this issue may just related to the local environment.

**Comment by sinchb** [comment]
same problem, whatever I typed in vim, it display this:
![image](https://user-images.githubusercontent.com/1590268/38769605-189ecac6-4038-11e8-9bf0-f7ef67e1aa0c.png)


system: osx 10.13.3

**Comment by DTech-Diabetes** [comment]
@sinchb were you able to fix this issue? I'm experiencing the same thing.

**Comment by kabobbob** [comment]
@sinchb were you able to fix this issue? I'm seeing the same thing.

**Comment by baasman** [comment]
I'm seeing this as well.
