### ISSUE TITLE
如何卸载插件

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#228]
#### Environment

- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

#### Problem Description

如何卸载插件，把rename.vim 换成了tpope/vim-eunuch但是以前的rename.vim 还没有卸载

**Comment by liuchengxu** [comment]
使用 `exclude`:

```vim
function! Layers()
    Layer 'file-manager',  { 'exclude': 'danro/rename.vim' }
endfunction
```
