### ISSUE TITLE
mac 系统 vim 7.4 下正确，升级vim 8 后报错。

### ISSUE THREAD

**Issue by quakex** [liuchengxu/space-vim#23]
uninstall，重新安装，依旧报错。盼解决。

==> Trying to update space-vim
From https://github.com/liuchengxu/space-vim
 * branch            master     -> FETCH_HEAD
Already up-to-date.
[✔] Successfully updated space-vim
[✔] Setting up vim symlinks.
Error detected while processing function <SNR>2_collect_topics:
line   19:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Error detected while processing function LayersEnd[20]..<SNR>2_load_layer_packages[2]..<SNR>2_cur_layer_base_dir:
line    3:
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * fzf * is invalid, please check it.
[space-vim] 0fzf/packages.vim does not exist, which may cause unexpected errors.
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * unite * is invalid, please check it.
[space-vim] 0unite/packages.vim does not exist, which may cause unexpected errors.
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * better-defaults * is invalid, please check it.
[space-vim] 0better-defaults/packages.vim does not exist, which may cause unexpected errors.
Error detected while processing function LayersEnd[30]..<SNR>2_load_layer_config[2]..<SNR>2_cur_layer_base_dir:
line    3:
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * fzf * is invalid, please check it.
[space-vim] 0fzf/config.vim does not exist, which may cause unexpected errors.
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * unite * is invalid, please check it.
[space-vim] 0unite/config.vim does not exist, which may cause unexpected errors.
E121: Undefined variable: s:topic2layers
E116: Invalid arguments for function items(s:topic2layers)
E15: Invalid expression: items(s:topic2layers)
[space-vim] Layer * better-defaults * is invalid, please check it.
[space-vim] 0better-defaults/config.vim does not exist, which may cause unexpected errors.
Press ENTER or type command to continue
[✔] Now updating/installing plugins using vim-plug

Thanks for installing space-vim. Enjoy!

**Comment by liuchengxu** [comment]
看起来像是 vim 的 python 调用出错了, 能把你的 vim  信息贴一下吗？`vim --version | grep python`

**Comment by quakex** [comment]
重新安装vim后解决，而且要从源码编译，直接 brew reinstall vim 都不行。折腾啊，space-vim 非常好，非常感谢

**Comment by liuchengxu** [comment]
🎉
