### ISSUE TITLE
How to use auto completion function 

### ISSUE THREAD

**Issue by backyes** [liuchengxu/space-vim#233]
Thanks for this good repo to make vim easier and perfect, and I would like to try it, but I can not go completely. 

We try set ~/.spacevim 

```
" Let Vim and NeoVim shares the same plugin directory.
" Comment it out if you don't like
let g:spacevim_plug_home = '~/.vim/plugged'

" Enable the existing layers in space-vim
function! Layers()

  " Default layers
  Layer 'fzf'
  Layer 'unite'
  Layer 'better-defaults'

  Layer 'c-c++'
  Layer 'python'
  Layer 'java'
  Layer 'go'
  Layer 'scala'
  Layer 'clojure'
  Layer 'markdown'
  Layer 'graphviz'

  Layer 'chinese'

  Layer 'text-align'
  Layer 'programming'

  Layer 'ycmd'
  Layer 'auto-completion'
  Layer 'syntax-checking'

endfunction

" Add your own plugins
function! UserInit()

  " The default leader key is space key.
  " Uncomment the line below and modify "<\Space>" if you prefer another
  " let g:spacevim_leader = "<\Space>"

  " The default local leader key is comma.
  " Uncomment the line below and modify ',' if you prefer another
  " let g:spacevim_localleader = ','

  " Install personal plugins

endfunction

" Override the default settings as well as adding extras
function! UserConfig()

  " If you have installed the powerline fonts and want to enable airline layer
  " let g:airline_powerline_fonts=1

  " Use gui colors in terminal if available
  if has('termguicolors')
    set termguicolors
    if g:spacevim_tmux
      " If use vim inside tmux, see https://github.com/vim/vim/issues/993
      " set Vim-specific sequences for RGB colors
      let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
      let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    endif
  endif

endfunction
```

then, open vim,  install layers completely. 

But the autocompletion function does not work when I open 'vim' with an java or shell files. 

Maybe I miss some steps... Could you give us some detailed guideline ?

**Comment by liuchengxu** [comment]
Well, what's your vim version? If you are using Vim8 or NeoVim, then `auto-completion` is enough. `ycmd` is a heavy auto-completion option, you need to compile first to get it work.

**Comment by backyes** [comment]
Thanks . I recompile vim with lua support, then completion works well. 

You suggestion give more information on it , well thanks. I will fix it.

**Comment by backyes** [comment]
And I think, if the docker images for releasing fully available space-vim could be preferred options to easier use this tool, since more implicit options should be obeyed  to achieve this tool deployed well.

**Comment by liuchengxu** [comment]
Thanks for your suggestion. Can you elaborate? You mean a docker image with a complied Vim and ready-to-use space-vim? In essential, space-vim is nothing but a *.vimrc* or *init.vim*. It's merely a configuration engineering.
