### ISSUE TITLE
What does Spacevim use for the keybinding discovery

### ISSUE THREAD

**Issue by njunxuan** [liuchengxu/space-vim#235]
Hi this space vim effort is really amazing. However, I think it is too much for me to swap over from my own config. I was very interested in how the "keybindings" map was created and where should I look if I want to incorporate it in my own setup.

Thank you.

**Comment by liuchengxu** [comment]
Most mappings are defined in [default.vim](https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim), they are merely basic configuration for vim and very easy to incorporate into your own setup.

**Comment by njunxuan** [comment]
I am sorry I think I was not very clear. I meant the feature that after pressing the leader key, the "guide" will appear showing all the keybindings.

**Comment by liuchengxu** [comment]
Well, for the time being, [vim-leader-guide](https://github.com/hecal3/vim-leader-guide/) is the best option. You can also take a look at [quickmenu.vim](https://github.com/skywind3000/quickmenu.vim) , which brings some hints for complex operations.

**Comment by njunxuan** [comment]
I see. thank you very much!
