### ISSUE TITLE
快速运行代码F5的时候，调用的是python2.7的

### ISSUE THREAD

**Issue by startybai** [liuchengxu/space-vim#236]
#### Environment

- OS:
    - [√ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [√ ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description

sorry ,my englishi is very bad ,so i usr chinese,快速运行代码按F5的时候，用的是ubuntu系统，执行的时候用的是python2.7的解析器，有办法更改吗，

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/dcbb319ac41bba72a6cef85e42cee9b7a0c236ad/core/autoload/spacevim/util.vim#L57

默认是调用当前系统默认的 Python，你可以把 `"time python %"` 里面的 `python` 指向你想要的版本。

**Comment by startybai** [comment]
升级了spacevim,就报错了
![image](https://user-images.githubusercontent.com/31914699/33106552-95c690d8-cf6d-11e7-9a60-e9bcaae60e0e.png)，
更改了python3也没生效
![image](https://user-images.githubusercontent.com/31914699/33106585-ce9b5a42-cf6d-11e7-8abd-d9871c1896b4.png)

**Comment by liuchengxu** [comment]
那个错误是不是你写错字了？`chinese`，不是 `chinesse`。

改了以后，重新打开 vim 应该就可以了。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33109625-aa9b75e0-cf7d-11e7-825b-5d8f9d65a166.png)
 已经改了，但不生效，可以方便加我QQ：3759393交谈下吗，或者有QQ群可以谈论的地方？

**Comment by liuchengxu** [comment]
你可以直接测试：`:!python3 %` 或者 `:AsyncRun! python3 %`，如果执行成功，再映射一个快捷键就行了。

```vim
nnoremap <F5> :!time python3 %<CR>
```

我不认为 QQ 群是一个好的方式。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33111477-50bcf45c-cf89-11e7-898c-4abe11f1c741.png)
我把里面的这个F5注释掉就可以了，不知道是什么原因，还有就是我要调用历史命令（即按q: ），可以显示，但是用不了，不知道是不是冲突了

**Comment by liuchengxu** [comment]
那么这样覆盖应该就可以了：

```vim
autocmd python nnoremap <F5> :!time python3 %<CR>
```

这应该会覆盖 `core/ftplugin/python.vim` 的 F5 快捷键。你可以先这么暂时用一下，晚点我应该可以加个选项进行设置。

**Comment by liuchengxu** [comment]
在 `UserConfig()` 中加入：

```vim
let g:spacevim_python_run = 'python3'
```

这样，应该就是用的 `python3` 了，也可以用 `/usr/local/bin/python3`。
