### ISSUE TITLE
代码中文，快速执行报错

### ISSUE THREAD

**Issue by startybai** [liuchengxu/space-vim#238]
使用python3 ，代码里面有中文，快速执行命令会报错，有 办法解决吗
UnicodeEncodeError: 'ascii' codec can't encode character '\u60a8' in position 0: ordinal not in range(128)

![image](https://user-images.githubusercontent.com/31914699/33155925-a026640a-d02f-11e7-8c74-9430fbf094ae.png)

**Comment by liuchengxu** [comment]
<img width="639" alt="2017-11-23 9 34 00" src="https://user-images.githubusercontent.com/8850248/33156113-7f525e3a-d031-11e7-8e76-101696bd3913.png">

我想这与 vim 的配置无关，你应该 Google 这个错误：

- https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20/19727991

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33158579-1a97da64-d046-11e7-8fb3-1be10eafbcc4.png)





,检测代码，就直接显示错误

**Comment by liuchengxu** [comment]
使用 `vim -u NONE 7.py` 不加载 vimrc 打开 7.py，在里面执行 `:!python3 %` 看是否正常。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33161599-7b20807a-d05f-11e7-9fca-727146456233.png)
这样操作是正常的

**Comment by liuchengxu** [comment]
space-vim 在 AsyncRun 的情况下，F5 执行的是 `:AsyncRun python %`，没有 AsyncRun 的话，执行的是 `:!python %`。你看直接执行 `:AsyncRun python %` 是不是正常。

**Comment by startybai** [comment]
什么反应也没有
![image](https://user-images.githubusercontent.com/31914699/33161988-fe7c7030-d061-11e7-8fe1-fe9923e3b2ce.png)

**Comment by liuchengxu** [comment]
额，不要用有交互的，有交互的 AsyncRun 不支持，直接测试一下 `print('我')` 是不是正常就行了。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33162394-517eaabc-d064-11e7-8068-908fb72b68f4.png)
还是没反应，能远程协助下吗

**Comment by liuchengxu** [comment]
- 把光标放到第一行，看一下显示的具体信息。
- 执行 `:AsyncRun python %` 看一下结果。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33162645-95cb9e18-d065-11e7-8238-f7bb02ea3fdd.png)
执行 :AsyncRun python %，没反应，返回到正常模式

**Comment by liuchengxu** [comment]
- `:version`，vim 的版本信息。
- `:ALEDetail` 看一下 ale 的提示信息。
- 执行 `:AsyncRun python %` 以后，执行 `:PlugStatus`。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33163025-59ff4f04-d067-11e7-956e-98a180519606.png)
![image](https://user-images.githubusercontent.com/31914699/33163055-7b7eae90-d067-11e7-8c81-f70c0a9c03e2.png)
![image](https://user-images.githubusercontent.com/31914699/33163076-96e9b134-d067-11e7-8466-4d837f4feb1e.png)

**Comment by liuchengxu** [comment]
你可以试一下 `AsyncRun` 执行其他文件是否正常，比如写一个 cpp 文件：

```cpp
#include <iostream>
using namespace std;

int main()
{
  cout<<"hello"<<endl;
  return 0;
}
```

看一下 F5 是否正常，问题是不是只出现在 Python 文件。

**Comment by startybai** [comment]
我的好像不支持cpp，按了F5没反应。可否方便远程帮忙看下，感激不尽

**Comment by liuchengxu** [comment]
这种问题还是需要自己解决，这个过程每个人都会经历的。

怎么会不支持 cpp? 如果没有 `g++`，装一个就好了。

**Comment by startybai** [comment]
是的，我按F5没效果
但是执行AsyncRun g++ -std=c++11 % -o %<; time ./%< ,同级目录就生成了一个可执行文件

**Comment by liuchengxu** [comment]
试着打开 quickfix 窗口， `:copen`，按道理执行 AsyncRun 时，是会自动打开的，不过还是看一下。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33164939-eb01619c-d06f-11e7-84bc-f47d5034c670.png)
已经出来了，但是报错

**Comment by liuchengxu** [comment]
这里的 quickfix 显示的是你之前有交互文件的信息，AsyncRun 不支持交互，你再执行一次试一下，看quickfix 里面输出的是不是`我`。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33165350-759bb9be-d071-11e7-9cd1-702f81dfcd2d.png)
这是我刚新建的，还是一样，我感觉是哪里配置有问题了，vim -u NONE没问题的

**Comment by startybai** [comment]
我知道原因了，我自己在.spavevim配置了一大堆，用默认的就没有问题了

**Comment by liuchengxu** [comment]
无法复现你的问题，在我这里都是正常的，你可以尝试重装 space-vim。

**Comment by liuchengxu** [comment]
对了，你有没有启用 `programming` layer? quickfix 在 AsyncRun 时自动打开的设置放在里面。

**Comment by startybai** [comment]
![image](https://user-images.githubusercontent.com/31914699/33191541-3071a356-d0f5-11e7-8fc0-9119fcc2b7e7.png)
代码检测机制好像是针对pythone3后面的版本，只能是英文

**Comment by liuchengxu** [comment]
我刚刚更新了一下，即使不启用 `programming` layer，Python 文件快速执行时，`AsyncRun` 可用，也会自动打开 quickfix。

至于其他编程问题，还是需要你自己研究。

**Comment by startybai** [comment]
发现了一个问题，使用vim -u NONE 7.py 打开文件，使用:python2 % 执行是会报错，但直接vim打开执行：python2是正常的，正常python2是默认ASCII无法编码中文的，所有肯定有配置文件强制让python2的默认编码改为了utf8，反而python3默认是uft8，正常用vim -u NONE 7.py是没问题的，用vim执行出错了，能否看哪个配置文件有让python2使用uft8编码的

**Comment by liuchengxu** [comment]
`:verbose set encoding`，不会出现对换编码的情况，因为设置的都是 utf-8。

**Comment by startybai** [comment]
很奇怪的一个问题，用vim 进去执行:echo has('python3')，竟然是为0 ，用vim -u NOEE 进去是为1

**Comment by liuchengxu** [comment]
那 `:version` 一样吗？

**Comment by startybai** [comment]
一样的，命令行的vim --version 和 vim 进去的version 还有vim -u NONE进去的version是一样的

**Comment by liuchengxu** [comment]
不清楚，没遇过。

**Comment by startybai** [comment]
如果你有时间，可以装个ubuntu17的 ，测试一下哈，今天刚测试的全新ubuntu17的，echo has('python3')是正常的，应该是space-vim配置触发导致中文运行不了的

**Comment by startybai** [comment]
终于找到原因，真不容易，加载layer fzf 就会出现这个问题，没有加载就正常了

**Comment by liuchengxu** [comment]
这句话没什么重要的，判断是不是使用 GUI vim, 同时有没有 `terminal` 特性。如果是跟 fzf 有关，我觉得真正的原因可能在这里：

https://github.com/liuchengxu/space-vim/blob/48a21cd5998f18f4fbe0efc479c99c448819a2ab/layers/%2Btools/fzf/config.vim#L11

你把这一行注释掉试一下，这里之前就出现过问题，然后才加的这个设置。

**Comment by startybai** [comment]
刚测试了下，可以的，周一我在公司电脑在测试下，谢谢啦

**Comment by liuchengxu** [comment]
如果确认是 `$LANG` 的问题，就先关闭了:).
