### ISSUE TITLE
Library not loaded: /usr/local/opt/perl/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE/libperl.dylib

### ISSUE THREAD

**Issue by yiailake** [liuchengxu/space-vim#240]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [ ] NeoVim

```

```

#### Problem Description

<img width="549" alt="qq20171124-161442 2x" src="https://user-images.githubusercontent.com/5363570/33201334-027b79f2-d133-11e7-8261-e00bcf3bba46.png">
<img width="791" alt="qq20171124-161431 2x" src="https://user-images.githubusercontent.com/5363570/33201337-08955eca-d133-11e7-9eb8-6548465da58f.png">

Library not loaded: /usr/local/opt/perl/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE/libperl.dylib

**Comment by liuchengxu** [comment]
See if this helps: https://github.com/Homebrew/brew/issues/2356 .

**Comment by yiailake** [comment]
It works for me. Thank you!

**Comment by ashwinvidiyala** [comment]
Worked for me too. Specifically [this](https://github.com/Homebrew/brew/issues/2356#issuecomment-301830565). Thank you @liuchengxu !
