### ISSUE TITLE
spacevim使用历史命令 q: 查看，无法enter确定命令

### ISSUE THREAD

**Issue by startybai** [liuchengxu/space-vim#244]
![image](https://user-images.githubusercontent.com/31914699/33534991-e7764794-d8e5-11e7-9229-8a0e5340bdec.png)
当要使用历史操作命令时，快捷键q: 查看之后，按enter键无效

**Comment by liuchengxu** [comment]
在 `UserConfig()` 中添加 `unmap <CR>` 就可以了，因为默认 enter 被重映射为 `:`。
