### ISSUE TITLE
ctags / cscope 插件支持， 选中即复制支持

### ISSUE THREAD

**Issue by backyes** [liuchengxu/space-vim#246]
RT几个特性，一致以来是比较不错的阅读代码助手，切换到spacevim后，发现相关工具不是很好的支持，能否给些guide能方便快速的使用上上面的几个插件。

如果有一些文档或者简介，介绍如何自己扩展这些插件到space-vim中，非常感谢。

**Comment by liuchengxu** [comment]
1. 可以先把 space-vim 默认没有的插件，即用户的自定义插件放在 `UserInit()`，使用方法与正常的 vim-plug 无异，比如：

   ```vim
   function! UserInit()
     Plug 'jsfaint/gen_tags.vim'
   endfunction
   ```

2. 如果需要进行配置，在 `UserConfig()` 中进行，配置方式与正常的 vimrc 无异。之所以放在 `UserConfig()` 里面，是为了最后加载用户的自定义设置。比如：

   ```vim
   function! UserConfig()
      let g:gen_tags#blacklist = ['$HOME']
   endfunction
   ```

---------


如果希望将它们包装为一个 *layer* 集成到 space-vim 里面，可以参考现有的 *layer* 结构。比如放在 `+programming` topic 下面，那么在 `layers/+programming` 目录下面新建一个子目录，比如 `cscope`，并在 `cscope` 里面新增 3 个文件：

- packages.vim: `UserInit()`  使用的插件使用 `MP` 替换 `Plug` 进行加载。
- config.vim: `UserConfig()` 里面的配置直接放到 config.vim 里面。
- README.md: 一个简单介绍。

然后就可以通过 `Layers()` 进行加载了：

```vim
function! Layers()
  Layer 'cscope'
endfunction
```

**Comment by backyes** [comment]
Wow, thanks for quick response, I will have a try soon.
