### ISSUE TITLE
How space-vim implemented jk cross-line feature?

### ISSUE THREAD

**Issue by ztlevi** [liuchengxu/space-vim#247]
It's a very basic feature I'm using in space-vim. When the cursor reaches the end or start of the line, it should go next line or previous line if you keep pressing j or k.

I search across this repo but cannot find any clues.

Does anyone know how to set this in a pure vim?

**Comment by liuchengxu** [comment]
Most of the basic settings are defined in a tiny vim plugin [vim-better-default](https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim). In terms of your question, I think you can find some useful information via `:verbose map j`.

**Comment by ztlevi** [comment]
Thanks!

I found 
```
" Allow backspace and cursor keys to cross line boundaries
set whichwrap+=<,>,h,l
```
It works for me. But I have to say github's native project search really sucks... I did search for `cross line`. But nothing found.
