### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by JesusZhao** [liuchengxu/space-vim#248]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description

How to uninstall?

**Comment by liuchengxu** [comment]
`make uninstall` or `bash uninstall.sh`.
