### ISSUE TITLE
mac下使用nvim的时候，需要在nvim的autoload里面放Plug.vim插件。

### ISSUE THREAD

**Issue by forbreak** [liuchengxu/space-vim#25]
mac下使用nvim的时候，需要在nvim的autoload里面放Plug.vim插件。
在文档里面多加一句这个吧。
ln -s ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/plug.vim

不太会用github提交，先发个问题吧。

**Comment by liuchengxu** [comment]
谢谢，我会在下次提交时注明这一点。
