### ISSUE TITLE
怎么文件夹下查找字符串

### ISSUE THREAD

**Issue by dodong471520** [liuchengxu/space-vim#251]
怎么文件夹下查找字符串

**Comment by liuchengxu** [comment]
`:Ag`.

**Comment by dodong471520** [comment]
thanks

**Comment by dodong471520** [comment]
space-vim 里面有集成的吗

**Comment by liuchengxu** [comment]
实际上使用的是 [fzf.vim](https://github.com/junegunn/fzf.vim) 和 [fzf](https://github.com/junegunn/fzf)，`fzf` Layer 已经包含了这两个插件。

**Comment by dodong471520** [comment]
那用这个怎么查找文件夹里的字符串
