### ISSUE TITLE
how to disable matchparen?

### ISSUE THREAD

**Issue by lancelock** [liuchengxu/space-vim#252]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
vim 8.0
```

#### Problem Description

i have used `let loaded_matchparen = 1` in UserConfig, but it does't works, what's the reason?

**Comment by liuchengxu** [comment]
See if this helps https://stackoverflow.com/questions/34675677/disable-highlight-matched-parentheses-in-vim-let-loaded-matchparen-1-not-w .
