### ISSUE TITLE
deoplete layer 的config.vim不知道是否有一点小瑕疵？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#258]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ x] Terminal Vim
    - [ ] GVim
    - [x ] NeoVim

```


```

#### Problem Description
deoplete layer 作者似乎是想支持vim8的使用，因此在package.vim 添加了
  MP 'Shougo/deoplete.nvim'
  MP 'roxma/nvim-yarp'
  MP 'roxma/vim-hug-neovim-rpc'
但是在config.vim 当中似乎是 if g:spacevim_nvim，
要是默认使用这个layer的话，vim8 的使用不能生效，还需要手动添加
let g:deoplete#enable_at_startup = 1，感觉要是这样的话在这个layer 的config.vim里面的一些配置还是没有应用到vim8中。
感谢作者的配置，萌新一枚，要是issue提错了还请作者见谅。

**Comment by liuchengxu** [comment]
说得对，已更新，谢谢！
