### ISSUE TITLE
A bit of a lag when you first time enter insert mode (首次进入插入模式时可能会感到些许的停顿或延迟)

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/space-vim#26]
When first time enter insert mode, you may feel a bit of delay, for vim-plug is probably loading the two vim plugins: ultisnips and YouComplteMe, which have a huge effect on the startup of vim, several hundred milliseconds I guess. 

In order to obtain a faster startup, I referred to [loading-plugins-manually](https://github.com/junegunn/vim-plug/wiki/faq#loading-plugins-manually) for a solution, which is only when you first time enter insert mode ultisnips and YouCompleMe starts to play their expected roles.

Now space-vim can start in no more than 200 ms without opening any files, which is much faster than before. 

If you have a better workaround to get a faster startup without this issue, please let me know. Thanks!

当你打开 vim, 第一次进入插入模式时，也许会感到些许的停顿或者延迟，这是因为 vim-plug 可能在加载 ultisnips 或 YouCompleteMe 这个两个插件. 

因为基于加速 vim 启动的考虑, 我参考了这里 [loading-plugins-manually](https://github.com/junegunn/vim-plug/wiki/faq#loading-plugins-manually)， 在首次进入插入模式时才加载这两个对启动时间非常有影响的插件。

只是在第一次进入插入模式时可能会有感觉，加载以后就正常了。如果仍然觉得体验不好，可以不使用 ycmd, 启用 auto-completion layer, 它使用的是 neocomplete.vim.

在进行这样的处理后，space-vim 打开空文件的启动时间可以保持在 200 ms 以内，有非常大的提升，我想这是非常值得的。当然，如果有一些更好的加速方法可以规避这个点，非常欢迎您能分享给大家。

**Comment by monkeydterry** [comment]
我也是这样，解决方案大概只有不用ycm了...

**Comment by wsdjeg** [comment]
当初为了这个事情，我纠结太久了，后来用了neovim 以及 deoplete，发现安装插件如此简单，ycm安装太麻烦，仓库还用子模块管理。

**Comment by liuchengxu** [comment]
@monkeydterry 也不至于吧...., 只是在首次进入插入模式时会有一丢丢的延迟，但比起它能够提供的强大功能还是值得的. 可能会有更好的解决方案的，总要有所期待嘛 😹

**Comment by liuchengxu** [comment]
@wsdjeg 应该还好，首次安装主要看网速，需要提前下载 cmake, 而 YouCompleteMe 首次安装时会自动下载 clang 并存放在本地，这也会需要一些时间。不过以后更新什么的就不用了，它会使用存储的 clang archive。因此只要成功安装一次，以后就都顺利了。

**Comment by wsdjeg** [comment]
@liuchengxu 对，我当初在访问外网不方便，下了非常久，后期更新，编译还算快，不过我不用YCM主要原因是他对vim原生的omni支持不好，我看了后台代码，只是简单调用`c-x c-o`,  而且对有些字符还无法调用补全。当初为了这个事情，fork了一个，做了适当的修改，但是 后来发现一直有bug，所以换了deoplete，主要是deoplete有跟好的可拓展性。

我觉得 咱们两项目可以相互支持学习，我的项目，文件结构和你的，包括和spacemacs不一致，我只是采用了原理。

**Comment by liuchengxu** [comment]
@wsdjeg 就像 README 里所写的, 我可能没有足够的时间加入到一个组织或是投入到另外一个类似的 vim distribution 中。

但我非常赞成相互学习，共同改进，这是一件利己利人的事情。

**Comment by zgqq** [comment]
首次i很慢，应该是懒加载的锅

**Comment by liuchengxu** [comment]
@zgqq
ultisnips 是在首次进入插入模式时加载，YouCompleteMe 是针对一些文件类型 ( https://github.com/liuchengxu/space-vim/blob/master/layers/%2Btools/ycmd/packages.vim#L15 ) , 比如 c, python, shell 等等在首次进入插入模式时加载。

这是有意为之，主要是想保持启动速度，因为 ultisnips 与 YouCompleteMe 对 vim 的启动速度影响比较大，大概有几百毫秒，已经可以感知到差别。这么延迟加载能够使得空 vim 的启动时间在 200 ms, 甚至是 150 ms 以下。

如果不希望 lazy loading 的话，能够接受 vim 启动不那么迅速的话，也是可以选择取消的。Exclude 以后再把这两个当做是 private plugin 放到 `UserInit()` 中就好了。

因为还没有两全其美的方法，所以目前的方案只能是这样。

**Comment by liuchengxu** [comment]
I have switched from YCM to [completor.vim](https://github.com/maralla/completor.vim) and [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) for quite a while. These two auto-completion plugins are really great, utterly fast and lightwight. Now, it's sufficient to only have [auto-completion](https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bcompletion/auto-completion/README.md) layer enabled.
