### ISSUE TITLE
如何关闭输入时自动弹出的左侧横条

### ISSUE THREAD

**Issue by programscape** [liuchengxu/space-vim#263]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  6 2018 15:48:06)
```

#### Problem Description

When I Input Some Word , In left of vim pop this , But I don't know the problem is a feature or other? Please tell me the problem name or tell me how to solve it.
当我输入一些内容的时候，在左侧会出现一个窗口横条，当输入完成后，又会自动关闭，但我不知道该怎么称呼它，也不知道是一个 feature 还是 bug，烦请告知这个窗口的出现是一个问题还是特性，如果再有可能的话，希望告诉我怎么关闭它。

![截图](https://ws1.sinaimg.cn/large/006tNc79ly1fnnip4r472j305a0ogn0z.jpg)

**Comment by liuchengxu** [comment]
你的配置文件 `.spacevim`？

**Comment by liuchengxu** [comment]
你所说的左侧横条是 `signcolumn`，一些插件用到了这个特性，比如 git-gutter, YouCompleteMe, ale 等等用来显示一些信息。
