### ISSUE TITLE
Keep highlight when moving cursor

### ISSUE THREAD

**Issue by buptweixin** [liuchengxu/space-vim#266]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description

When I move the cursor, the search highlight will disappear. What can I do to keep it? Thank you.

**Comment by liuchengxu** [comment]
The functionality of clearing highlight automatically is provided by [is.vim](https://github.com/haya14busa/is.vim). Override [the related default mappings](https://github.com/liuchengxu/space-vim/blob/4850ccc4c697588383dbb12a6c72458477dc3713/layers/%2Bdistributions/better-defaults/config.vim#L22-L23) via removing `<Plug>(is-nohl)`:

```vim
function! UserConfig()
  map n <Plug>(anzu-n-with-echo)
  map N <Plug>(anzu-N-with-echo)
endfunction
```

**Comment by buptweixin** [comment]
It's work! Thank you.
