### ISSUE TITLE
感觉有一些 layer 没有正常载入生效？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#268]
#### Environment

- OS:
    - [ x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
  环境是arch linux ，删除了所有插件并把space-vim 也已经更新到最新。
```

#### Problem Description
  Layer 'markdown'   添加之后，
![markdown-preview](https://user-images.githubusercontent.com/22888402/35747044-d6feff46-0883-11e8-8499-c149bab95f10.png)

  Layer 'markdown',{'exclude':'iamcco/markdown-preview.vim'}
  然后在private中重装( Plug 'iamcco/markdown-preview.vim' )后,上面问题解决。
 之前的code-snippets 也有相似的状况，添加这个layer 后在vim8 中可以生效，但是在nvim 中不能生效。
 最后在.spacevim 删除了这个layer 然后在private 中安装了那两个插件，并在config 中复制了你的原本code-snippets中config的配置。也修改了一点点，  
let g:UltiSnipsExpandTrigger = "<nop>"
  let g:ulti_expand_or_jump_res = 0
  function ExpandSnippetOrCarriageReturn()
      let snippet = UltiSnips#ExpandSnippetOrJump()
      if g:ulti_expand_or_jump_res > 0
          return snippet
      else
          return "\<C-y>"
      endif
  endfunction
  inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrCarriageReturn()<CR>" : pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
这样的话好像可以解决有点怪怪的换行。
问题解决。

没搞懂哪里出了问题。

**Comment by liuchengxu** [comment]
`MarkdownPreview` 可能是由于 vim 刚启动在加载其他插件，没有响应，过一段时间应该就可以了。

**Comment by pittcat** [comment]
应该是你说的那样，在show-plugin-status 里面查看是not load 。等了一会了依然没反映，切换了一波suan/vim-instant-markdown，自动打开浏览器显示没问题，但是输入它本身的InstantMarkdownPreview 命令和上面一样不能生效。shime/vim-livedown 命令输入和自动打开浏览器都能正常触发运行。最后还是选择了suan/vim-instant-markdown。谢谢大佬回复。
