### ISSUE TITLE
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda` Press ENTER or type command to continue [13]  + 3053 suspended  vim .

### ISSUE THREAD

**Issue by joneyphair** [liuchengxu/space-vim#273]
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`
Press ENTER or type command to continue
[13]  + 3053 suspended  vim .

**Comment by joneyphair** [comment]
![image](https://user-images.githubusercontent.com/8407484/36941714-dd73b10c-1f9c-11e8-8287-586a49026eb9.png)

show error

**Comment by liuchengxu** [comment]
You need to recompile or reinstall Vim to get the necessary features. `auto-completion` Layer utilizes [completor.vim](https://github.com/maralla/completor.vim/#requirements) for the auto complete functionality.

**Comment by sukai-cheng** [comment]
I don't know how to deal with it, I'm so confused

**Comment by liuchengxu** [comment]
@sukai-cheng I personally no longer use `auto-completion` layer and switched to coc for quite a while, see [let g:spacevim_lsp_engine = 'coc'](https://github.com/liuchengxu/dotfiles/blob/ecc1cae8fabcc74bb9fce693b0231af6360ef442/spacevim#L22) .
