### ISSUE TITLE
<C-j> keybinding conflict between tmux and editing layers

### ISSUE THREAD

**Issue by vladucu** [liuchengxu/space-vim#274]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] NeoVim

```
NVIM v0.2.3-711-g71e89cec2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-par
ameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180218-4956-1oblp4g/build/config -I/tmp/neovim-20180218-4956-1oblp4g/src
 -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180218-4956-1oblp4g/build/src/nvim/auto -I/tmp/neovim-20180218-4956-1oblp4g/build/include
Compiled by vladucu@Vlads-MacBook-Pro.local

Features: +acl +iconv +jemalloc +tui
```

#### Problem Description

When both `tmux` and `editing` layers are loaded, without any customizations...`<C-j>` mapping from `vim-tmux-navigator` is not working....seems a conflict added [here](https://github.com/liuchengxu/space-vim/blob/master/layers/+programming/editing/config.vim#L12)

**Comment by liuchengxu** [comment]
I think there is a quick workaround:

```vim
function! UserConfig()
  nnoremap <silent> <c-p> :TmuxNavigateDown<cr>
endfunction
```

change `<c-p>` to whatever you like, just remap `:TmuxNavigateDown`. I basically don't use tmux layer. Do you have any better suggestions? @tracyone
