### ISSUE TITLE
nerd commenter

### ISSUE THREAD

**Issue by senior7515** [liuchengxu/space-vim#276]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

['fzf', 'unite', 'better-defaults', 'which-key', 'c-c++', 'go', 'airline', 'python', 'scala', 'markdown', 'ycmd', 'file-manager', 'editing', 'programming', 'games', 'github', 'git', 'spacevim']     

#### Problem Description

nerdcommenter.

if i type `<space>cc` nothing happens. how to trigger a comment of a block.

**Comment by 3ter** [comment]
https://spacevim.org/documentation/#commenting
