### ISSUE TITLE
vim不指定py文件时, ycmd不会启动

### ISSUE THREAD

**Issue by eleveni386** [liuchengxu/space-vim#278]
#### Environment

- OS:
    - [* ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [* ] NeoVim

```

```

#### Problem Description

我想问下 当我直接启动vim 不指定任何文件的时候, 这个时候ycmd 是不会启动,  哪怕我在vim 里面通过nerdtree 去打开某个py文件, 此时ycmd也是不会启动的.  但是当我在启动vim的时候 指定了要打开的文件(py) 此时 ycmd 就会自己启动了.  这是什么情况? 我要如何配置? 让ycmd 可以识别到nerdtree中打开的文件, 而启动呢?

**Comment by eleveni386** [comment]
@liuchengxu  嗯, 我这个我知道.  我的情况时. 仅输入vim 后面不接任何文件名. 此时 ycmd 是不会启动的(这个我可以理解, 因为ycmd遇到特定文件类型才自启动) , 然后 我在vim里面通过nerdtree 打开了 某个python文件. 此时ycmd也没有启动起来,  就是说 如果在启动vim的时候 没有指定文件的话 , 且没有指定ycmd支持的文件的时候, 那么不管在vim里面 通过何种手段再编辑其他 ycmd支持的文件类型时. 此时 ycmd也是不会启动起来了.

**Comment by liuchengxu** [comment]
你可以试着进入插入模式，在首次进入插入模式时也会尝试启动。

https://github.com/liuchengxu/space-vim/blob/5dbd395f8fa218b4c29bf259a070e28fd71bb984/layers/%2Btools/ycmd/packages.vim#L9-L12

**Comment by eleveni386** [comment]
@liuchengxu  然而并没有成功.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/commit/a86ed43939b7e61c800fb48e06f39caee6418115

请尝试更新 space-vim, 现在加载 youcompleteme 有两种途径：

1. 通过 timer 的回调函数加载，即在启动后 1 秒无论文件类型是什么都会进行加载。
2. 如果在 timer 的回调函数加载之前进入了插入模式，那么会针对部分的类型文件进行加载。
