### ISSUE TITLE
layers下的文件夹名字为啥要以加号开始...

### ISSUE THREAD

**Issue by monkeydterry** [liuchengxu/space-vim#28]
这是出于什么理由呢？？

你看CtrlP都把+号开始的文件夹名字过滤掉了，本来想用ctrlp来搜索的，结果搜索不到大大打击信心。。。。😢

**Comment by wsdjeg** [comment]
spacemacs 的 锅。

**Comment by liuchengxu** [comment]
这确实是跟 spacemacs 学的..... 🙉

**Comment by liuchengxu** [comment]
@monkeydterry 要不试试用 fzf 搜索？

**Comment by monkeydterry** [comment]
恩，既然你喜欢用fzf，竟然映射的按键那么难用，得按四个按键spc+f+shift+?😶

问个问题吧，我全局搜了下你的配置，似乎没有一个地方是集中放option的设置的，比如我觉得最好改变默认backspace的动作为好，这个option的设置放在better default合适吗？

**Comment by liuchengxu** [comment]
@monkeydterry 可能你没有用过 spacemacs, 不太了解 space-vim 的套路.....

space-vim 中没有 4 个键的映射，至多为 `SPC` 即空格键加上两个键，在 spacemacs 的 mnemonics 基础上我已经做了很多适应。`SPC f f`, 空格键+f+f 即为使用 fzf 在当前目前下进行搜索，第一个 f 可记为 file, 第二个 f 可记为 find, 十分易于记忆。 

在个人的配置文件 `.spacevim` 中, 有个函数 `UserConfig()`, 这个就是专门用来放置自己的个性化设置的，这里的配置会覆盖已有的信息。

**Comment by liuchengxu** [comment]
如果没有问题就关闭这个 issue 了。
