### ISSUE TITLE
添加fzf 的预览，也可以解决一下tmux Ctrl arrow 的矛盾。

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#280]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
fzf 预览，tmux 中 ctrl arrow 的矛盾，tweekmonster/fzf-filemru在LAYERS.md中提及但是并没有在fzf layer 中安装
```

##### fzf 预览---->依赖Ag 或者Rg
 " fzf
  let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
    \ 'bg':      ['bg', 'Normal'],
    \ 'hl':      ['fg', 'Comment'],
    \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
    \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
    \ 'hl+':     ['fg', 'Statement'],
    \ 'info':    ['fg', 'PreProc'],
    \ 'border':  ['fg', 'Ignore'],
    \ 'prompt':  ['fg', 'Conditional'],
    \ 'pointer': ['fg', 'Exception'],
    \ 'marker':  ['fg', 'Keyword'],
    \ 'spinner': ['fg', 'Label'],
    \ 'header':  ['fg', 'Comment'] }
  autocmd VimEnter * command! -bang -nargs=* Ag
              \ call fzf#vim#ag(<q-args>,
              \                 <bang>0 ? fzf#vim#with_preview('up:60%')
              \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
              \                 <bang>0)
  nnoremap <leader>ap :Ag!<cr>
  " Likewise, Files command with preview window
  command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

##### 修复tmux 中的键位矛盾

  " fix tmux and vim
  if &term =~ '^screen'
      " tmux will send xterm-style keys when its xterm-keys option is on
      execute "set <xUp>=\e[1;*A"
      execute "set <xDown>=\e[1;*B"
      execute "set <xRight>=\e[1;*C"
      execute "set <xLeft>=\e[1;*D"
      execute "set <xHome>=\e[1;*H"
      execute "set <xEnd>=\e[1;*F"
  endi

**Comment by liuchengxu** [comment]
不太明白你的意思 :)

**Comment by pittcat** [comment]
* [ tmux 下Ctrl arrow 无法正常工作 ](https://superuser.com/questions/401926/how-to-get-shiftarrows-and-ctrlarrows-working-in-vim-in-tmux)<br>
* [fzf 添加 预览 ，在Advanced customization 里面有写到](https://github.com/junegunn/fzf.vim)<br>
* LAYERS.md 中有写fzf-filemru 但是 fzf layer里面没有写进去
![image](https://user-images.githubusercontent.com/22888402/38172544-93d5bcb6-35e0-11e8-8619-327fed0acd57.png)
![image](https://user-images.githubusercontent.com/22888402/38172556-df517da6-35e0-11e8-8d84-75143fbdd36e.png)

**Comment by liuchengxu** [comment]
LAYERS.md 是通过执行脚本手动更新的，有时可能没跟上最新版本。

```bash
$ cd layers && python generate_layers.py
```

至于其他点，欢迎提 PR。

**Comment by pittcat** [comment]
好的，谢谢。
