### ISSUE TITLE
插入模式下无法连续输入 `j`

### ISSUE THREAD

**Issue by jjjjyx** [liuchengxu/space-vim#281]
#### Environment

- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
插入模式下无法连续输入 `j`
```

#### Problem Description
你好 我在使用这个插件的遇到一个奇怪的问题，由于我的用户名是jjjjyx ，因此在编辑文件的时候需要连续输入`j`，但是我在插入模式下输入一个`j` 在输入`j`时将会退出插入模式跳转到下一行。

**Comment by liuchengxu** [comment]
插入模式下 `jj` 和 `jk` 被映射为 `<Esc>`，快速按两下 `j` 等于 `<Esc>` 退出插入模式。

https://github.com/liuchengxu/vim-better-default/blob/f9de3c3298570d1a205f13ef21fdaaac6407515b/plugin/default.vim#L223-L227

**Comment by jjjjyx** [comment]
@liuchengxu  `这么个回事，看来得我得专门为的我的用户名修改下配置文件
