### ISSUE TITLE
如何一次删除多个插件？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#284]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description
 { 'exclude': 'tiagofumo/vim-nerdtree-syntax-highlight' }可以删除一个插件，如果要删除多
个插件要如何正确操作呢？

**Comment by liuchengxu** [comment]
`exclude` 的 key 可以是数组，`{ 'exclude': ['plugin1', 'plugin2'] }`。
