### ISSUE TITLE
exclude 删除haya14busa/incsearch-easymotion.vim ，报错[vim-plug] Unknown plugin: incsearch-easymotion.vim

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#297]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x ] NeoVim

```

```

#### Problem Description
exclude 删除haya14busa/incsearch-easymotion.vim ，报错[vim-plug] Unknown plugin: incsearch-easymotion.vim
应该是 call timer_start(600, 'spacevim#defer#motion')的原因,在space-vim/core/autoload/spacevim/defer<br>
        `call plug#load('incsearch-easymotion.vim')`
也许应该修改为
`if has_key(g:plugs, 'incsearch.vim') 
            call plug#load('incsearch-easymotion.vim')
endif`

**Comment by pittcat** [comment]
请教一下，defer.vim 的作用是什么呢？是加快启动速度吗？

**Comment by liuchengxu** [comment]
延迟加载部分插件，见 https://github.com/liuchengxu/space-vim/pull/232 。

这个错误并不影响使用，晚点我看一下是否有比较 *友好* 的方式避免。

**Comment by pittcat** [comment]
哦哦

**Comment by liuchengxu** [comment]
这回应该没问题了，https://github.com/liuchengxu/space-vim/commit/9214c67c56ee483aeceaa4a5f13a2c5e7f7cb440 ，`plug#load` 传入多个插件时，如果出现错误，会影响传入的其他插件，逐个加载就行了。

**Comment by pittcat** [comment]
行了，谢谢

**Comment by exten** [comment]
Layer 'file-manager',{'exclude':'danro/rename.vim'} 是否支持排除多个插件呢？是数组形势还是？
