### ISSUE TITLE
是否支持neovim呢

### ISSUE THREAD

**Issue by pkking** [liuchengxu/space-vim#3]

**Comment by liuchengxu** [comment]
目前还并没有测试，也没有使用一些针对 neovim 的很好的插件。不过如果您已有一定使用经验，愿意尝试兼容，应该也是可以的。我目前也有在本地使用 neovim (调整 space-vim 崩溃时使用)，只要将 vim 的相关文件对应到 neovim 即可。

后期会兼容 neovim, 尽请期待，也非常欢迎您能贡献.

**Comment by pkking** [comment]
ok，因为自动安装脚本会判断vim，我以为你已经做过测试了
我会人肉测试的：）

**Comment by liuchengxu** [comment]
如果使用 neovim, 在安装脚本完成后，只需建立一个软连接即可：

```sh
ln -s ~/.space-vim/init.vim ~/.config/nvim/init.vim
```
