### ISSUE TITLE
The function Layers() does not exist.

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/space-vim#30]
为了组织更有条理 (实际所做的事情是之前一样的 :p)，在 `.spacevim` 中我新增了一个函数 `Layers()`, 也许之前 clone 过的 space-vim 用户在更新时可能会遇到一点问题。解决很简单，将 `Layers()` 添加到 `.spacevim` 中即可。可查看 README.

```vim
function! Layers()
       Layer 'fzf'
       Layer 'unite'
       Layer 'better-defaults'
endfunction
```
新添加的 `Layers()` 可以使得各个部分的功能更加清晰：

- `Layers()` 中可以启用 space-vim 已有的 Layer，排除部分插件， `Layer` 与 `Exclude` 命令在这里是有效的。 
- `UserInit()` 中单独放置自己私有的一些插件 。
- `UserConfig()` 放置个性化配置信息对已有设置进行覆盖。

**Comment by pacuna** [comment]
having the same issue when reinstalling

**Comment by liuchengxu** [comment]
@pacuna  Sorry for that, but it makes no sense. I have just updated the `install.sh` with the function `Layers()` added. I'll dig into it.

**Comment by liuchengxu** [comment]
@pacuna I have fixed the problem, please try again.

**Comment by pacuna** [comment]
@liuchengxu thanks. I tried the manual update and everything went fine. 
Cheers!
