### ISSUE TITLE
移除 neoclide/vim-jsx-improve ？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#300]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x ] NeoVim

```

```

#### Problem Description
mxw/vim-jsx，neoclide/vim-jsx-improve  都是处理高亮缩进的插件，似乎是重复了，移除neoclide/vim-jsx-improve有一段时间了，不影响正常使用。似乎neoclide/vim-jsx-improve可以选择移除。

**Comment by pittcat** [comment]
另外 let g:jsx_ext_required = 0这样的话会导致新建一个js 文件的话，会让filetype 变成javascript.jsx，给人的直觉上有点怪，似乎有一点点不合理，不过不影响正常正常使用

**Comment by pittcat** [comment]
移除 neoclide/vim-jsx-improve
packages.vim
MP 'mxw/vim-jsx',              { 'for': ['javascript', 'javascript.jsx'] }
config.vim
let g:jsx_ext_required = 1
似乎这样还比较合理。

**Comment by liuchengxu** [comment]
js 我其实不咋写 :)，neoclide 好像在 @chemzqm 在维护，关于这两个插件有啥建议吗？

**Comment by chemzqm** [comment]
不建议一起使用，建议移除 vim-jsx
:p

**Comment by liuchengxu** [comment]
我倾向于 @chemzqm 的建议 :)

**Comment by chemzqm** [comment]
`let g:jsx_ext_required = 1` 这个选项也没啥必要，现在大多 react 项目都是 `.js`

**Comment by pittcat** [comment]
确实没什么，不影响体验

**Comment by pittcat** [comment]
嗯，随便去一个吧，就去vim-jsx也可以

**Comment by pittcat** [comment]
用chemzqm/vim-jsx-improve 其实两个都可以去的样子？

**Comment by pittcat** [comment]
`This plugin have no dependency, all the code you need for jsx and javascript is included`好像有提到

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/commit/8efce8c89d70d27da7abaa62ab792c5434865f58 移除了 `mxw/vim-jsx` :)。
