### ISSUE TITLE
Markdown syntax not hilight

### ISSUE THREAD

**Issue by Bingbingyan** [liuchengxu/space-vim#302]
#### Environment

- OS:
    - [ ] Linux
    - [X ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X ] NeoVim

```
:version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNI
BI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack
-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-2018
0209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/inc
lude -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzo
o/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

```

['spacevim', 'fzf', 'unite', 'better-defaults', 'emoji', 'goyo', 'better-motion', 'html', 'python', 'vue', 'javascript', 'java', 'markdown', 'chinese', 'tex
t-align', 'programming', 'syntax-checking', 'git']

#### Problem Description

1. Add   Plug 'rafi/awesome-vim-colorschemes'  in .spacevim UserInit（）
2. Set colorscheme to: one or grvubox
3. Open a markdown file, the markdown file not hilight as markdown syntax 

The default colorschema: **space-vim-dark**, markdown files hilight looks good.

Could you help me to find why the other color scheme not runs good?

**Comment by liuchengxu** [comment]
I guess these color schemes doesn't distinguish the [markdownH[1-5]](https://github.com/liuchengxu/space-vim-dark/blob/9cb89989de616a59c9e863a8a41df33f28e27f61/colors/space-vim-dark.vim#L225-L233) or [htmlH[1-6]](https://github.com/liuchengxu/space-vim-dark/blob/9cb89989de616a59c9e863a8a41df33f28e27f61/colors/space-vim-dark.vim#L349-L355). You can check these items' highlight setting, e.g., `:verbose hi markdownH1`.

**Comment by Bingbingyan** [comment]
3Q  let me have a try

**Comment by Bingbingyan** [comment]
:verbose hi markdownH1
markdownH1     xxx ctermfg=168 guifg=#e06c75
        Last set from ~/.vim/plugged/awesome-vim-colorschemes/colors/one.vim

:verbose hi htmlH1
htmlH1         xxx cleared
Press ENTER or type command to continue

The one.vim doesn't have htmlH[1-6].
After add htmlH[1-6] markdown syntax looks good.  

thank you so much
