### ISSUE TITLE
Spacevim initializes with terrible colors (not specified in init)

### ISSUE THREAD

**Issue by mdheller** [liuchengxu/space-vim#304]
#### Environment

- OS:
    - [ ] Linux
    - [ x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ x
![screen shot 2018-05-03 at 8 37 41 am](https://user-images.githubusercontent.com/21163552/39576842-9110a5e6-4ead-11e8-8e67-d6f16dc4736b.png)
![screen shot 2018-05-03 at 8 37 41 am](https://user-images.githubusercontent.com/21163552/39576869-a2081866-4ead-11e8-8396-063e63d8b113.png)

] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

**Comment by liuchengxu** [comment]
How about `:set notermguicolors`?

**Comment by mdheller** [comment]
in ~/.vimrc or ~/.space-vim/init.vim or elsewhere?

**Comment by mdheller** [comment]
works fine in iterm2 btw

**Comment by liuchengxu** [comment]
Modify `.spacevim` in your home directory:

```vim
function! UserConfig()
  " Comment this out
  " set termguicolors
endfunction
```

**Comment by mdheller** [comment]
worked like a charm! thanks!
