### ISSUE TITLE
关于 layer 的加载顺序问题

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#308]
.spacevim layer 的加载是从上自下依次加载，还是随机的呢？

**Comment by liuchengxu** [comment]
`:echo g:layers_loaded`，按 `Layer` 命令顺序依次加载，最后加载 `g:spacevim_layers` 变量里面的 layer。先依次加载所有 layer 的 packges.vim，再加载所有 layer 的 config.vim。
