### ISSUE TITLE
backspace问题

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/space-vim#31]
不知道多少人喜欢原来vi的backspace的行为？

一般来说，插入模式，命令模式，都设置成删除的动作吧。

这是一个，不知道各位同意不。

另外的问题：

明明默认已经是

set nocompatible
set backspace=indent,eol,start

奇怪的是，不知道为啥，没有效果

ps:macOS vim 8.0

**Comment by liuchengxu** [comment]
我这里没有问题 ..., 环境跟你是类似的，macOS 8.0, `:verbose set backspace` 看看是什么。

**Comment by tracyone** [comment]
应该是tmux+zsh的某个问题，今晚回去研究下...

**Comment by liuchengxu** [comment]
好，我用的也是 tmux + zsh + vim + iterm2/terminal, 到目前为止还没有遇到过这个问题。

**Comment by tracyone** [comment]
解决了，terminal.app设置--高级去掉**Control-H键代替delete**。
