### ISSUE TITLE
install.cmd is giving an error on windows 10.

### ISSUE THREAD

**Issue by Thorocaine** [liuchengxu/space-vim#311]
#### Environment

- OS:
    - [ ] Linux
    - [ ] macOS
    - [X] Windows
    - [ ] FreeBSD
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [X] NeoVim

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  8 2018 15:00:34)

NVIM v0.2.2
```

#### Problem Description

The install.cmd is not running in Windows (version 10).

when running install.cmd I get the following error message:

```
Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:1066
+ ... ug.vim';    (New-Object Net.WebClient).DownloadFile($uri,$ExecutionCo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by liuchengxu** [comment]
From what I can tell, it's related to your local environment, see:

- https://stackoverflow.com/questions/29942729/powershell-unable-to-connect-to-internet-at-all
- https://isc.sans.edu/forums/diary/Blocking+Powershell+Connection+via+Windows+Firewall/21829

**Comment by Thorocaine** [comment]
Thank you.
