### ISSUE TITLE
nvim 感觉启动有一点慢,如何正确添加skip 选项呢？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#314]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x ] NeoVim

```

```

#### Problem Description

想将nvim 的启动速度加快一点，添加let g:python_host_skip_check = 1  ,let g:python3_host_skip_check = 1到.spacevim ，但是速度并没有提升？

**Comment by liuchengxu** [comment]
首先看一下启动日志。
```bash
$ nvim --startuptime nvim.log
```

**Comment by pittcat** [comment]
[nvim-log](https://gist.github.com/pittcat/f19a7fd7e91ec7033c2d65c60f1defd5)

`006.145  000.057  000.057: sourcing /usr/share/nvim/runtime/autoload/provider/pythonx.vim
053.821  047.771  047.714: sourcing /usr/share/nvim/runtime/autoload/provider/python.vim
079.124  000.151  000.151: sourcing /usr/share/nvim/runtime/autoload/remote/host.vim
079.210  025.315  025.164: sourcing /usr/share/nvim/runtime/autoload/provider/python3.vim
164.961  000.049  000.049: sourcing /usr/share/nvim/runtime/autoload/provider.vim
`

这几行时间增加有点快。

**Comment by liuchengxu** [comment]
指定 `g:python_host_prog`.
```vim
let g:python_host_skip_check=1
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_skip_check=1
let g:python3_host_prog = '/usr/local/bin/python3'
```

**Comment by pittcat** [comment]
添加了的啊，但是添加与不添加的nvim log 可以说没什么差别？然后我就怀疑我是不是没有正确添加。

**Comment by liuchengxu** [comment]
那你可以尝试去 neovim 提个 issue 问一下:)

**Comment by pittcat** [comment]
哦哦
