### ISSUE TITLE
vim can not begin

### ISSUE THREAD

**Issue by programes** [liuchengxu/space-vim#315]
#### Environment

- OS:
    - [ ] Linux
    - [ ] macOS
    - [*] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [*] GVim
    - [ ] NeoVim

```

```

#### Problem Description

Error detected while processing function spacevim#begin[7]..<SNR>
2_check_dot_spacevim:

line    4:

E716: Key not present in Dictionary: loaded + g:spacevim_layers

E15: Invalid expression: g:spacevim.loaded + g:spacevim_layers

Error detected while processing function <SNR>2_layer:

line    1:

E716: Key not present in Dictionary: loaded, a:name) == -1

E116: Invalid arguments for function index(g:spacevim.loaded, 
a:name) == -1

E15: Invalid expression: index(g:spacevim.loaded, a:name) == -1

Error detected while processing function spacevim#end[7]..<SNR>2
_register_plugin[8]..<SNR>2_packages:

line    2:

E716: Key not present in Dictionary: loaded

E15: Invalid expression: g:spacevim.loaded

line   22:

E716: Key not present in Dictionary: base . '/private/packages.vim'

E15: Invalid expression: g:spacevim.base . '/private/packages.vim'

line   23:

E121: Undefined variable: l:private_packages

E116: Invalid arguments for function expand(l:private_packages))

E116: Invalid arguments for function filereadable(expand(l:private_p
ackages))

E15: Invalid expression: filereadable(expand(l:private_packages))

Error detected while processing function spacevim#end[7]..<SNR>2
_register_plugin[10]..<SNR>2_filter_plugins:

line    1:

E716: Key not present in Dictionary: plugins, 'index(g:spacevim.exclu
ded, v:val) < 0')

E116: Invalid arguments for function filter

Error detected while processing function spacevim#end[7]..<SNR>2
_register_plugin[11]..<SNR>2_invoke_plug:

line    1:

E716: Key not present in Dictionary: plugins

E15: Invalid expression: g:spacevim.plugins

Error detected while processing function spacevim#end[12]..<SNR>
2_config:

line    2:

E716: Key not present in Dictionary: loaded

E15: Invalid expression: g:spacevim.loaded

line   17:

E716: Key not present in Dictionary: base . '/private/config.vim'

E15: Invalid expression: g:spacevim.base . '/private/config.vim'

line   18:

E121: Undefined variable: l:private_config

E116: Invalid arguments for function expand(l:private_config))

E116: Invalid arguments for function filereadable(expand(l:private_co
nfig))

E15: Invalid expression: filereadable(expand(l:private_config))

Error detected while processing function spacevim#end[16]..<SNR>
2_post_user_config:

line    5:

E716: Key not present in Dictionary: os.windows

E15: Invalid expression: !g:spacevim.os.windows

**Comment by liuchengxu** [comment]
Delete `~/.space-vim/core/autoload/spacevim/info.vim` and change variable like `g:spacevim_tmux` to `g:spacevim.tmux` if you used these in `.spacevim`, see #313 .

**Comment by liuchengxu** [comment]
Feel free to reopen if the issue persists after you delete `~/.space-vim/core/autoload/spacevim/info.vim`.

**Comment by programes** [comment]
Thanks。It works！

**Comment by ElvisAttro** [comment]
Worked like a charm!
