### ISSUE TITLE
在哪查看每个模块的具体介绍啊，文档里没说

### ISSUE THREAD

**Issue by forgiveboo** [liuchengxu/space-vim#316]
#### Environment

- OS:
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

**Comment by liuchengxu** [comment]
- https://github.com/liuchengxu/space-vim#how-to-use
- https://github.com/liuchengxu/space-vim/wiki/layer

layers 目录下面是每个 topic，每个 topic 下面是每个 layer，里面有 README.md 简要说明。不过我现在没时间写文档，很多文档比较简略。详细内容可以查看每个 layer 下面的 config.vim 和 packages.vim。
