### ISSUE TITLE
ycmd only run if I execute vim without any filename

### ISSUE THREAD

**Issue by qwIvan** [liuchengxu/space-vim#321]
#### Environment

- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
0.7.0
```

['fzf', 'unite', 'better-defaults', 'which-key', 'spacevim', 'git', 'chinese', 'docker', 'editing', 'programming', 'formatting', 'code-sni
ppets', 'python', 'c-c++', 'markdown', 'vue', 'java', 'html', 'javascript', 'better-motion', 'ycmd', 'file-manager', 'auto-completion']
#### Problem Description

启动vim不加任何参数时，才能启动ycmd，只要加上了参数（例如 vim demo.py）就无法加载ycm

**Comment by liuchengxu** [comment]
首先更新一下 space-vim 再测试一下 :)。

然后看一下正常加载与未加载的 `:scriptnames`。

**Comment by qwIvan** [comment]
我卸载了 vim-youcompleteme-git 后可以了
