### ISSUE TITLE
当窗口分割当中存在quickfix 窗口的时候，bdelete 会直接退出窗口，而不是关闭当前buffer.

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#325]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ x] NeoVim

```

```

#### Problem Description
先用copen 打开一个quickfix ,然后再执行bd,[过程](https://asciinema.org/a/HCAAl1G9b3JmtqS00IENhHPuw)

vim -u NONE启动不会有这种状况.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/spacevim/config.vim#L33 如果 `:bd` 以后只剩一个窗口，比如 quickfix, 会自动退出。
