### ISSUE TITLE
为什么auto-pairs无法自动加载，什么情况下才会自动加载？

### ISSUE THREAD

**Issue by qwIvan** [liuchengxu/space-vim#329]
#### Environment

- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description
`PlugStatus` 显示 not loaded
在配置文件中显式加载倒可以

**Comment by qwIvan** [comment]
发现`auto-paris`其实可以自动懒加载，但是没有生效。还是要手动`:call AutoPairsTryInit()`才能生效。

**Comment by qwIvan** [comment]
或者我触发以下`BufEnter`，也可以生效
https://github.com/jiangmiao/auto-pairs/blob/master/plugin/auto-pairs.vim#L582

**Comment by liuchengxu** [comment]
现在应该好了，auto-pairs 会在进入插入模式或者空闲的时候加载。

**Comment by qwIvan** [comment]
https://github.com/liuchengxu/space-vim/commit/40291ccd676ac9303f414717260f6d7cb9e70be4
可以了
