### ISSUE TITLE
when quickfix window already opened，no need to execute “copen 8” command

### ISSUE THREAD

**Issue by Bingbingyan** [liuchengxu/space-vim#331]
#### Environment

- OS:
    - [ ] Linux
    - [X] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] NeoVim

```

```

#### Problem Description

当Quickfix窗口放到右侧时，在nvim中执行编辑的代码后，nvim底部命令窗口变得很高，文件编辑窗口只有8行的高度。

建议将 /layers/+distributions/spacevim/config.vim 第32 行，修改为：

  if !exists("g:qfix_win") && a:forced == 0
    autocmd QuickFixCmdPost * botright copen 8
  endif

**Comment by liuchengxu** [comment]
你应该这个是不完整的。

参见：
- https://stackoverflow.com/questions/8061229/detecting-if-quickfix-buffer-exists-in-vim
- http://vim.wikia.com/wiki/Toggle_to_open_or_close_the_quickfix_window

**Comment by Bingbingyan** [comment]
是的，我没有判断，quickfix 窗口已经打开的情况。
我认为quickfix 已经打开的时候，不需要再去关闭它，就让quickfix窗口，保持当前的状态就可以了。
只有在quickfix窗口，没有打开的时候，才需要去打开它。

**Comment by liuchengxu** [comment]
我的意思是你这个语法是不过的 :(

可以参考这里改进，检测是否存在 quickfix, 如果不存在, 自动打开。https://www.reddit.com/r/vim/comments/5ulthc/how_would_i_detect_whether_quickfix_window_is_open/

**Comment by Bingbingyan** [comment]
哦哦  我新手，我瞅瞅看。

**Comment by liuchengxu** [comment]
我已经改了，你可以看一下，如果 quickfix window 没有打开的话自动打开。

**Comment by Bingbingyan** [comment]
现在quickfix window 正确了。

能不能帮忙科普一下
我下面这样写，为啥不正确啊？
  if len(filter(range(1, winnr('$')), 'getwinvar(v:val, "&ft") == "qf"')) == 0
    autocmd QuickFixCmdPost * botright copen 8
  endif

**Comment by liuchengxu** [comment]
是要设置在事件发生时执行相关操作，你这个写法是在 vimrc 加载时判断是否存在 quickfix window，然后设置 autocmd 事件。加载 vimrc 时 quickfix window 肯定不存在，所以配置无效。逻辑放在 autocmd 后面，了解事件见 `:h autocmd`, `:h autocmd-events`。
