### ISSUE TITLE
typing jk in insert mode leaves insert mode

### ISSUE THREAD

**Issue by nwmcsween** [liuchengxu/space-vim#335]
#### Environment

- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

As the title says typing jk in insert mode will leave insert mode.

**Comment by liuchengxu** [comment]
Yeah, that's intentional, see `:verbose imap jk`. 

To *fix* it, try unmap it in `UserConfig()` for now:

```vim
function! UserConfig()
  iunmap jk
endfunction
```

Actually, I began to doubt that such a key mapping is a good idea, which may be removed in the future :).

**Comment by zhaozg** [comment]
+1 for remove imap jk

**Comment by liuchengxu** [comment]
`jk` mapping in insert mode has been removed, no need to check any more.
