### ISSUE TITLE
relativenumber only enable when file lines less then 1000?

### ISSUE THREAD

**Issue by qwIvan** [liuchengxu/space-vim#337]
相对行号只在1000行以内的文件有效吗？

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/9eb8427eb0dac7bc5c1b563bcc665f1eba257154/layers/%2Bdistributions/spacevim/config.vim#L23-L26

默认如果超过 1000 行就会禁用相对行号，因为相对行号会对性能有一定影响。
