### ISSUE TITLE
添加 在autoload中添加 escalt.vim，让 alt更好的在tmux 下面更好工作？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#338]
#### Environment

- OS:
    - [x ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```
```

#### Problem Description
alt 键在tmux 下的一些map 不能正常工作，建议添加 lilydjwg师傅的[escalt.vim](https://github.com/lilydjwg/dotvim/blob/master/plugin/escalt.vim)

**Comment by pittcat** [comment]
另外之前的一个[tmux pr](https://github.com/liuchengxu/space-vim/blob/master/layers/%2Btools/tmux/config.vim)应该要删除掉这一段。

              if g:spacevim.tmux
                if spacevim#load('unite')
                    "CtrlP tmux window
                    nnoremap <Leader>mw :CtrlPTmux w<cr>
                    "CtrlP tmux buffer
                    nnoremap <Leader>mf :CtrlPTmux b<cr>
                    "CtrlP tmux session
                    nnoremap <Leader>mm :CtrlPTmux<cr>
                    "CtrlP tmux command
                    nnoremap <Leader>md :CtrlPTmux c<cr>
                    "CtrlP tmux command interactively
                    nnoremap <Leader>mi :CtrlPTmux ci<cr>
                endif
                "let g:tmuxify_map_prefix = '<leader>u'
              endif

**Comment by liuchengxu** [comment]
我没用过，不知道有何区别。如果你觉得可行，可以提 PR，说明一下这么做的好处。

**Comment by pittcat** [comment]
有一些有关alt 键map<M-c>之类的在tmux下面没法生效，escalt.vim主要解决这个。我试着去pr 一下。

**Comment by liuchengxu** [comment]
稍微看了一下，大概应该是终端模拟器（temrinal-emulator）相关的问题，不同平台下不同终端模拟器可能都会有细微的区别，比如 macOS 下的 iTerm2 需要将 `alt` 选择 `ESC+` 才能工作。

你可以在 [wiki](https://github.com/liuchengxu/space-vim/wiki/troubleshooting) 里面介绍一下可能出现的问题以及解决方案，就不用 PR 了。
