### ISSUE TITLE
为什么加载ycmd，每次打开vim移动光标都要卡一下

### ISSUE THREAD

**Issue by if2012** [liuchengxu/space-vim#339]
#### Environment

- OS:
    - [y ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [y ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/3a0d7f5ad045ba9002726d064d937ed7d5a2c918/layers/%2Btools/ycmd/packages.vim#L12

ycmd 有延迟加载，在一开始进入 vim 的时候并不会启动，而是在首次进入插入模式或者空闲的时候才会加载。你感觉卡一下，大概就是在加载 ycmd。如果觉得体验不好的话，vim8 或者 neovim 可以使用 `auto-completion`，`let g:spacevim_use_ncm2 = 1` 使用 ncm2。在 `~/.spacevim` 可以配置：

```vim
let g:spacevim_plug_home = '~/.vim/plugged'

let g:spacevim_use_ncm2 = 1

Layer 'auto-completion'

function! UserInit()
  ...
endfunction

function! UserConfig()
  ...
endfunction
```
