### ISSUE TITLE
有什么办法查看哪一个layer出了问题吗？

### ISSUE THREAD

**Issue by pittcat** [liuchengxu/space-vim#341]
#### Environment

- OS:
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] NeoVim

```

```

#### Problem Description
在space-vim 的有一个layer 没有正常加载的时候并不会有报错，但是它不会被正常加载，那我们怎么去查看是哪一个layer 有问题呢？

**Comment by liuchengxu** [comment]
每个 layer 有自己的功能，查看对应的功能是否正常，针对性查找。一个 layer 就是加载一些插件跟配置而言，并没有什么 magic。

**Comment by pittcat** [comment]
哦哦，只是发现有时候自己去写或者修改的layer 的之后，发现没有生效，只有去查找对应的layer 有一点麻烦。

**Comment by pittcat** [comment]
![screenshot](https://user-images.githubusercontent.com/22888402/43084199-cb01a9aa-8eca-11e8-85ca-b5ec3ff519c3.png)
感觉 space-vim 的lazy load 很厉害了，可以说对比rafi 的vim-config的启动有过之而无不及，把八九十个插件只要10多ms 。

**Comment by liuchengxu** [comment]
这是计算方式的问题。裸 vim 在 15 寸 18 款 mac 上的启动时间是 7 秒左右，space-vim 在 80+ 插件，裸文件加载的情况下大概是 100+ ms，100 ms 才是你的体验时间，而不是 10 ms。

**Comment by pittcat** [comment]
嗯，确实是这样，用time vim +qa 试了一下，确实是100+ ms ,time nvim +qa 大概是200 ms 左右。

**Comment by liuchengxu** [comment]
跟你的机器也有关系，nvim 我的机器还是不超过 200 ms。

```bash
~ ❯❯❯ for i in $(seq 1 50); do nvim --startuptime /dev/stdout +q | tail -n1; done | awk '{ sum += $1 } END { print sum / NR }'
175.434
```

实际上只要在 200 ms 以内，启动时间已经不是你的瓶颈了。

**Comment by if2012** [comment]
八九十个插件10ms怎么可能。

**Comment by pittcat** [comment]
![image](https://user-images.githubusercontent.com/22888402/43150232-f85d01f2-8f9b-11e8-8635-d51d4e1afb33.png)
之前确实搞错了，vim 88个插件大概是90ms左右，也算比较快了。nvim是190左右。

**Comment by if2012** [comment]
你这个用什么测的？

**Comment by pittcat** [comment]
https://github.com/rhysd/vim-startuptime

**Comment by if2012** [comment]
你这是在命令行运行的吧，跟在vim运行结果界面不一样

**Comment by pittcat** [comment]
是的，我用time vim +qa 测出来也是差不多这个样子。这样都不行的话要怎么才可以呢？@if2012

**Comment by pittcat** [comment]
没有绝对的精确，只要很接近就行了吧。

**Comment by if2012** [comment]
恩，跟机器也有很大关系

**Comment by if2012** [comment]
你装八九十个插件都是自己加了lazyload吗？space-vim里面好像就不到10个插件lazyload

**Comment by pittcat** [comment]
好像是加了一点吧，大多是用的space-vim的配置。也对space-vim 的一些配置进行了删减。

**Comment by if2012** [comment]
其实启动时间占大头就ycm、ale、airline为数不多的几个plug

**Comment by pittcat** [comment]
我没用ycmd airline 也删除的。

**Comment by pittcat** [comment]
但是我加了lsp 的插件有点耗时间。

**Comment by if2012** [comment]
为什么不用ycm?

**Comment by if2012** [comment]
lsp不是不成熟还很耗资源

**Comment by if2012** [comment]
你用其它补全插件，像c/c++是怎么去找到用户的头文件的？

**Comment by if2012** [comment]
也是像ycm一样有一个配置文件吗

**Comment by pittcat** [comment]
deoplete-clang 或者直接deoplete 加autozimu/LanguageClient-neovim cquery 。具体的你应该自己去看文档。

**Comment by if2012** [comment]
deoplete-clang具体是哪个作者的，查了下有几个相似名字的

**Comment by pittcat** [comment]
。。。。。。。。。。。

**Comment by pittcat** [comment]
https://github.com/zchee/deoplete-clang 你找一个star 最多的不就行了吗。
