### ISSUE TITLE
默认安装了autocompletion功能吗

### ISSUE THREAD

**Issue by YvesZHI** [liuchengxu/space-vim#342]
如题。

系统：ubuntu 16.04.3

安装space-vim后，启动vim或nvim，都没有实现对c++的自动补全。

space-vim是否自带了自动补全功能？如果自带了，请问如何激活？

**Comment by liuchengxu** [comment]
在 `~/.spacevim` 启用 `auto-completion` layer:

```vim
" 如果用的是 neovim 或者 vim8 可以使用 ncm2
let g:spacevim_use_ncm2 = 1

Layer 'auto-completion'
```

其他用法再仔细看一下 README 或者 https://github.com/liuchengxu/space-vim/wiki 。

**Comment by YHYJ** [comment]
![_ _20180726134417](https://user-images.githubusercontent.com/21995281/43243695-74a1f562-90da-11e8-86c3-75cd0eb6000d.png)
这是什么原因啊

**Comment by liuchengxu** [comment]
@YHYJ  如果补全功能正常，就在 `UserConfig()` 加上：

```vim
function! UserConfig()
  if has('python3')
    silent! python3 1
  endif
endfunction
```

如果不能补全，确认已经安装了 python 的 neovim package, https://github.com/roxma/vim-hug-neovim-rpc#requirements 。
