### ISSUE TITLE
ycm有个奇怪的问题

### ISSUE THREAD

**Issue by if2012** [liuchengxu/space-vim#343]
#### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
- Vim:
    - [x] Terminal Vim

为什么不让它延迟启动，就不会自动补全了，改ycm的配置也不生效。

自己手动plug也不行，查看了PlugStatus里面ycm是加载成功的，为什么会这样？其它插件暂时都没有这个问题。

**Comment by if2012** [comment]
@liuchengxu 
.spacevim加了 Layer 'yemd'
然后ycmd这里去掉延时启动：
MP 'Valloric/YouCompleteMe', { 'do': function('spacevim#plug#youcompleteme#build')}
autocmd! User YouCompleteMe call spacevim#autocmd#youcompleteme#Init()

if g:spacevim.timer
  call timer_start(1000, 'spacevim#plug#youcompleteme#invoke')
endif
augroup loadYcm
  autocmd!
  autocmd CursorHold,CursorHoldI,InsertEnter * call spacevim#plug#youcompleteme#load() | autocmd! loadYcm
augroup END

**Comment by if2012** [comment]
然后就没有自动弹出补全了，插件是加载成功了的

**Comment by liuchengxu** [comment]
准确一点，去掉延时启动，是注释了哪些行？

**Comment by if2012** [comment]
MP 'Valloric/YouCompleteMe', { 'do': function('spacevim#plug#youcompleteme#build'), 'on': [] }
改为：
MP 'Valloric/YouCompleteMe', { 'do': function('spacevim#plug#youcompleteme#build')}

**Comment by liuchengxu** [comment]
加上下面这句就行了：

```vim
autocmd VimEnter * call youcompleteme#Enable()
```

至于 root cause，有时间你可以进一步研究，我没那么多时间:)

**Comment by if2012** [comment]
@liuchengxu 改ycm配置还是不生效，还有为什么要加这么一句" autocmd VimEnter * call youcompleteme#Enable() "，实在找不到原因

**Comment by if2012** [comment]
@liuchengxu 请教下这个插件加载一半，自己要做的话怎么实现？
