### ISSUE TITLE
关于layer 'ycmd'

### ISSUE THREAD

**Issue by YHYJ** [liuchengxu/space-vim#344]
我在.spacevim添加了layer 'ycmd'然后安装了，其他语言都支持，为什么rust不自动补全呢？需要做什么修改么？谢谢！！

**Comment by liuchengxu** [comment]
确认编译 YCM 的时候加了 `--rust-completer` 选项，https://github.com/Valloric/YouCompleteMe#installation 。

**Comment by YHYJ** [comment]
……我看家了layer以后都是自动编译的，而且在space-vim的core/...下有一个youcompleteme.vim里面写了rust的选项，我以为就会支持了，原来还要手动编译一遍……谢谢！

**Comment by YHYJ** [comment]
Thanks！！！！

**Comment by liuchengxu** [comment]
如果不加参数编译，应该不是使用 gocode 补全的 semantic completion，只是普通补全而已。


除了第一次安装，更新插件时加个 `!`，执行 `:PlugUpdate!` 也会自动编译 YCM。

**Comment by YHYJ** [comment]
好的
还有一个问题，我更新了space-vim，您不是已经家了rust支持的参数了么，还是无法补全，我在vimrc里加了关键字补全，才能补全关键字，但还是不能补全println、use、std::io  ……这些
麻烦了！！！

**Comment by liuchengxu** [comment]
多看文档：https://github.com/Valloric/YouCompleteMe#rust-semantic-completion

```bash
rustup component add rust-src
```
