### ISSUE TITLE
创建django项目输入django-admin.py startproject tutorial 不能创建项目 而是直接用vim打开一个django-admin.py文件

### ISSUE THREAD

**Issue by YellowDong** [liuchengxu/space-vim#345]
#### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```

```

#### Problem Description

OS Info:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by liuchengxu** [comment]
This issue is outside the scope of space-vim.

显然，这不属于 space-vim 的问题，你应该排查 django 或者 shell 相关的问题。
