### ISSUE TITLE
Problem with ncm2_tmux, constant errors on autocomplete

### ISSUE THREAD

**Issue by rafaponieman** [liuchengxu/space-vim#347]
### Environment

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [x] NeoVim

**Put the contents of `:version` below:**

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORT
IFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-protot
ypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mz
R4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovi
m-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### Problem Description

Getting an error with the latest version while having ncm2_tmux@yarp enabled by default. Disabling it (by exclusion of ncm2/ncm2-tmux) fixes the problem.

[ncm2_tmux@yarp] error caught in notification handler 'on_complete [{'filepath': '/home/rafa/www/espaciopla/web/espaciopla/models.py', 'typed': '    date', 'scope_match': '', 'startccol': 5, 'scope_level': 1, '
word_pattern': '(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\=\\+\\[\\{\\]\\}\\\\\\|\\;\\:\\\'\\"\\,\\.\\<\\>\\/\\?\\s]+)', 'time': 1532909776.5298116, 'lnum': 24, 'bufnr': 12, 'changedtick': 
1120, 'manual': 0, 'base': 'date', 'ccol': 9, 'filetype': 'python', 'curpos': [0, 24, 9, 0, 9], 'tick': [[0, 24, 9], 0], 'early_cache': False, 'context_id': 721, 'scope': 'python', 'matcher': {'name': 'abbrfuzz
y'}, 'source': {'subscope_enable': 0, 'early_cache': 0, 'name': 'tmux', 'priority': 4, 'enable': 1, 'on_warmup': 'ncm2_tmux#on_warmup', 'ready': 1, 'mark': 'T', 'auto_popup': 1, 'on_complete': 'ncm2_tmux#on_com
plete', 'on_completed': 'ncm2_tmux#on_completed'}, 'bcol': 9, 'match_end': 4}]'

Thank you!!

**Comment by liuchengxu** [comment]
Have you tried upgrading your neovim to the latest, i.e., 0.3.1? If the problem persists, you might want to file an issue in [ncm2-tmux](https://github.com/ncm2/ncm2-tmux). I'm not an expert on *fixing* this issue. @roxma could help here :).

**Comment by roxma** [comment]
The exception message doesn't seem to be complete.

What's the result of `:messages`?

Possibly related to https://github.com/ncm2/ncm2-tmux/issues/2

**Comment by roxma** [comment]
I have pushed an update. Please test the latest ncm2-tmux

**Comment by rafaponieman** [comment]
I'm sorry I didn't answer in time. I updated space-vim, all plugins and the jedi python package in my Virtualenv, and the first problem was fixed, I then installed tmux and that solved a similar error message that I got right after. Thanks a lot for your help!
