### ISSUE TITLE
这个bug怎么没人提？

### ISSUE THREAD

**Issue by if2012** [liuchengxu/space-vim#348]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
- Vim:
    - [x] Terminal Vim

**Put the contents of `:version` below:**

```

```

### Problem Description

关于插件signature，如果一个文件打过标签，不管你有没有清除标签，下次进文件再打标签，必出下面的错误：

![signature_bug](https://user-images.githubusercontent.com/2003879/43499503-62f02124-957e-11e8-9e36-785a92ac730b.jpg)
初步判断为延迟导致的。关掉延迟就没有问题。

**Comment by liuchengxu** [comment]
等插件加载完毕，也就是 1s 的时间，看到之前打的 mark 以后再 mark 就没问题。

至于其他更好既能 defer loading 又能避免这个问题的方案，欢迎 PR。

**Comment by if2012** [comment]
@liuchengxu 要五六秒以上。

**Comment by liuchengxu** [comment]
如果确实觉得不可接受的话，从 space-vim 的角度，可以直接在 `UserInit()` 添加插件直接启动：

```vim
function! UserInit()
    Plug 'kshenoy/vim-signature'
endfunction
```

从 vim-signaure 的角度，可能就需要再 cover 一些 case 而已，不过我没那么多时间去研究了。有兴趣的话，你可以研究一下给 vim-signature 提 PR 解决。

**Comment by if2012** [comment]
@liuchengxu 我也是站在space-vim的角度，仅仅是提出发现的bug以供你们参考。至于提此类pr尚觉能力不行。
