### ISSUE TITLE
start vim report autocmd error

### ISSUE THREAD

**Issue by steinliber** [liuchengxu/space-vim#352]
### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [x] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**
IM - Vi IMproved 8.1 (2018 May 17, compiled May 18 2018 13:18:41)
macOS version
Included patches: 1
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               -mouse_sysmouse    +scrollbind        +virtualedit
+arabic            +dialog_con        +jumplist          +mouse_urxvt       +signs             +visual
+autocmd           +diff              +keymap            +mouse_xterm       +smartindent       +visualextra
-autoservername    +digraphs          +lambda            +multi_byte        +startuptime       +viminfo
-balloon_eval      -dnd               +langmap           +multi_lang        +statusline        +vreplace
+balloon_eval_term -ebcdic            +libcall           -mzscheme          -sun_workshop      +wildignore
-browse            +emacs_tags        +linebreak         +netbeans_intg     +syntax            +wildmenu
++builtin_terms    +eval              +lispindent        +num64             +tag_binary        +windows
+byte_offset       +ex_extra          +listcmds          +packages          +tag_old_static    +writebackup
+channel           +extra_search      +localmap          +path_extra        -tag_any_white     -X11
+cindent           +farsi             -lua               +perl              -tcl               -xfontset
-clientserver      +file_in_path      +menu              +persistent_undo   +termguicolors     -xim
+clipboard         +find_in_path      +mksession         +postscript        +terminal          -xpm
+cmdline_compl     +float             +modify_fname      +printer           +terminfo          -xsmp
+cmdline_hist      +folding           +mouse             +profile           +termresponse      -xterm_clipboard
+cmdline_info      -footer            -mouseshape        -python            +textobjects       -xterm_save
+comments          +fork()            +mouse_dec         +python3           +timers
+conceal           -gettext           -mouse_gpm         +quickfix          +title
+cryptv            -hangul_input      -mouse_jsbterm     +reltime           -toolbar
+cscope            +iconv             +mouse_netterm     +rightleft         +user_commands
+cursorbind        +insert_expand     +mouse_sgr         +ruby              +vertsplit
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SO
URCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/u
sr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=1
0.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2/darwin-thread-multi-2
level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/confi
g-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

```

### Problem Description

I update vim to newest version, but every time i start vim, it report error below:

```
  Vim(autocmd):E216: No such group or event: <nomodeline> User SpacevimAfterUserConfig call s:after_user_config()
```

**Comment by liuchengxu** [comment]
Sorry for the trouble, should be fixed now.
