### ISSUE TITLE
Makefile using tabs

### ISSUE THREAD

**Issue by mekanix** [liuchengxu/space-vim#353]
### Environment
- OS:
    - [] Linux
    - [] macOS
    - [] Windows
    - [x] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [x] NeoVim

**Put the contents of `:version` below:**

Breaks on :version, but that's a different issue. As I use HardenedBSD which is FreeBSD distro, some apps break on enforcing extra security rules on them (to be investigated).

### Problem Description
Is there a way to toggle something like this:
```
autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
```
It works on make files, but opening any other file type after Makefile retains these settings (I guess it's expected). As make is sensitive about tabs vs spaces, there is a need for this to be active for anyone editing any Makefile, I would say. What is the best way to handle the situation "open Makefile with tabstop=8, than open any other file and use spacevim default"?

**Comment by liuchengxu** [comment]
`setlocal` is what you're looking for:

```vim
autocmd FileType make setlocal tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
```

**Comment by mekanix** [comment]
Fantastic. Do you think it could become part of default configuration?

**Comment by liuchengxu** [comment]
Hmm, I don't know which is more conventional: `tabstop=8` or `tabstop=4`. I saw some projects use `tab_width = 4` in their `.editorconfig`.
