### ISSUE TITLE
Could not preview markdown if chrome is not installed in the default location

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/space-vim#355]
Thanks for this great project!

Recently I enabled the markdown layer and tried to preview a markdown file using `PrevimOpen`. An error occurred say that:

```vim
[vimproc] vimproc#get_command_name: File "google-chrome" is not found.
``` 

According to the homepage of [previm](https://github.com/previm/previm/blob/master/README-en.mkd), I should be able to change the browser using `g:previm_open_cmd`. However, by looking at this, I found that that command is hard coded which always using Google Chrome with default location.

https://github.com/liuchengxu/space-vim/blob/b983e3432c49ec1cd3d345a987f6755c533da0a9/core/autoload/spacevim/autocmd/markdown.vim#L3

I did not install Chrome but Chromium. Is there any way I can change that?

Thanks!

**Comment by liuchengxu** [comment]
Thanks for the report. Now you  should be able to change the browser by adding `let g:previm_open_cmd = 'your browser'` in `UserConfig()`.

**Comment by hongyuanjia** [comment]
I can confirm that it has been fixed. Thanks!
