### ISSUE TITLE
space-vim changed my iterm2 cursorline shape from line to bar

### ISSUE THREAD

**Issue by kelvinji2009** [liuchengxu/space-vim#356]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [*] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [*] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
space-vim 0.8.0
```

### Problem Description

`space-vim` changed my iterm2 cursorline shape from `line` to `bar`

**Comment by liuchengxu** [comment]
For all I know, the cursor shape in iTerm2 is configured at https://github.com/liuchengxu/vim-better-default/blob/d6239473fa22429564efdd72d7e4407c6b744718/plugin/default.vim#L103-L123, i.e., block in normal mode, vertical bar in insert mode, underline in replace mode.

**Comment by liuchengxu** [comment]
If you don't like these changes, set these options to the default:

```vim
function! UserConfig()
    set t_SI&
    set t_SR&
    set t_EI&
endfunction
```
