### ISSUE TITLE
Multiple version of Python and OS provided packages

### ISSUE THREAD

**Issue by mekanix** [liuchengxu/space-vim#359]
### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [] macOS
    - [] Windows
    - [x] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [x] NeoVim

### Problem Description

On FreeBSD there are multiple packages for the same pypi library. One example is py27-yapf and py36-yapf. As py27-yapf is default which installs `yapf` binary and I would, for example, like to use py36-yapf which installs `yapf-3.6` binary, I'd like to know if there's a way to specify executable to be used? For example, I use `let g:gutentags_ctags_executable = "uctags"` for ctag config, but I was not able to find something similar for yapf, isort and flake8. If there's no such option, I would be glad to send PR if it's possible, but I would need some guidance.

For the quick workaround, I could install those packages in virtualenv and start my vim/neovim with that virtualenv activated, but it's ugly in the long run. Thank you!

**Comment by liuchengxu** [comment]
Now you should be able to use `yapf-3.6` instead of the default `yapf`:

```vim
let g:spacevim_python_fmt = 'yapf-3.6'
```

**Comment by liuchengxu** [comment]
Should be fixed now. `yapf-3.6` is not general, so ALE doesn't support it by default.

**Comment by mekanix** [comment]
Works like a charm with `, =`, but gives the same error on `:w`.

**Comment by liuchengxu** [comment]
So `ALEFix` is still triggered when you save the file. The workaround is to remove `yapf-3.6` from the fixers:

```vim
autocmd FileType python let b:ale_fixers = ['remove_trailing_lines', 'isort']
```

Then you have to press `, =` to apply `yapf-3.6` manually.

Alternatively, if you never use py27-yapf, you could even override the default py27-yapf by adding an alias `yapf` for `yapf-3.6` in your .bashrc/.zshrc.
