### ISSUE TITLE
Python questions

### ISSUE THREAD

**Issue by mekanix** [liuchengxu/space-vim#362]
I'm wondering why is there `let g:pymode_rope = 0`? If I remember correctly, rope can remove imports that are not really used. If there are any problems with rope, can we use something else to automatically remove extra imports?

I remember spacemacs having "go to next error", but I can't find it in layer config. Is there a key binding for that?

I vaguely remember there's a vim plugin for python which looks like NERDTree, but is on the right side and displays current values of variables. Am I right that such plugin exists, and if yes, can we include it?

Suggestion for people using FreeBSD or any other OS that ships with `yapf-3.6` as a binary instead `yapf`. I ended up putting ~/.local/bin to my PATH and adding symlinks from that dir to /usr/local/bin enteries, so for example I have `~/.local/bin/yapf -> /usr/local/bin/yapf-3.6`. While Python2 is not EOL I think that's the easiest way to have space-vim working properly with yapf/isort/flake8 while not touching the system.

**Comment by liuchengxu** [comment]
I actually never used the functionalities of pymode except the enhanced syntax highlight. To my knowledge [autoflake](https://github.com/myint/autoflake) supports removing unused imports. You can apply it on current python file in a simple way: `:!autoflake --in-place --remove-unused-variables %`. I'll polish this point if I get some time, no guarantees though. 

What's more, you can override any settings in space-vim if they are not suitable for you.

Next and previous error:

https://github.com/liuchengxu/space-vim/blob/6904b08c7f5f736395e99a2e9355d7c05a52a334/layers/%2Bcheckers/syntax-checking/config.vim#L15-L16

https://github.com/liuchengxu/space-vim/commit/8ab01574e547b760de686a60ae37d5c16b9ebce4#L64-L68

**Comment by mekanix** [comment]
This is great! I feel like I'm re-learning Python development :o) Thank you!

Is there a way to make space-vim not break too long line while typing, because yapf will do it on save or using `, =`?

**Comment by liuchengxu** [comment]
I don't think it will break too long lines when you're typing.

**Comment by liuchengxu** [comment]
autoflake support has been added, try it via `, a` or remap it to you preferred keymapping:

```vim
nnoremap <buffer> <LocalLeader>a :<C-U>call spacevim#lang#python#autoflake()<CR>
```

- Use `g:spacevim_python_autoflake_executable` to specify the path of
autoflake, by default it's `autoflake`.

- Use `g:spacevim_python_autoflake_option` to specify option of
autoflake, by default it's `--in-place --remove-all-unused-imports  --remove-unused-variables`.
