### ISSUE TITLE
fzf layer should not modify environment variable $LANG

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/space-vim#364]
In [this code](https://github.com/liuchengxu/space-vim/blob/0a4ff84aeb166bd9468e89268aa04bbf190746c3/layers/%2Btools/fzf/config.vim#L11), the fzf layer modifies the environment variable `$LANG` which will cause troubles to programs that read the `$LANG` environment variable to determine the locale settings. As `"en_US"` is not globally recognized as a valid locale name, some programs may fallback the locale settings to all C-like.

One example is [R](https://www.r-project.org/).

![startup](https://user-images.githubusercontent.com/20545387/46132939-f73f1680-c271-11e8-8cdd-f8851310972a.png)

Is there any strong reason that `$LANG` variable should be hard coded in the fzf layer?

**Comment by liuchengxu** [comment]
That was introduced from #61 . What's your use case? I barely use R with vim.

**Comment by hongyuanjia** [comment]
I use vim most for R programming with vim plugin [Nvim-R](https://github.com/jalvesaq/Nvim-R) which uses environment variable `LC_ALL`, `LC_MESSAGES` and `LANG` to determine the locale, which complies with [the documentation of R](https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Localization-of-messages), i.e.

> The preferred language for messages is by default taken from the locale. This can be overridden first by the setting of the environment variable LANGUAGE and then by the environment variables LC_ALL, LC_MESSAGES and LANG.

As from [#61](https://github.com/liuchengxu/space-vim/issues/61), the issue only existed in Neovim. I would suggest to only set `LANG` only for Neovim or set it to `en_US.UTF-8` which is a more common used locale.

BTW, if I change `let $LANG = "en_US"` to `let $LANG = "en_US.UTF-8", the warning of R goes away. But I am not sure if this also works for Neovim. It would be great if you could test that.

**Comment by hongyuanjia** [comment]
Thanks for testing. Right now the issue goes away👍👍👍
