### ISSUE TITLE
升级后，出现各种问题，基本不可用了。

### ISSUE THREAD

**Issue by quakex** [liuchengxu/space-vim#37]
1. 默认的各种快捷键都不能用。
2. airline status 栏不显示。

**Comment by wsdjeg** [comment]
@quakex 是因为新加的插件么， 我也在考虑要不要再 [SpaceVim](https://github.com/SpaceVim) 里面加呢。

而且问题是你怎么升级的呢？

**Comment by quakex** [comment]
git pull 升级，回到之前的版本，一切恢复正常。感觉还是很不稳定啊。

**Comment by wsdjeg** [comment]
@quakex space-vim 自带插件应该不多吧，应该稳定的， 如果不怕折腾，可以用我的试试，不过插件有点多，190左右，目前是这么多，后期可能有所更改。

https://github.com/SpaceVim/SpaceVim  如果熟悉vim的话，可以试试。

**Comment by liuchengxu** [comment]
@quakex 抱歉，因为都是人工测试，而且都是一些小的改进，一般我踩完坑，本地没问题就更新了😂。有没有什么更详细的症状？可以排除法试一下，看能否具体到哪一个 Layer 的问题。
@wsdjeg 我建议 SpaceVim 可以适当的做做减法，让它条理更清晰一些，目前的插件真的已经不少了。。。

**Comment by wsdjeg** [comment]
@liuchengxu 还不够多的，很多语言还没有覆盖到，当然后期默认肯定不会这么多插件。

**Comment by liuchengxu** [comment]
@quakex 我刚刚在本地测试依旧没有发现什么问题 ，airline 也是正常的，你可以再测试一下吗？有没有可能会更新时网络出现问题？

**Comment by liuchengxu** [comment]
@quakex 你有没有设置 `spacevim_leader` 与 `spacevim_localleader` ？快捷键不能用有可能是这个原因..... #38 ， so sorry....

**Comment by liuchengxu** [comment]
如果恢复正常就先关闭这个 issue 了。
