### ISSUE TITLE
The Windows version is not available

### ISSUE THREAD

**Issue by limbo-envoy** [liuchengxu/space-vim#370]
The Windows version is not availa:echomsg l:msg

[space-vim] .spacevim does not exist! Exiting...

处理 function spacevim#bootstrap[1]..spacevim#begin[7]..<SNR>2_c
heck_dot_spacevim 时发生错误:

第    8 行:

E168: 在脚本文件外使用了 :finishble

**Comment by liuchengxu** [comment]
As the error message said, you should create `.spacevim` in your home directory. Please refer to  https://github.com/liuchengxu/space-vim/wiki/install#windows for more info.
