### ISSUE TITLE
Extra, unexpected output and prompt for Enter when using vim-metarw-gdrive

### ISSUE THREAD

**Issue by motevets** [liuchengxu/space-vim#372]
### Environment
- OS:
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] FreeBSD
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] NeoVim

**Put the contents of `:version` below:**

```
:version                                                                                                  
NVIM v0.3.1-1-g489d32f2b                                                                                  
Build type: RelWithDebInfo                                                                                
LuaJIT 2.0.5                                                                                              
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -O
g -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-
strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MS
GPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -
I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/u
sr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/trav
is/build/neovim/bot-ci/build/neovim/build/include                                                         
Compiled by travis@travis-job-ecc960f4-8e53-44e6-a8e8-9587ed80f885                                        
                                                                                                          
Features: +acl +iconv +jemalloc +tui                                                                      
See ":help feature-compile"                                                                               
                                                                                                          
   system vimrc file: "$VIM/sysinit.vim"                                                                  
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"    
                                                                                                          
Run :checkhealth for more info  
```

```
:echo g:spacevim_layers
[]
```

### Problem Description

I use a plugin called [vim-metarw-gdrive](https://github.com/mattn/vim-metarw-gdrive).  With it the expected behavior is that, I can view all of my files on Google Drive by running `:e gdrive:`, and then I can select one to open/edit it (similar to netrw or NERDtree).

The issue I'm seeing is that when I run `:e gdrive:` or when I select a file in the subsequent window, I see some extra, unexpected input:
```
1 more line
1 more line
1 more line
1 line less
Press ENTER or type command to continue
```
and I have to hit enter to continue (which I don't normally have to do.) The plugin otherwise functions normally.  I have confirmed that this problem is not present with an otherwise vanilla neovim config (without space-vim).  I additionally confirmed that the issue is not with eleline.vim by adding it along side vim-metarw-gdrive in an otherwise vanilla neovim config:
```
call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/eleline.vim'
Plug 'mattn/vim-metarw-gdrive'
" dependencies for vim-metarw-gdrive
Plug 'kana/vim-metarw'
Plug 'mattn/webapi-vim'

set laststatus=2

call plug#end()
```

![screenshot 2018-11-25 at 5 05 28 pm](https://user-images.githubusercontent.com/777773/48987519-95b1f180-f0d4-11e8-98cd-ec60d9fa5a19.png)

**Comment by liuchengxu** [comment]
Well, can you provide a minimal `.spacevim` instead of a vanilla vim/neovim config to reproduce?

**Comment by motevets** [comment]
Yes, sorry I should have included my `.spacevim` which reproduces the problem.  Here it is:
```
let g:spacevim_plug_home = '~/.vim/plugged'
let g:spacevim_layers = []

function! UserInit()
  Plug 'mattn/vim-metarw-gdrive'
  Plug 'kana/vim-metarw'
  Plug 'mattn/webapi-vim'
endfunction

function! UserConfig()

endfunction
```

Just to confirm, the problem **does not** reproduce when using the vanilla `init.vim` I provided above, so far it's only reproduced when using space-vim.

**Comment by liuchengxu** [comment]
The `.spacevim` you provide is essentially same as the previous `init.vim`. You don't enable any layers in space-vim(`let g:spacevim_layers = []`), so it's not a problem of space-vim itself, which is a mere vim configuration actually.

I think you should report and provide the vanilla `init.vim` in https://github.com/mattn/vim-metarw-gdrive .

**Comment by motevets** [comment]
The vanilla `init.vim` (without space-vim) does not have the problem, so I think the problem must be somewhere is the space-vim setup, but I'm not sure where to look.

**Comment by liuchengxu** [comment]
Ok, then could you test if it can work with `liuchengxu/vim-better-default`?

```vim
call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-better-default'
Plug 'mattn/vim-metarw-gdrive'
" dependencies for vim-metarw-gdrive
Plug 'kana/vim-metarw'
Plug 'mattn/webapi-vim'

set laststatus=2

call plug#end()
```

**Comment by motevets** [comment]
Using that config **did reproduce** the problem.

**Comment by liuchengxu** [comment]
Good, then we should focus on https://github.com/liuchengxu/vim-better-default.

If so, chances are great that one of the lines https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L16-L186 leads to this problem. Could you narrow it down?

**Comment by motevets** [comment]
This is the line: https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L63. Commenting it out fixes the problem. It's easy enough for me to override it in my `.spacevim` file. Thanks for the help in finding it.
