### ISSUE TITLE
NERDTree使用不了

### ISSUE THREAD

**Issue by Lyndon1994** [liuchengxu/space-vim#373]
### Environment

- OS:
    - [*] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [*] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
VIM - Vi IMproved 8.0
space-vim 0.8.0 (默认配置)
```

无法使用 `SPC f t`  
报错： [which-key] fail to execute, no such mapping.

**Comment by liuchengxu** [comment]
你要启用 `file-manager` layer.

```vim
let g:spacevim_layers  += ['file-manager']
```
