### ISSUE TITLE
Problem with `space ff` to open file

### ISSUE THREAD

**Issue by julien-h** [liuchengxu/space-vim#375]
### Environment

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 01 2018 17:32:49)                                                                      Included patches: 1-320
```

### Problem Description

I just installed spacevim using the linux script. When I type `<space> ff` to open a file, the suggestions are wrong. See screenshot.

![screenshot 66](https://user-images.githubusercontent.com/11776282/49689872-04a53680-fb28-11e8-95ad-f340eea9f7e0.png)

**Comment by liuchengxu** [comment]
works for me.

![image](https://user-images.githubusercontent.com/8850248/49692758-4f14ca80-fb9d-11e8-904a-c4df552295b3.png)

`SPC f f` is nothing but a wrap for `:Files ~` from [fzf.vim](https://github.com/junegunn/fzf.vim). You can directly call the commands from fzf.vim to see if they could work as expected.
