### ISSUE TITLE
git pull master分支，<space>1-9的buffer切换不工作

### ISSUE THREAD

**Issue by co1inlee** [liuchengxu/space-vim#38]
今天git pull master分支，用切换buffer时，不能正常切换，这次改动有点大，感觉很不稳定呢！取消leander key的两行注释，space不能工作，注释后能工作
```shell
let g:spacevim_leader = "<\Space>"
let g:spacevim_localleader = ','
```

**Comment by liuchengxu** [comment]
真是抱歉！的确有变化，可以看这里 #35 ，因为默认的 statusline 中我加入了 window number 的信息。具体改动的原因，我会在用电脑的时候详细解释，手机回复好尴尬。。。

**Comment by co1inlee** [comment]
@liuchengxu  好的哈，等有空了，我们再沟通下，这次改动有点太大了，连spacevim文件个Layers都独立出来了。刚开始还不知道呢

**Comment by liuchengxu** [comment]
@co1inlee `SPC [1-9]` 从原来切换到相应数字编号的 buffer 到 切换到相应编号的 window, 主要是考虑这样一个多 window 的场景：

<img width="857" alt="2017-01-06 5 41 46" src="https://cloud.githubusercontent.com/assets/8850248/21714024/e1d1bd22-d437-11e6-9dd7-af203f75f55a.png">

当处于 window 1 时，我们想要切换到 window 2 那个文件里进行操作, 这样的动作当然是简单快捷才好，一个空格键加数字看起来不错。

圆圈数字代表 buffer 编号，紧接着的代表 window 编号，知道了 window 编号在这种多 window 的场景下进行切换就比较方便了。否则像之前那样，空格键加数字是**在当前的 window 打开对应编号的 buffer**, 这可能并不是我们想要的。

而像之前 `SPC [1-9]` 切换到对应 buffer, 主要适用于开启 airline :

<img width="242" alt="2017-01-06 5 52 50" src="https://cloud.githubusercontent.com/assets/8850248/21714254/fe0e7308-d438-11e6-884c-eabdaa9c45be.png">

这种场景是多个 buffer, 但是只有一个 window。 如果开启 airline, 那么可以在 `UserConfig()` 中进行覆盖使得 `SPC [1-9]` 依旧是切换到对应 buffer. 可以先判断一下，要是开启了 airline Layer, 就还是改回原来的样子。

```vim
if LayerLoaded('airline')
    " <Leader>[1-9] move to buffer [1-9]
    for i in range(1, 9)
        "   就是 nnoremap <Leader>1 :b1<CR> 而已
        execute 'nnoremap <Leader>' . i . ' :b' . i . '<CR>'
    endfor
endif
```

这个更新增加了 window number 的信息，虽然改变了原有 `SPC [1-9]` 的键位，但是通过在 `UserConfig()` 中进行覆盖应该也能不受影响，应当还是有用的（为了找 window 的 unicode symbol 我好找了一会儿呢 😂 ）。

新增了 `Layers()`， 主要是为了几个部分能更明朗一些：

- `Layers()` 中可以启用 space-vim 已有的 Layer，也可以排除部分插件， `Layer` 与 `Exclude` 命令在这里是有效的。 
- `UserInit()` 中单独放置自己私有的一些插件 。如果有一些插件用着不错可以考虑单独成为一个 Layer, 也是方便自己整理与分享。
- `UserConfig()` 放置个性化配置信息对已有设置进行覆盖。

本质上，有没有 `Layers()` 都是一样的，可以随便放，但是为了少折腾，还是遵循一些原则比较好整理 😃 。 

关于那两行注释的问题，的确有 😭  ！ 我还在找是什么回事...， so sad

**Comment by liuchengxu** [comment]
@co1inlee 如果不注释掉这两行，空格键好像表现的跟 `L` 一样 (右移)，但是所有的键位映射是正常的（ 可通过 `Maps` 或 `SPC ?` 查看），不解....

**Comment by quakex** [comment]
这两行在哪个文件？？

**Comment by liuchengxu** [comment]
@co1inlee https://github.com/liuchengxu/space-vim/blob/master/core/core_config.vim#L299-L309

**Comment by liuchengxu** [comment]
@quakex @co1inlee 好像不要设置成 `"\<Space>"` 就还是正常的，比如:

```vim
let g:spacevim_leader = '-'
```

**Comment by co1inlee** [comment]
不好意思， 周末没带电脑。没有及时回复. 如果需要使用默认的leader key还是注释掉吧，不想太折腾！ 等有空了再研究下，如果没其他的问题，可以先关掉这个issue

**Comment by liuchengxu** [comment]
@co1inlee 那就先关闭了，因为其他的 vim 配置也都是这么做的，所以关于那两行注释的问题有可能是其他的锅.....
