### ISSUE TITLE
Mouse freezes

### ISSUE THREAD

**Issue by YaroslavTER** [liuchengxu/space-vim#381]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [+] Linux (Mint)
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [+] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
1.1.0
```

### Problem Description

For the first time, I didn't understand why but for the second it was frozen because I paste already copied text. Mouse disappears from the monitor but you can see it if all windows are minimized.

**Comment by liuchengxu** [comment]
Can you post your `~/.spacevim`? Does this issue exist in the vanilla vim, i.e., start vim without any config via `vim -u NONE`?

**Comment by YaroslavTER** [comment]
Oh, I'm sorry. It's my fault. It was just an input mode in vanilla Vim.
