### ISSUE TITLE
Why private is a single layer?

### ISSUE THREAD

**Issue by fno2010** [liuchengxu/space-vim#39]
I have been using spacemacs for a long time. And I often add many third-party layers in `private` directory. I think it is very useful, because I can decide which private layers can be loaded or not. But I found in current implementation of `space-vim`, the `private` is just a single layer. Is there any special thought or design philosophy for this? If not, I can help to change `private` to support multiple layers.

Btw. I really like this project. Vim is faster than emacs. And now I can op vim more efficiently. You are doing a great job!

**Comment by liuchengxu** [comment]
To be honest, since I'm currently a spacemacs user, not a spacemacs hacker (yet 🙈 ). I didn't take this situation into account in the beginning. 

I very much agree with your idea. Please open up a PR, thanks!
