### ISSUE TITLE
Searching does not work in fzf buffers

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/space-vim#397]
### Environment

- OS:
    - [x] Linux
    - [] macOS
    - [x] Windows
    - [] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [x] NeoVim

#### `:version`

```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.5/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Problem Description

In current version, `<Space>bb` opens a different view of buffers and searching does not work correctly. Input is treated as the file size column, but not buffer name. This may be introduced in 7337c21cc2afdd2fd8608eebc21b48bccb3ec59c. Searching works in `:Buffers`.

**Comment by liuchengxu** [comment]
Thanks for the report, should be fixed now.

**Comment by hongyuanjia** [comment]
Thanks for the quick response! I can confirm it has been fixed now.
