### ISSUE TITLE
vim在md格式中，无法弹出自动补齐提示

### ISSUE THREAD

**Issue by huos3203** [liuchengxu/space-vim#400]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [x] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
version                                                                                            
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 24 2019 00:25:24)                                  
macOS version                                                                                       
Included patches: 1-800                                                                             
Compiled by Homebrew                                                                                
Huge version without GUI.  Features included (+) or not (-):                                        
   system vimrc file: "$VIM/vimrc"                                                                  
     user vimrc file: "$HOME/.vimrc"                                                                
 2nd user vimrc file: "~/.vim/vimrc"                                                                
      user exrc file: "$HOME/.exrc"                                                                 
-- More --                           
```

### Problem Description
在`.md`格式下，YCM没有提示。
之后，在space-vim/layers/+tools/ycmd/config.vim添加全局配置
1. 白名单
```
 let g:ycm_filetype_whitelist = {'*': 1}
```
2. 黑明单
```
let g:ycm_filetype_blacklist = {
      \ 'tagbar': 1,
      \ 'notes': 1,
      \ 'netrw': 1,
      \ 'unite': 1,
      \ 'text': 1,
      \ 'vimwiki': 1,
      \ 'pandoc': 1,
      \ 'infolog': 1,
      \ 'mail': 1
      \}
```
问题仍然存在。
![IMG_1037](https://user-images.githubusercontent.com/4022953/59571590-03595580-90d9-11e9-9618-7e339b12ff78.jpeg)

**Comment by liuchengxu** [comment]
Try `Layer 'lsp'` and set `let g:spacevim_lsp_engine = 'coc'`. I used to several tricks in `ycmd` layer to improve the startup of YCM, which are needless in `lsp` layer.

**Comment by huos3203** [comment]
> Try `Layer 'lsp'` and set `let g:spacevim_lsp_engine = 'coc'`. I used to use several tricks in `ycmd` layer to improve the startup of YCM, which are needless in `lsp` layer.
```
[LC] LanguageClient caught exception: 'Vim(return):E906: not an open channel'
```
