### ISSUE TITLE
安装lsp之后,提示错误哦

### ISSUE THREAD

**Issue by huos3203** [liuchengxu/space-vim#401]
> Try `Layer 'lsp'` and set `let g:spacevim_lsp_engine = 'coc'`. I used to use several tricks in `ycmd` layer to improve the startup of YCM, which are needless in `lsp` layer.

i install `lsp` and set `let g:spacevim_lsp_engine = 'coc'`,  print this log  when `vi test.md` 
```
[LC] LanguageClient caught exception: 'Vim(return):E906: not an open channel'
```

_Originally posted by @huos3203 in https://github.com/liuchengxu/space-vim/issues/400#issuecomment-502559624_

**Comment by liuchengxu** [comment]
It's obviously that you fail to set the space-vim lsp engine to `coc`, you are using the default one `lcn`. 

You should read the README more carefully to learn how space-vim works and how to customize it.

**Comment by huos3203** [comment]
> It's obviously that you fail to set the space-vim lsp engine to `coc`, you are using the default one `lcn`.
> 
> You should read the README more carefully to learn how space-vim works and how to customize it.

I have seted that`let g:spacevim_lsp_engine = 'coc'` in `.spacevim`file. 
I want to know where to set it up successfully. thanks

**Comment by huos3203** [comment]
> > It's obviously that you fail to set the space-vim lsp engine to `coc`, you are using the default one `lcn`.
> > You should read the README more carefully to learn how space-vim works and how to customize it.
> 
> I have seted that`let g:spacevim_lsp_engine = 'coc'` at `function! UserConfig()` in `.spacevim`file.
> I want to know where to set it up successfully. thanks
> 
> @liuchengxu help me!

on OSX
```
:echo g:spacevim_lsp_engine
> coc
```
在OSX安装成功了. `lsp`并没有修复这个问题.如图
![IMG_1037](https://user-images.githubusercontent.com/4022953/59571590-03595580-90d9-11e9-9618-7e339b12ff78.jpeg)

**Comment by liuchengxu** [comment]
I can't reproduce.

![image](https://user-images.githubusercontent.com/8850248/59607125-52d56b00-9145-11e9-99af-30f227cb6d6b.png)

**Comment by huos3203** [comment]
> I can't reproduce.
> 
> ![image](https://user-images.githubusercontent.com/8850248/59607125-52d56b00-9145-11e9-99af-30f227cb6d6b.png)

实现提示的操作：
1. 第一步
```
$ vim test.md
```
2. 第二步：`spc+shift+r `
3. 第三步：再次输入，会提示补全框
vim启动之后，再次强制加载.vimrc `spc+shift+r `，再次输入内容，会启动提示补齐框

最终卸载了`lsp`，再次尝试以上三步，也可实现提示补全，反复测试，似乎与`lsp`无关。

想问下，如何设置自动加载.vimrc，不用每次启动后`spc+shift+r`来加载?

**Comment by liuchengxu** [comment]
本来就不用。

**Comment by huos3203** [comment]
> 本来就不用。升级到最新的 space-vim，然后把你的 `.spacevim` 贴出来。

嗯，昨天先升级了space-vim
```
Comment the following line if you don't want Vim and NeoVim to share the
" same plugin download directory.
let g:spacevim_plug_home = '~/.vim/plugged'

" Uncomment the following line to override the leader key. The default value is space key "<\Space>".
" let g:spacevim_leader = "<\Space>"

" Uncomment the following line to override the local leader key. The default value is comma ','.
" let g:spacevim_localleader = ','

" Enable the existing layers in space-vim.
" Refer to https://github.com/liuchengxu/space-vim/blob/master/layers/LAYERS.md for all available layers.
let g:spacevim_layers = [
      \ 'fzf', 'unite', 'better-defaults','which-key','text-align','better-motion',
      \ 'chinese',
      \ 'github','git','airline',
      "\ 'lsp',
      \ 'markdown',
      \ 'file-manager',
      \ 'syntax-checking',
      \ 'python','javascript','ruby','docker',
      \ 'ycmd','code-snippets','editing','formatting','programming',
      \ ]
"\ 'lsp',安装提n示错误
"\ 'file-manager', 定制的nerdtree目录树
"\ 'syntax-checking',  支持swifelint，实现语法检测纠正机制"
"Layer 'ycmd'         \"语法自动补齐

" Uncomment the following line if your terminal(-emulator) supports true colors.
" let g:spacevim_enable_true_color = 1

" Uncomment the following if you have some nerd font installed.
" let g:spacevim_nerd_fonts = 1

" If you want to have more control over the layer, try using Layer command.
" if g:spacevim.gui
"   Layer 'airline'
" endif

" Manage your own plugins.
" Refer to https://github.com/junegunn/vim-plug for more detials.
function! UserInit()

    " Add plugin via Plug command.
    "禁止vim-better-default 的键位映射部分，可以将其设置为0.
    let g:vim_better_default_key_mapping = 1
    " ---------安装私有插件------
    Plug 'chemzqm/wxapp.vim'
    Plug 'junegunn/seoul256.vim'
    Plug 'huos3203/plantuml-syntax'  "plantuml语法高亮 Plug 'aklt/plantuml-syntax'
    Plug 'tyru/open-browser.vim'
    Plug 'iamcco/markdown-preview.vim'
    Plug 'weirongxu/plantuml-previewer.vim' "在线工具：http://sujoyu.github.io/plantuml-previewer/
    "模板
    Plug 'huos3203/vim-template'  ".swift/.h/m/.md/.uml 文件模版
    Plug 'shougo/unite-outline' "源码方法结构
    Plug 'ryotakato/unite-outline-objc'

    "语法结构
    Plug 'shougo/unite-outline'
    Plug 'ryotakato/unite-outline-objc'

    "swift
    Plug 'jerrymarino/SwiftPlayground.vim'
    Plug 'jerrymarino/iCompleteMe'
    Plug 'tpope/vim-pathogen'
    Plug 'vim-syntastic/syntastic'
    Plug 'keith/swift.vim'      "swiftpm + swiftlint + syntactic集成
    Plug 'keith/sourcekittendaemon.vim' "swift自动补齐提示插件,omnifunc万能不全
    "Plug 'kballard/vim-swift', {'for': 'swift'} ""语法高亮/swift命令/LLVM/在iOS模拟器上编译/运行/支持Xcode多种安装,错误Swift string interpolations do not work well with 'showmatch'
    "Plug 'toyamarinyon/vim-swift'
    "Plug 'landaire/deoplete-swift'
    "Plug 'mitsuse/autocomplete-swift'
    "xcode编译工具
    Plug 'keith/zsh-xcode-completions'
    Plug 'keith/xcconfig.vim'
    Plug 'keith/cocoapods.vim'
    Plug 'gfontenot/vim-xcode'
    Plug 'keith/sourcekittendaemon.vim'

    " React code snippets 一组为 Vim 打造的可与Facebook 的 React 库一起使用的片段
    Plug 'epilande/vim-react-snippets'
    "你自己的代码仓库 git 地址 http://blog.jobbole.com/114334/
    "Plug 'keelii/vim-snippets'
    "Plug 'sunzhongwei/vim-zhongwei-snippets'
    Plug 'huos3203/iSnippets'

    " vim-babel翻译不同版本的js，实现兼容
    Plug 'jbgutierrez/vim-babel'
    Plug 'mattn/webapi-vim'
    "提供 JSX 的语法高亮和缩进
    Plug 'mxw/vim-jsx'
    "dash文档插件
    Plug 'rizzatti/dash.vim'
    "
    Plug 'jaxbot/github-issues.vim'

endfunction

" Override the default settings from space-vim as well as adding extras
function! UserConfig()
  " If you have installed the powerline fonts and want to enable airline layer
  " let g:airline_powerline_fonts=1
  let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
  let g:ale_linters = { 'swift': ['swiftlint'] }
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = '>>'
  let g:ale_sign_warning = '--'
  " Set this. Airline will handle the rest.
  let g:airline#extensions#ale#enabled = 1
  
  "markdown自动提示
  let g:spacevim_lsp_engine = 'coc' 


  "
  let g:jsx_ext_required = 1 " Allow JSX in normal JS files
  let g:syntastic_javascript_checkers = ['eslint']
  "
  " Use gui colors in terminal if available
  function! s:enable_termgui()
    if has('termguicolors')
      set termguicolors
      if g:spacevim.tmux
        " If use vim inside tmux, see https://github.com/vim/vim/issues/993
        " set Vim-specific sequences for RGB colors
        let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
        let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
      endif
    endif
  endfunction

  " If your terminal(-emulator) supports true colors, uncomment the line below
  " call s:enable_termgui()

  " Override the default settings.
  " Uncomment the following line to disable relative number.
  " set norelativenumber

  " Adding extras.
  " Uncomment the following line If you have installed the powerline fonts.
  " It is good for airline layer.
  " let g:airline_powerline_fonts = 1
endfunction
```

**Comment by liuchengxu** [comment]
`let g:spacevim_lsp_engine = 'coc'` 放在外面，space-vim 提供的配置项都放在外面。

```vim
" Comment the following line if you don't want Vim and NeoVim to share the
" same plugin download directory.
let g:spacevim_plug_home = '~/.vim/plugged'

" Uncomment the following line to override the leader key. The default value is space key "<\Space>".
" let g:spacevim_leader = "<\Space>"

" Uncomment the following line to override the local leader key. The default value is comma ','.
" let g:spacevim_localleader = ','

" Enable the existing layers in space-vim.
" Refer to https://github.com/liuchengxu/space-vim/blob/master/layers/LAYERS.md for all available layers.
let g:spacevim_layers = [
      \ 'fzf', 'better-defaults','which-key','text-align','better-motion',
      \ 'lsp',
      \ 'markdown',
      \ 'file-manager',
      \ 'syntax-checking',
      \ 'editing','formatting','programming',
      \ ]

" ================================
let g:spacevim_lsp_engine = 'coc'
" ================================

" Uncomment the following line if your terminal(-emulator) supports true colors.
" let g:spacevim_enable_true_color = 1

" Uncomment the following if you have some nerd font installed.
" let g:spacevim_nerd_fonts = 1

" If you want to have more control over the layer, try using Layer command.
" if g:spacevim.gui
"   Layer 'airline'
" endif

" Manage your own plugins.
" Refer to https://github.com/junegunn/vim-plug for more detials.
function! UserInit()

endfunction

" Override the default settings from space-vim as well as adding extras
function! UserConfig()
  " If you have installed the powerline fonts and want to enable airline layer
  " let g:airline_powerline_fonts=1
  let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
  let g:ale_linters = { 'swift': ['swiftlint'] }
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = '>>'
  let g:ale_sign_warning = '--'
  " Set this. Airline will handle the rest.
  let g:airline#extensions#ale#enabled = 1

  " Override the default settings.
  " Uncomment the following line to disable relative number.
  " set norelativenumber

  " Adding extras.
  " Uncomment the following line If you have installed the powerline fonts.
  " It is good for airline layer.
  " let g:airline_powerline_fonts = 1
endfunction
```

**Comment by huos3203** [comment]
> > 本来就不用。升级到最新的 space-vim，然后把你的 `.spacevim` 贴出来。
> 
> 嗯，昨天先升级了space-vim
> 发现新现象，在启动vim之后，不仅要强制加载.vimrc，还需要先在YCM支持的文件中例如`test.py`，编写确保启动了补齐功能，这时再进入`test.md`中，才会提示Snippets的提示内容，否则只会提示输入的历史内容
> 
> ```yaml
> Comment the following line if you don't want Vim and NeoVim to share the
> " same plugin download directory.
> let g:spacevim_plug_home = '~/.vim/plugged'
> 
> " Uncomment the following line to override the leader key. The default value is space key "<\Space>".
> " let g:spacevim_leader = "<\Space>"
> 
> " Uncomment the following line to override the local leader key. The default value is comma ','.
> " let g:spacevim_localleader = ','
> 
> " Enable the existing layers in space-vim.
> " Refer to https://github.com/liuchengxu/space-vim/blob/master/layers/LAYERS.md for all available layers.
> let g:spacevim_layers = [
>       \ 'fzf', 'unite', 'better-defaults','which-key','text-align','better-motion',
>       \ 'chinese',
>       \ 'github','git','airline',
>       "\ 'lsp',
>       \ 'markdown',
>       \ 'file-manager',
>       \ 'syntax-checking',
>       \ 'python','javascript','ruby','docker',
>       \ 'ycmd','code-snippets','editing','formatting','programming',
>       \ ]
> "\ 'lsp',安装提n示错误
> "\ 'file-manager', 定制的nerdtree目录树
> "\ 'syntax-checking',  支持swifelint，实现语法检测纠正机制"
> "Layer 'ycmd'         \"语法自动补齐
> 
> " Uncomment the following line if your terminal(-emulator) supports true colors.
> " let g:spacevim_enable_true_color = 1
> 
> " Uncomment the following if you have some nerd font installed.
> " let g:spacevim_nerd_fonts = 1
> 
> " If you want to have more control over the layer, try using Layer command.
> " if g:spacevim.gui
> "   Layer 'airline'
> " endif
> 
> " Manage your own plugins.
> " Refer to https://github.com/junegunn/vim-plug for more detials.
> function! UserInit()
> 
>     " Add plugin via Plug command.
>     "禁止vim-better-default 的键位映射部分，可以将其设置为0.
>     let g:vim_better_default_key_mapping = 1
>     " ---------安装私有插件------
>     Plug 'chemzqm/wxapp.vim'
>     Plug 'junegunn/seoul256.vim'
>     Plug 'huos3203/plantuml-syntax'  "plantuml语法高亮 Plug 'aklt/plantuml-syntax'
>     Plug 'tyru/open-browser.vim'
>     Plug 'iamcco/markdown-preview.vim'
>     Plug 'weirongxu/plantuml-previewer.vim' "在线工具：http://sujoyu.github.io/plantuml-previewer/
>     "模板
>     Plug 'huos3203/vim-template'  ".swift/.h/m/.md/.uml 文件模版
>     Plug 'shougo/unite-outline' "源码方法结构
>     Plug 'ryotakato/unite-outline-objc'
> 
>     "语法结构
>     Plug 'shougo/unite-outline'
>     Plug 'ryotakato/unite-outline-objc'
> 
>     "swift
>     Plug 'jerrymarino/SwiftPlayground.vim'
>     Plug 'jerrymarino/iCompleteMe'
>     Plug 'tpope/vim-pathogen'
>     Plug 'vim-syntastic/syntastic'
>     Plug 'keith/swift.vim'      "swiftpm + swiftlint + syntactic集成
>     Plug 'keith/sourcekittendaemon.vim' "swift自动补齐提示插件,omnifunc万能不全
>     "Plug 'kballard/vim-swift', {'for': 'swift'} ""语法高亮/swift命令/LLVM/在iOS模拟器上编译/运行/支持Xcode多种安装,错误Swift string interpolations do not work well with 'showmatch'
>     "Plug 'toyamarinyon/vim-swift'
>     "Plug 'landaire/deoplete-swift'
>     "Plug 'mitsuse/autocomplete-swift'
>     "xcode编译工具
>     Plug 'keith/zsh-xcode-completions'
>     Plug 'keith/xcconfig.vim'
>     Plug 'keith/cocoapods.vim'
>     Plug 'gfontenot/vim-xcode'
>     Plug 'keith/sourcekittendaemon.vim'
> 
>     " React code snippets 一组为 Vim 打造的可与Facebook 的 React 库一起使用的片段
>     Plug 'epilande/vim-react-snippets'
>     "你自己的代码仓库 git 地址 http://blog.jobbole.com/114334/
>     "Plug 'keelii/vim-snippets'
>     "Plug 'sunzhongwei/vim-zhongwei-snippets'
>     Plug 'huos3203/iSnippets'
> 
>     " vim-babel翻译不同版本的js，实现兼容
>     Plug 'jbgutierrez/vim-babel'
>     Plug 'mattn/webapi-vim'
>     "提供 JSX 的语法高亮和缩进
>     Plug 'mxw/vim-jsx'
>     "dash文档插件
>     Plug 'rizzatti/dash.vim'
>     "
>     Plug 'jaxbot/github-issues.vim'
> 
> endfunction
> 
> " Override the default settings from space-vim as well as adding extras
> function! UserConfig()
>   " If you have installed the powerline fonts and want to enable airline layer
>   " let g:airline_powerline_fonts=1
>   let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
>   let g:ale_linters = { 'swift': ['swiftlint'] }
>   let g:ale_sign_column_always = 1
>   let g:ale_sign_error = '>>'
>   let g:ale_sign_warning = '--'
>   " Set this. Airline will handle the rest.
>   let g:airline#extensions#ale#enabled = 1
>   
>   "markdown自动提示
>   let g:spacevim_lsp_engine = 'coc' 
> 
> 
>   "
>   let g:jsx_ext_required = 1 " Allow JSX in normal JS files
>   let g:syntastic_javascript_checkers = ['eslint']
>   "
>   " Use gui colors in terminal if available
>   function! s:enable_termgui()
>     if has('termguicolors')
>       set termguicolors
>       if g:spacevim.tmux
>         " If use vim inside tmux, see https://github.com/vim/vim/issues/993
>         " set Vim-specific sequences for RGB colors
>         let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
>         let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
>       endif
>     endif
>   endfunction
> 
>   " If your terminal(-emulator) supports true colors, uncomment the line below
>   " call s:enable_termgui()
> 
>   " Override the default settings.
>   " Uncomment the following line to disable relative number.
>   " set norelativenumber
> 
>   " Adding extras.
>   " Uncomment the following line If you have installed the powerline fonts.
>   " It is good for airline layer.
>   " let g:airline_powerline_fonts = 1
> endfunction
> ```



> `let g:spacevim_lsp_engine = 'coc'` 放在外面，space-vim 提供的配置项都放在外面。
> 
> ```viml
> " Comment the following line if you don't want Vim and NeoVim to share the
> " same plugin download directory.
> let g:spacevim_plug_home = '~/.vim/plugged'
> 
> " Uncomment the following line to override the leader key. The default value is space key "<\Space>".
> " let g:spacevim_leader = "<\Space>"
> 
> " Uncomment the following line to override the local leader key. The default value is comma ','.
> " let g:spacevim_localleader = ','
> 
> " Enable the existing layers in space-vim.
> " Refer to https://github.com/liuchengxu/space-vim/blob/master/layers/LAYERS.md for all available layers.
> let g:spacevim_layers = [
>       \ 'fzf', 'better-defaults','which-key','text-align','better-motion',
>       \ 'lsp',
>       \ 'markdown',
>       \ 'file-manager',
>       \ 'syntax-checking',
>       \ 'editing','formatting','programming',
>       \ ]
> 
> " ================================
> let g:spacevim_lsp_engine = 'coc'
> " ================================
> 
> " Uncomment the following line if your terminal(-emulator) supports true colors.
> " let g:spacevim_enable_true_color = 1
> 
> " Uncomment the following if you have some nerd font installed.
> " let g:spacevim_nerd_fonts = 1
> 
> " If you want to have more control over the layer, try using Layer command.
> " if g:spacevim.gui
> "   Layer 'airline'
> " endif
> 
> " Manage your own plugins.
> " Refer to https://github.com/junegunn/vim-plug for more detials.
> function! UserInit()
> 
> endfunction
> 
> " Override the default settings from space-vim as well as adding extras
> function! UserConfig()
>   " If you have installed the powerline fonts and want to enable airline layer
>   " let g:airline_powerline_fonts=1
>   let g:syntastic_swift_checkers = ['swiftpm','swiftlint']
>   let g:ale_linters = { 'swift': ['swiftlint'] }
>   let g:ale_sign_column_always = 1
>   let g:ale_sign_error = '>>'
>   let g:ale_sign_warning = '--'
>   " Set this. Airline will handle the rest.
>   let g:airline#extensions#ale#enabled = 1
> 
>   " Override the default settings.
>   " Uncomment the following line to disable relative number.
>   " set norelativenumber
> 
>   " Adding extras.
>   " Uncomment the following line If you have installed the powerline fonts.
>   " It is good for airline layer.
>   " let g:airline_powerline_fonts = 1
> endfunction
> ```
嗯,修改生效了,可以提示当前页面中存在的字符.
不过首次还是没启动snippets提示功能. 目前先打开类似`test.py`的文件,再回到md文件中,才生效
这种情况,是哪个配置没有生效导致的呢?
