### ISSUE TITLE
如何隐藏 vim-better-default 首屏出现的 space-vim 几个很大的字母

### ISSUE THREAD

**Issue by exten** [liuchengxu/space-vim#402]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [Y] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [Y] NeoVim

**Put the contents of `:version` below:**
**我喜欢简洁一点的vim-better-default 页面，只显示历史文件以及项目列表即可，如何隐藏不显示最上面的 space-vim 几个字符绘制的字母**
```

```

**Comment by liuchengxu** [comment]
```vim
function! UserConfig() abort
  let g:startify_custom_header = ['my custom header']
endfunction
```

**Comment by exten** [comment]
非常感谢！！！
