### ISSUE TITLE
How to add new bindings under leader key?

### ISSUE THREAD

**Issue by c02y** [liuchengxu/space-vim#406]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```

```

### Problem Description

1. How to add new bindings under leader key, for instance, I want to add a new binding such as `<Leader> t t` to toggle line number.(If such binding exists, please ignore me, it is just an example)

2. I can know how to add new prefix and bindings under it after reading core/autoload/spacevim/map/leader.vim, but a documentation should be created.

**Comment by c02y** [comment]
OK, I got it after reading layers/+distributions/better-defaults/keybindings.vim file.

Just like usually way in vimrc:
~~~
  nnoremap <Leader>tt :call NumberToggle()<cr> " NumberToggle() is just a function
~~~

**Comment by liuchengxu** [comment]
To he honest, I now don't have too much time for this project, which just works perfectly for me. If you are willing to help, you could contribute to the help https://github.com/liuchengxu/space-vim/blob/cd5c20198528058bf93332750711ccfa7793a7a4/core/doc/spacevim.txt .
