### ISSUE TITLE
spacevim.speed_up_via_timer问题

### ISSUE THREAD

**Issue by YHYJ** [liuchengxu/space-vim#411]
为什么要设置`g:spacevim.speed_up_via_timer`=1的时候不加载这些插件呢?
![pic](https://raw.githubusercontent.com/YHYJ/MyPic/master/picgo/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190709172014.png)

我用的layer 'go'测试，然后我设置了g:spacevim.speed_up_via_timer=0,也还是不能使用自动补全（比如fmt.Pr...），直到我取消了`{'on': []}`才可以正常补全golang

thx!

**Comment by YHYJ** [comment]
刚又测试了一下，不管g:spacevim.speed_up_via_timer的值是0还是1,layer 'python'都是可以的

**Comment by liuchengxu** [comment]
See #410.

**Comment by YHYJ** [comment]
thx!
the configuration options for 'spacevim' can only be set in `$HOME/.spacevim` ? i set it up in `$HOME/.space-vim/private/config.vim`, it didn't work

**Comment by liuchengxu** [comment]
All `spacevim_*` options should be provided in `~/.spacevim`, they are space-vim specific. `~/.space-vim/private/config.vim` could be used for overriding non space-vim specific settings.
