### ISSUE TITLE
How to highlight the text in cscope output window

### ISSUE THREAD

**Issue by c02y** [liuchengxu/space-vim#413]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```

```

**Put the contents of `:SpaceInfo` below:**

```

```

### Problem Description

How to highlight the text in cscope output window like the screenshot
![VkZER](https://user-images.githubusercontent.com/2135996/61034981-e6265700-a3f8-11e9-9373-b70f1588880f.png)

**Comment by liuchengxu** [comment]
`:h *` may help you. And I think you should ask it in reddit, stackoverflow, etc.

**Comment by c02y** [comment]
I think you misunderstood what I was saying, I mean when you use cscope to find a definition or a string in vim, it is better to highlight the string in the cscope output automatically, it doesn't have to be highlighted like the screenshot, all kinds of highlight will be OK, it has nothing to do with `*`.

Of course, this is not the problem of space-vim project.
Since space-vim provides cscope layer, if this layer can do this, that is better.

Anyway, I'll try to figure out the solution, and will update this post once available.

**Comment by liuchengxu** [comment]
I personally hardly have a chance to use cscope layer recently. But it you could provide a more detailed proposal, I may help implement it since it's not hard to add a highlight, e.g., `:h matchadd()`.

**Comment by scottlvsha** [comment]
I also want to know,  please let me know if you got the answer, thanks
