### ISSUE TITLE
Layer cscope has nothing to do with romainl/vim-qf plugin?

### ISSUE THREAD

**Issue by c02y** [liuchengxu/space-vim#415]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```

```

**Put the contents of `:SpaceInfo` below:**

```

```

### Problem Description

From https://github.com/liuchengxu/space-vim/blob/master/layers/LAYERS.md link, I get that the cscope layer includes `romainl/vim-qf` plugin, but in `.space-vim/layers/+tools/cscope/config.vim`, it has nothing to do with `romainl/vim-qf`.

Another thing is: can I exclude a subdirectory when using cscope?

**Comment by liuchengxu** [comment]
Just use the functions provided by vim-qf, no extra config. I basically don't cscope now so can't answer your second question.
