### ISSUE TITLE
Unable to add description for maps using vim-which-key

### ISSUE THREAD

**Issue by c02y** [liuchengxu/space-vim#419]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```

```

**Put the contents of `:SpaceInfo` below:**

```

```

### Problem Description

Check https://github.com/liuchengxu/vim-which-key/issues/59 for details, and this issue is partially related to https://github.com/liuchengxu/space-vim/issues/414

**Comment by liuchengxu** [comment]
```vim
function! UserConfig() abort

  let g:spacevim#map#leader#desc = g:spacevim#map#leader#desc

  nnoremap <Leader>ff :GFiles<CR>
  let g:spacevim#map#leader#desc.f = get(g:spacevim#map#leader#desc, 'f', {})
  let g:spacevim#map#leader#desc.f.f = 'My-FF'

endfunction
```

**Comment by c02y** [comment]
Thanks, it works, but there is another question, how to add description for special keys like `<LEFT>/<RIGHT>/<UP>/<DOWN>` and `<Space>`, `<Bslash>`(`\`)? I've tried to use them like 
~~~
let g:spacevim#map#leader#desc.w.<LEFT> = 'test'
let g:spacevim#map#leader#desc.b.<Space> = 'test'
let g:spacevim#map#leader#desc.w.<Bslash> = 'test'
~~~

but they all produce the same error message:
~~~
E985: .= is not supported with script version 2
~~~
