### ISSUE TITLE
Cannot cut and paste `dd` during git rebase

### ISSUE THREAD

**Issue by florentx** [liuchengxu/space-vim#424]
After f993d4f it's no longer easy to copy paste 1 or more lines during a git-rebase for re-ordering commits.

The usual keys `dd` or `<num>dd` no longer work.

**Comment by liuchengxu** [comment]
`d` is mapped to drop the commit when in the `gitrebase` buffer. If you don't want it, just unmap `d`:

```vim
function! UserConfig() abort 
  autocmd FileType gitrebase unmap <buffer> d
endfunction
```

**Comment by florentx** [comment]
Well I'm not really fond of this new behavior.
I don't like that it shadows some commonly used key bindings.

Maybe it should be off by default, and the user can opt-in for these bindings in his/her configuration `~/.spacevim` with a `g:spacevim_gitrebase_keybindings  =  1` ?

Or the bindings could use a modifier key ?
E.g. `Control+P` / `Control+R` ... `Control+D` ...

At least the `dd`, `p` and `P` are standard keys which are useful during a rebase.

On a similar topic:
https://www.reddit.com/r/git/comments/6lln75/vim_keybindings_for_interactive_rebase/djupt43/

**Comment by liuchengxu** [comment]
Well, that makes sense. I have added an option `b:spacevim_enable_map` for gitrebase buffer, which is disabled by default.
