### ISSUE TITLE
vim-rsi overrides german "ä" and daenish "æ" key

### ISSUE THREAD

**Issue by hantslambda** [liuchengxu/space-vim#433]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
```

**Put the contents of `:SpaceInfo` below:**

```

```

### Problem Description

vim-rsi gets loaded by better-defaults. Which then Proceeds to override `<M-d>`.
`<M-d>` in turn corresponds to the german "ä" key, which thus cannot be used for writing texts anymore.
UserConfig seems to run before vim-rsi is loaded. 
Where would be the right place to unmap `<M-d>` ?

Awesome Project btw. Thank You!

Also see upstream bug report: https://github.com/tpope/vim-rsi/issues/14

**Comment by liuchengxu** [comment]
Doesnot `let g:rsi_no_meta = 1` work for you?

**Comment by hantslambda** [comment]
that was fast! It works perfectly. Thank you very much :+1:
