### ISSUE TITLE
disabling vim_current_word 

### ISSUE THREAD

**Issue by edrex** [liuchengxu/space-vim#436]
I don't want vim_current_word highlighting while writing prose (especially while journaling with Goyo). 

I'm unable to get the feature to disable for matching buffers in neovim (ideas welcome :) ) https://github.com/dominikduda/vim_current_word/issues/9#issuecomment-531451681 so I just want to disable it globally.

I looked around for a supported way to disable plugins. I tried adding

```
	Plug 'dominikduda/vim_current_word', { 'on': [] }
```

to `UserInit()` but that doesn't seem to work.

I'm aware of `vim_current_word#vim_current_word_disable()` which I could call after startup (maybe with an AutoCmd) to disable everywhere. That's probably what I'll do for now.

It would be nice if there was a supported way of overriding specific plugins. Also IDT vim_current_word should be in better_defaults, since some people (ahem me) might find it annoying.

Cheers :)

**Comment by liuchengxu** [comment]
Use `g:spacevim_excluded` to exclude the plugins that you don't want:

```vim
let g:spacevim_excluded = ['dominikduda/vim_current_word']

function! UseInit() abort
endfunction

function! UserConfig() abort
endfunction
```

**Comment by edrex** [comment]
Thanks, that's just what I was hoping for. Might think about including a commented line in the docs, although maybe I'm the only one who inevitably wants to disable something hard-to-reach.

**Comment by liuchengxu** [comment]
See `:h g:spacevim_excluded`. And also feel free to help the docs.
