### ISSUE TITLE
space-vim 对vue的折叠如何实现？还有，eleline不显示git的状态

### ISSUE THREAD

**Issue by dielianhuachusai** [liuchengxu/space-vim#443]
### Environment

- OS:
    - [] Linux
- Vim:
    - [] Terminal Vim
    - [] NeoVim

如题所示，space-vim的折叠如何实现的？我看源码没找到，eleline对git不提示，不用space-vim直接装eleline和git

**Comment by liuchengxu** [comment]
>**Note that low quality issue feedback might be closed directly**.

**Comment by dielianhuachusai** [comment]
OK, but you could answer my question first
