### ISSUE TITLE
使用 vi -t 命令的时候导致索引无法正常显示

### ISSUE THREAD

**Issue by jianghao0302** [liuchengxu/space-vim#445]
当使用 vi -t 进行 tag 代码检索的的时候，发现无法显示出来检索出来的代码列表，每次都必须按下空格或者回车后，才会显示。按下按键后，表现是水平又开了一个窗口。我需要在使用 vi -t 的时候能在弹出的 vim 页面上直观的显示并输入需要跳转的地方。
![image](https://user-images.githubusercontent.com/22189088/66698714-e8a78e00-ed12-11e9-8b2c-bea1338d7c43.png)

**Comment by jianghao0302** [comment]
滑动鼠标后，发生了这种现象
![image](https://user-images.githubusercontent.com/22189088/66698844-2ce75e00-ed14-11e9-91d0-c5dee4890ce4.png)

**Comment by liuchengxu** [comment]
我不知道你在说什么。

**Comment by jianghao0302** [comment]
ctags 索引被 airline 遮盖。具体情况看下面的详细说明：


详细说明一下，首先看看我的 .spacevim 的配置，主要是对插件 airline 的添加，
对内核执行 make tags，生成 tag 文件：


不添加 airline 层的情况：
.spacevim 层配置：

继续操作，对内核某一函数进行 tag 索引，vi -t atomic_set：


执行此命令后，会生成一个索引列表：

在列表下面可以选择是API序列，跳入。
现在的情况是，添加了 airline 层之后，索引被遮盖住，如下：
添加 airline 层：



继续操作，对内核某一函数进行 tag 索引，vi -t atomic_set：

此时应该会生成一个索引界面，但是界面为空，索引被 airline 层遮盖住了。







------------------ 原始邮件 ------------------
发件人: "Liu-Cheng Xu"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 晚上7:55
收件人: "liuchengxu/space-vim"<space-vim@noreply.github.com>;
抄送: "游戏进行中"<312143663@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liuchengxu/space-vim] 使用 vi -t 命令的时候导致索引无法正常显示 (#445)




我不知道你在说什么。
