### ISSUE TITLE
spacevim如何默认使用 Python 3 运行代码

### ISSUE THREAD

**Issue by lov1394** [liuchengxu/space-vim#446]
新手用的ubuntu装了spacevim后对着文档整了很长时间没弄明白，想请教下怎么调整为默认3.x运行程序，还有就是文档里说的添加F5快捷键运行程序，添加后没反应，不是在下面的两个文件里添加么？
~/.SpaceVim.d/init.toml
~/.SpaceVim.d/autoload/myspacevim.vim
大佬路过瞅一眼，不胜感激！

**Comment by liuchengxu** [comment]
你找错地方了，这是 space-vim 的仓库，不是 SpaceVim.

**Comment by lov1394** [comment]
汗颜-_-||头一次用这个网站
