### ISSUE TITLE
python auto-completion not work with jedi-vim

### ISSUE THREAD

**Issue by co1inlee** [liuchengxu/space-vim#45]
when I enable **auto-completion** and **jedi-vim** layers, python completion can't work with `jedi-vim`, It always complete with `omni completion`, maybe cause by `autocmd FileType python setlocal omnifunc=pythoncomplete#Complete`. So, maybe remove `omni completion` config from `auto-completion` layer, let user custom config!

**Comment by liuchengxu** [comment]
So, have you tried to remove `autocmd FileType python setlocal omnifunc=pythoncomplete#Complete` in your case? Does this result in the problem?

BTW, `ycmd` has contained `jedi-vim`, and more than that, maybe worthy of giving a try.

**Comment by co1inlee** [comment]
before, I have try remove `autocmd FileType python setlocal omnifunc=pythoncomplete#Complete` in `auto completion` layer, it works for me , but in this way,  i have modified source code, so i wouldn't do this. BTW, `ycmd` is so large, i wouldn't use it!!

**Comment by liuchengxu** [comment]
As said above, it's the problem that vim can only have one completion function work at a time. I am sure that auto-completion and jedi-vim both supply their own completion function (I am not sure which one would be valid).  If diable `autocmd FileType python setlocal omnifunc=pythoncomplete#Complete in auto completion` in auto-completion, it may disrespect these who only use auto-completion. 

I think the completion functionality supplied by jedi-vim is stronger than the one supported by auto-completion, so it's unnecessary to use auto-completion and jedi-vim simultaneously, you can disable auto-completion when using jedi-vim.

**Comment by co1inlee** [comment]
well,we should set this `autocmd FileType python setlocal omnifunc=jedi#completions` in **~/.spacevim**.  it work well both **neocomplete** and **jede-vim**. close！

**Comment by liuchengxu** [comment]
Great! I would update later and PR is also welcome!
