### ISSUE TITLE
Clarify the section about customization to indicate that it is key to set it up

### ISSUE THREAD

**Issue by danielo515** [liuchengxu/space-vim#453]
### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [x] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

### Problem Description
First of all, let me say thank you very much for creating something like this. I'm just start to trying it, but looks promising. I have a suggestion about docs.
This is what the documentation says about customization:

>You can use .spacevim in your home directory to customize space-vim, where you can enable the existing layers, add your extra plugins and private configurations.

One line below, there is a very important sentence that should be entire bold

> If .spacevim does not exist, vanilla vim will be loaded! Refer to init.spacevim as an example.

Also, it is worth explaining that, an empty .spacevim file (I just created it because I read an spacevim error message, exiting...) leads to a broken spacevim experience. Even some plugins that has been reported to be default are not present (like better vim defaults). I'm not sure if my installation just went wrong or what, but my first minutes were a bit frustrating. Now everything seems to work fine, but I just want to make this problem not happen to anyone else in the future.

Regards

**Comment by liuchengxu** [comment]
If you were using `install.sh`, `.spacevim` will be generated automatically, https://github.com/liuchengxu/space-vim/blob/d11accd1c79189af5bc0d056299eee13fa8688d4/install.sh#L101

**Comment by liuchengxu** [comment]
Feel free to improve the docs.
