### ISSUE TITLE
suggestion:tmux layer

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/space-vim#46]
[tmux-plugins/vim-tmux](https://github.com/tmux-plugins/vim-tmux) : .tmux.conf's syntax,help...

[christoomey/vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) : 

> the plugin will allow you to navigate seamlessly between vim and tmux splits using a consistent set of hotkeys.

need extra config of tmux:

```config
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

[lucidstack/ctrlp-tmux.vim](https://github.com/lucidstack/ctrlp-tmux.vim)：switch tmux session through ctrlp..

I think there are some more useful plugins of vim for tmux that I haven't found.

**Comment by liuchengxu** [comment]
Have you ever tried these plugins? If you are conversant with these plugins, maybe you could open up a PR. `+tools/tmux` sounds good. Or I'll take some time to give it a shot.

**Comment by tracyone** [comment]
ok,i will try to make one.

Maybe there are some keymap conflict with space-vim.

C-h C-j C-k C-l in normal mode

I use m-h m-j m-k m-l instead.

what do you think?

**Comment by liuchengxu** [comment]
No worries. Space-vim doesn't set these key mappings (`C-[hjkl]`) in normal mode.
