### ISSUE TITLE
How to disable fzf plugin

### ISSUE THREAD

**Issue by inengch** [liuchengxu/space-vim#462]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [x] Linux
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim

**Put the contents of `:version` below:**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 28 2020 14:00:06)
```

**Put the contents of `:SpaceInfo` below:**

```

```

### Problem Description

How to disable fzf plugin, thanks in advance

**Comment by liuchengxu** [comment]
Remove `fzf` from `g:spacevim_layers` in `~/.spacevim`.
