### ISSUE TITLE
How to change the cursor's highlight color

### ISSUE THREAD

**Issue by jyscao** [liuchengxu/space-vim#465]
I'm using the default theme `space_vim_theme`. Everything looks great, the one slight inconvenience though is that I find the highlighting color for the current cursor position to be too similar to the highlighting color for the entire word under the cursor. As shown in screenshot below:
![image](https://user-images.githubusercontent.com/12605746/99198136-9bdb8580-2764-11eb-933c-ecac0f27db79.png)

The cursor at `=` is barely distinguishable from the surrounding word.

What's the easiest way to modify this setting?

**Comment by liuchengxu** [comment]
You should configure your terminal emulator instead of the vim theme, see https://vi.stackexchange.com/a/7177.
