### ISSUE TITLE
Layer 'syntax-checking' should be included before Layer 'spacevim'

### ISSUE THREAD

**Issue by zYeoman** [liuchengxu/space-vim#47]
E117: Unknown function: ALEGetError
E116: Invalid arguments for function empty(ALEGetError())?ALEGetError():''
请按 ENTER 或其它命令继续
E15: 无效的表达式: !empty(ALEGetError())?ALEGetError():''
请按 ENTER 或其它命令继续
E117: Unknown function: ALEGetWarning
请按 ENTER 或其它命令继续
E116: Invalid arguments for function empty(ALEGetWarning())?ALEGetWarning():''
...

**Comment by liuchengxu** [comment]
抱歉，现在这个问题应该解决了。

**Comment by changyukang** [comment]
加油，特别喜欢spacevim👍

**Comment by liuchengxu** [comment]
@changyukang 谢谢 ❤️
