### ISSUE TITLE
Line number display error 

### ISSUE THREAD

**Issue by vioulo** [liuchengxu/space-vim#482]
- OS:
    - [x] Linux (debian 10)
    - [] macOS
    - [] Windows
    - [] FreeBSD
- Vim:
    - [x] Terminal Vim
    - [] GVim
    - [] NeoVim
![image](https://user-images.githubusercontent.com/27475937/124064813-22c93e00-da68-11eb-84e3-45d8672aeada.png)

**Comment by liuchengxu** [comment]
Add `set norelativenumber` if you dislike it.

**Comment by vioulo** [comment]
> Add `set norelativenumber` if you dislike it.

My question is for the line number and the actual inconsistency before and after.
