### ISSUE TITLE
在 UserConfig 配置快捷键无效, 不知道为何?

### ISSUE THREAD

**Issue by alvin2ye** [liuchengxu/space-vim#49]
```
function! UserConfig()
    map <c-p> :FZF<CR>
endfunction
```

**Comment by liuchengxu** [comment]
试试 `nmap <c-p> :FZF<CR`

**Comment by liuchengxu** [comment]
我测试过应该 OK, 那么就先关闭了。

**Comment by alvin2ye** [comment]
更新后, 确实可以调用FZF
但是错误

![](https://agi-pub.b0.upaiyun.com/skitch/Pasted_Image_1_22_17__12_34_PM_1E346DE4.png)

**Comment by liuchengxu** [comment]
哈哈 我也遇到过这个问题 还给 fzf 提了一个 issue 。 很简单， 因为 fzf 更新了，需要重新下载 fzf binary, 运行 fzf 的安装脚本 ( ~/.fzf/install) 下载最新的 fzf 即可。

**Comment by alvin2ye** [comment]
@liuchengxu 谢谢 果然解决

**Comment by liuchengxu** [comment]
@alvin2ye 从截图来看你好像没有开启终端的真彩色支持，使用 iterm2 的话，可以直接在 UserConfig() 中设置 `set termguicolors`，试一下说不定有不一样的视觉体验。
