### ISSUE TITLE
Start screen is messy on MacVim 

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#5]
<img width="633" alt="wx20161208-220351 2x" src="https://cloud.githubusercontent.com/assets/465125/21012719/51162bd0-bd92-11e6-83b2-ea131978bc9a.png">

And after resize the window, screen becomes black.

**Comment by liuchengxu** [comment]
Could it be more specific? I can not reproduce this.

**Comment by yesmeck** [comment]
我发现是因为启动的时候窗口往上滚动了，往下滚动一下位置就正常了，不知道为什么会产生滚动。

**Comment by liuchengxu** [comment]
这个问题我也发现了，不过还不知道是怎么回事, terminal 中没有这个问题。

**Comment by yesmeck** [comment]
https://github.com/mhinz/vim-startify/issues/31

**Comment by yesmeck** [comment]
[这行](https://github.com/liuchengxu/space-vim/blob/a452abb84b4e9df633671d420ad1bd2ff2b92813/layers/%2Bvim/better-defaults/config.vim#L63) 注释掉就好了。

**Comment by yesmeck** [comment]
设置 100 的目的是？

**Comment by liuchengxu** [comment]
设置 GUI 启动时界面的大小。

**Comment by yesmeck** [comment]
没必要设置吧，就是这个 `lines=100` 的缘故。

**Comment by liuchengxu** [comment]
现在看来的确是多此一举.....

**Comment by liuchengxu** [comment]
已经修复。
