### ISSUE TITLE
请问一下为什么载入ycmd之后，依然没有启用自动补全呢？

### ISSUE THREAD

**Issue by zhaoyingjie** [liuchengxu/space-vim#50]

**Comment by liuchengxu** [comment]
可以贴下你的 `.spacevim` 和介绍下使用环境（os 之类的）吗？

**Comment by zhaoyingjie** [comment]
安装的时候速度基本上都是2、3MB\S，所以我的安装过程应该是没有问题，在:PlugStatus里面也显示YouCompleteMe是已经加载了的，另外我的.spacevim文件是除了默认的内容之外，就只是添加了一句```Plug 'ycmd'```
我用的系统是运行在Docker中的ubuntu16.04，开始我还以为是ycmd的配置问题，后来找了一下好像跟ycmd的配置没什么关系，请问您有什么好的解决办法吗？

**Comment by liuchengxu** [comment]
如果确认 YouCompleteMe 安装没有问题的话，那么按照常理应该是可以起作用的。因为我没有在 docker 中试过，所以可能不是太清楚具体是什么原因。

你试一下其他其他 Layer 可以正常工作吗？比如 syntax-checking layer, 打开 python 文件应该就会显示语法检查的信息。

**Comment by zhaoyingjie** [comment]
syntax-checking也是报错，找不到function()....之类的，请问一下这两个插件都是需要在python2.7的环境下才能用吗，因为我的ubuntu16.04只装了python3.5，不知道是不是这里的原因？

**Comment by liuchengxu** [comment]
我本地也是 python3.5， 应该没问题的。

把完整的错误信息贴一下吧。

**Comment by zhaoyingjie** [comment]
请问有什么输出错误日志的配置吗？

**Comment by liuchengxu** [comment]
额.., 你可以把 vim 的出错信息复制粘贴吗？没有什么自动化输出错误日志的配置...

**Comment by zhaoyingjie** [comment]
我重新开了一个容器，正在安装，稍后会将错误信息和配置贴出来。请稍等。😉

**Comment by liuchengxu** [comment]
好的，因为我没玩过 docker, 所以也不太了解~

**Comment by zhaoyingjie** [comment]
你好，这是我测试的结果：
<img width="1280" alt="2017-01-23 6 21 45" src="https://cloud.githubusercontent.com/assets/21018959/22200403/f020f6e4-e199-11e6-92b5-228442ff7be1.png">
<img width="642" alt="2017-01-23 6 23 45" src="https://cloud.githubusercontent.com/assets/21018959/22200410/f07ae546-e199-11e6-8252-091b27d39907.png">
<img width="1280" alt="2017-01-23 6 25 33" src="https://cloud.githubusercontent.com/assets/21018959/22200409/f07a2c64-e199-11e6-86b5-0bcd56780e10.png">
<img width="200" alt="2017-01-23 6 26 22" src="https://cloud.githubusercontent.com/assets/21018959/22200408/f077fa66-e199-11e6-9c74-d07314f31b10.png">
<img width="1280" alt="2017-01-23 6 29 00" src="https://cloud.githubusercontent.com/assets/21018959/22200412/f07d90d4-e199-11e6-8a26-435aa8c100fc.png">
<img width="1280" alt="2017-01-23 6 29 14" src="https://cloud.githubusercontent.com/assets/21018959/22200411/f07bf6de-e199-11e6-98bb-cd4905127a64.png">

**Comment by zhaoyingjie** [comment]
你好，上面图片里面我贴出来了所安装的layer，以及import的时候并没有开始自动补全的情况，另外几张是我测试```:PlugStatus```之后，尝试load这些插件的时候的报错信息。

**Comment by liuchengxu** [comment]
1. 看起来像是 YouCompleteMe 的 python 路径不太对，`which python` 看看你的 python 路径，然后修改下面的内容，将下面的配置信息写到 `UserConfig()`:
    ```vim
    let g:ycm_path_to_python_interpreter='你的 python 路径'
    ```

**Comment by zhaoyingjie** [comment]
将```let g:ycm_path_to_python_interpreter='/usr/bin/python3'```添加到```UserConfig()```之后，出现了这个错误
<img width="1280" alt="2017-01-23 6 34 37" src="https://cloud.githubusercontent.com/assets/21018959/22200753/63e11e00-e19b-11e6-9dea-bdff17343f54.png">

**Comment by liuchengxu** [comment]
这个就是我之前所说的了，你需要编译 YouCompleteMe, 按照我开头的步骤做就 OK 了。

**Comment by zhaoyingjie** [comment]
...我使用这条命令```sh -c "$(curl -fsSL https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)"```不是全自动安装编译的吗？😅

**Comment by liuchengxu** [comment]
是这样，YouCompleMe 有点特殊..... 😆

**Comment by liuchengxu** [comment]
你好像没有开启 `set termguicolors`, 可以开启试一下，说不定会有不一样的体验~

关于 ycmd 的使用，YouComplemteMe 可能是 vim 插件中最复杂的一个了，或许应该有个额外的安装说明，提供一个简易的安装脚本~

**Comment by zhaoyingjie** [comment]
好的，谢谢您的解答🤝

**Comment by liuchengxu** [comment]
问题解决了吗？那么就先关闭咯~
