### ISSUE TITLE
How do I uninstall spacevim from my Windows 11 pc.

### ISSUE THREAD

**Issue by 17Swagat** [liuchengxu/space-vim#502]
Before you continue, ensure you have read the [README](https://github.com/liuchengxu/space-vim/blob/master/README.md) and [wiki](https://github.com/liuchengxu/space-vim/wiki) carefully. **Note that low quality issue feedback might be closed directly**.

### Environment

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- OS:
    - [] Linux
    - [] macOS
    - [x] Windows
    - [] FreeBSD
- Vim:
    - [] Terminal Vim
    - [] GVim
    - [x] NeoVim

**Put the contents of `:version` below:**

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

```

### Problem Description

 HOW DO I UNISTALL SPACEVIM FROM MY WINDOWS PC. I SIMPLY DOWNLOADED THE install.cmd FILE AND RUN IT. AND SPACEVIM WAS INSTALLED ON MY SYSTEM. NOW I WANT TO UNINSTALL IT COMPLETELY. HOW TO DO IT ??

**Comment by rene-descartes2021** [comment]
You can read `install.cmd` to see everything installed by `install.cmd`.

Delete `"$HOME\.spacevim"` and `"$HOME\.space-vim"` to delete everything specific to space-vim. You may additionally delete vim-plug, symbolic links, and any plugins installed by space-vim on your filesystem, but those have to do with managing Vim configuration and not space-vim.
