### ISSUE TITLE
airline与syntax-checking同时开启时报错

### ISSUE THREAD

**Issue by zhaoyingjie** [liuchengxu/space-vim#52]
在Layer中同时添加了airline和syntax-checking之后，进入vim会报错，提示airline#extension#syntaxchecking#...之类的错误，好像两个插件有冲突。不知道您有没有检测过?

**Comment by zhaoyingjie** [comment]
刚才重新试了一下，问题好像解决了，应该是airline自带集合syntastic的功能，但是同时安装的时候airline会报错，所以如果两个插件同时启用的话，应该先启用syntastic，之后再启用airline。

**Comment by liuchengxu** [comment]
airline 嵌入了很多其他插件的信息，也是它的优点，同时也是缺点，因为它涉及的第三方扩展可能会出现问题，比如我之前遇到一个 tagbar 的问题，最后也是不了了之~
