### ISSUE TITLE
请问vim8如何安装？space-vim该如何安装？

### ISSUE THREAD

**Issue by xgj1010** [liuchengxu/space-vim#53]

**Comment by liuchengxu** [comment]
额，你应该要先介绍一下你的使用环境，mac? linux? windows?

**Comment by xgj1010** [comment]
我用的是虚拟机Ubuntu16.10，装了一个晚上vim8始终装不上

**Comment by liuchengxu** [comment]
我不知道你是否搜索过相关内容，无法安装的具体原因是什么，有什么报错？

我刚才搜索了一下，有很多 ubuntu16.04/16.10 安装 vim8 的信息，因为我目前使用的是 mac, 所以暂时无法进一步给出详细的指引。
