### ISSUE TITLE
是否有快速批量注释的按键呢？之前的被取消了

### ISSUE THREAD

**Issue by zhaoyingjie** [liuchengxu/space-vim#54]

**Comment by liuchengxu** [comment]
批量注释？是指选择一块区域进行注释吗？`SPC ;;` 空格+两个分号，不可以？快速注释的快捷键在 programming Layer 中 https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/config.vim#L136-L142 。

**Comment by zhaoyingjie** [comment]
嗯嗯，是的，之前没找到，谢谢啦～
            在2017年01月25日 21:49，Liu-Cheng Xu 写道： 批量注释？是指选择一块区域进行注释吗？SPC ;; 空格+两个分号，不可以？快速注释的快捷键在 programming Layer 中 https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/config.vim#L136-L142 。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liuchengxu/space-vim","title":"liuchengxu/space-vim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liuchengxu/space-vim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liuchengxu in #54: 批量注释？是指选择一块区域进行注释吗？`SPC ;;` 空格+两个分号，不可以？快速注释的快捷键在 programming Layer 中 https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/config.vim#L136-L142 。"}],"action":{"name":"View Issue","url":"https://github.com/liuchengxu/space-vim/issues/54#issuecomment-275111931"}}}

**Comment by liuchengxu** [comment]
OK, 可以看一下 README, 如果发现有错误或者没有提到的内容，欢迎提 PR 哈 😃

**Comment by zhaoyingjie** [comment]
不过好像真不行...您试过吗？
            在2017年01月25日 21:49，Liu-Cheng Xu 写道： 批量注释？是指选择一块区域进行注释吗？SPC ;; 空格+两个分号，不可以？快速注释的快捷键在 programming Layer 中 https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/config.vim#L136-L142 。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liuchengxu/space-vim","title":"liuchengxu/space-vim","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liuchengxu/space-vim"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liuchengxu in #54: 批量注释？是指选择一块区域进行注释吗？`SPC ;;` 空格+两个分号，不可以？快速注释的快捷键在 programming Layer 中 https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/config.vim#L136-L142 。"}],"action":{"name":"View Issue","url":"https://github.com/liuchengxu/space-vim/issues/54#issuecomment-275111931"}}}

**Comment by liuchengxu** [comment]
注释与取消注释也是我经常用的工作，我这里是没有问题的。

1. `SPC ?` 查看你的键位映射中是否存在 `<Space>;;`.
<img width="1280" alt="2017-01-26 6 52 38" src="https://cloud.githubusercontent.com/assets/8850248/22312733/13ff4204-e394-11e6-9de8-e32f8690bb72.png">

2. 空格键加两个分号这几个按键操作之间停顿时间不要太长，否则 vim 会识别不出这个动作。
