### ISSUE TITLE
注释文字的配色问题

### ISSUE THREAD

**Issue by janghyuan** [liuchengxu/space-vim#56]
#### Environment

- OS: macOS 10.12.3
- vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 16 2017 18:07:00)

#### Problem Description

注释的配色问题，前景色和背景色反转：

![2017-02-01 9 45 53](https://cloud.githubusercontent.com/assets/17661036/22509176/db1111fa-e8c7-11e6-890b-d6d6d4de96a9.png)
![2017-02-01 9 46 57](https://cloud.githubusercontent.com/assets/17661036/22509194/fbbc8d58-e8c7-11e6-9e78-d9f001460a2e.png)

我用 `:highlight` 查看时，看不出什么问题？

**Comment by liuchengxu** [comment]
你是在 tmux 里面吧？使用的 iterm2 ? 先看一下这里：https://github.com/liuchengxu/space-vim/wiki/Tips#macos

我也遇到过这个问题，你看上面的链接有没有用, 我忘记记录这个点了....

**Comment by liuchengxu** [comment]
好像是这里的问题:

<img width="1049" alt="2017-02-01 10 10 18" src="https://cloud.githubusercontent.com/assets/8850248/22510039/6d94b268-e8cb-11e6-8eb2-29b90a96b5fe.png">

Terminal Type 你之前有修改过吗？

tmux 的涉及内容大概在这里: https://github.com/liuchengxu/dotfiles/blob/master/tmux.conf#L1-L7.

具体的步骤我有点不记得了，可以看这里 https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/ ，大概是生成 terminfo 文件，在 preference 中进行设置这样。

**Comment by janghyuan** [comment]
问题解决：）

本质的原因就是终端不支持`italic`，而你的colorscheme中，Comment的`cterm=italic`

解决方案：
分别为iTerm和Tmux添加两个terminfo，然后在相应的位置指定`TERM`变量就OK了。至于系统默认的终端，只需要在`.bash_profile`中设置好`TERM`变量（利用之前添加的terminfo）

上面写的比较简陋，有时间写个详细的wiki，PS：过年没有及时查看邮件，@liuchengxu 效率真快啊：）

**Comment by liuchengxu** [comment]
@janghyuan 👍 

如果是因为 终端不支持 `italic`, 而 colorscheme 中设置了 `cterm=italic`, 可能还有一个比较简单的方法, 在 `UserConfig()` 中设置:

```
hi Comment cterm=None
```

直接取消 `italic`. 期待您解决方案的 wiki.

PS: 过年没啥事儿~

**Comment by liuchengxu** [comment]
@janghyuan 默认设置 `hi Comment cterm=italic` 好像会对 terminal 不支持 italic 的用户造成当前这个 issue  这样令人头疼的困扰，所以我已经把 space-vim-dark 重新设置为 `hi Comment cterm=None`。 
对于有心想要启用 terminal italic 的用户, 可以自行启用，感觉这样会更简单和人性化一点....
