### ISSUE TITLE
space-vim default theme not working properly when using tmux

### ISSUE THREAD

**Issue by onewildgamer** [liuchengxu/space-vim#58]
#### Environment

- OS: ubuntu 14.04
- vim: 8
- neovim: 0.20-dev

#### Problem Description

The default theme of space-vim works properly when using without tmux, but when I use vim inside tmux, the theme, syntax-highlighting etc. goes away. 

I'm a beginner in vim, tmux etc. please guide me.

vim in a normal terminal
![vim](https://cloud.githubusercontent.com/assets/4128250/22540497/7f6523c6-e946-11e6-9854-642eeb8c8e4d.png)

vim in tmux
![tmux-vim](https://cloud.githubusercontent.com/assets/4128250/22540436/16551d28-e946-11e6-990a-fd8b7706db34.png)

**Comment by liuchengxu** [comment]
Have you set `set -g default-terminal "screen-256color"` in `.tmux.conf`?  This setting enables 256 colors in tmux.

**Comment by onewildgamer** [comment]
This brought back the syntax highlighting, but all the pleasantries are still gone. Like, hitting a new line in a function doesn't automatically indent, and ctrl + left/right doesn't go word after word, and the theme is not space-vim-dark.

**Comment by liuchengxu** [comment]
`:echo g:colors_name`, see what the theme is.

**Comment by onewildgamer** [comment]
The g:colors_name output is space-vim-dark.

When .vimrc is disabled, the behaviour in a normal terminal is as expected (nvim default). But in tmux the erratic behaviour starts creeping in.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/dotfiles/blob/master/tmux.conf#L1-L7 Here is my tmux configuration. In ubuntu, I set `set -g default-terminal "screen-256color"` and it works well.

I don't know if your tmux.conf leads to the trouble. Please try `echo $TERM` in terminal.

**Comment by onewildgamer** [comment]
My default terminal is xterm, I tried using your tmux config without much help (though learnt a few unrelated tricks). I also tried setting the default-terminal as xterm, didn't help

**Comment by liuchengxu** [comment]
In ubuntu, I always use the **Terminal** application instead of xterm. Have you tried?

**Comment by tracyone** [comment]
This is part of my zsh setting, hope to help

```bash
which tmux > /dev/null
if [[ $? -eq 0  ]]; then
	case $- in *i*)
		[ -z "$TMUX" ] && exec $(TERM=xterm-256color tmux -2)
	esac
fi
export TERM=xterm-256color
```

execute `tput colors` and see if the output is **256** or not

**Comment by onewildgamer** [comment]
Hey guys, I got the space-vim colours by setting the TERM=xterm-256color in my bashrc

But while in the tmux, the vim doesn't respond to home, end, ctrl+left or right. And I'm not sure what else isn't working

**Comment by onewildgamer** [comment]
Thank you guys,

I got it working by trying out these threads
http://askubuntu.com/questions/125526/vim-in-tmux-display-wrong-colors
http://superuser.com/questions/360832/how-can-i-make-ctrlleft-right-keys-work-right-in-tmux

**Comment by cckate** [comment]
Got same problem. Solved by setting TERM=xterm-256color in zshrc. Thx for the solution @tracyone @onewildgamer
