### ISSUE TITLE
spc+? command not work well

### ISSUE THREAD

**Issue by taizilongxu** [liuchengxu/space-vim#61]
#### Environment

- OS: macOS 10.12.3
- vim: 
- neovim: 0.1.7

#### Problem Description

`spc+?` do not display all the keybinding, and my config is 

```viml
    Layer 'fzf'
    Layer 'unite'
    Layer 'better-defaults'
```

<img width="655" alt="2017-02-06 7 50 07" src="https://cloud.githubusercontent.com/assets/4475914/22646119/a5039466-eca5-11e6-8b14-c4ef404b0cbe.png">

**Comment by liuchengxu** [comment]
Have you tested it in vim?

**Comment by liuchengxu** [comment]
I have reproduced this in neovim. It's normal in vim. Maybe something is wrong with fzf.vim.

**Comment by taizilongxu** [comment]
Thanks, yes, vim works well, I will check it

**Comment by liuchengxu** [comment]
Some unrelated suggestions: `set termguicolors` in `UserConfig()` to use GUI colors in terminal. You may like it. -_-

**Comment by taizilongxu** [comment]
:-), I find it's a language bug for fzf, just set `let $LANG = 'en_US'`, maybe to set it in default config?

**Comment by liuchengxu** [comment]
We could add `let $LANG = 'en_US'` after https://github.com/liuchengxu/space-vim/blob/master/layers/%2Btools/fzf/config.vim#L2 . Please open up a PR. 👍
