### ISSUE TITLE
space-vim seems not to support python3?

### ISSUE THREAD

**Issue by iihawk** [liuchengxu/space-vim#62]
#### Environment

- OS: centos7.3
- vim: 8.0.311
- Python：anaconda3-4.2

#### Problem Description

1. [root@centos73 ~]# vim
2. Error detected while processing function <SNR>2_collect_topics:
3. line   26:
4. E370: Could not load library libpython3.5m.so.1.0
5. E263: Sorry, this command is disabled, the Python library could not be loaded.
6. Error detected while processing function core_config#end[6]..<SNR>2_load_layer_packages:
7. line    2:
8. E121: Undefined variable: g:layer_path
9. E15: Invalid expression: g:layer_path[l:layer] . '/packages.vim'
10. line    3:
11. E121: Undefined variable: l:layer_packages
12. 。。。
13. 。。。
14. 。。。
15. E116: Invalid arguments for function <SNR>2_Source
16. Error detected while processing function core_config#end[33]..<SNR>2_load_layer_config:
17. line    2:
18. E121: Undefined variable: g:layer_path
19. E15: Invalid expression: g:layer_path[l:layer] . '/config.vim'
20. line    3:
21. E121: Undefined variable: l:layer_config

=================================================
【question】space-vim seems not to support python3? or probabaly It might be some plugins not supporting python3, like YouCompleteMe ?

Have you tested on python3?

**Comment by liuchengxu** [comment]
Make no sense. I always use python3 and anaconda3. Our environment is much similar exccept the os(I use mac).

Could you check `:echo has('python')` or `:echo has('python3')` in vim? It looks like vim can't call python.

**Comment by iihawk** [comment]
echo has('python3') does return 1, but vim --version show many "-"
I checked with official vim compiling guide, then installed all its required packages, then it turns ok.
so this issue at first should be caused by lack of some packages.

**Comment by liuchengxu** [comment]
From the error messages above, it's the failure of calling python in vim that caused this issue. It should be ok if vim includes `+python` or `+python3` feature correctly.
