### ISSUE TITLE
关于禁用鼠标的问题

### ISSUE THREAD

**Issue by areaice** [liuchengxu/space-vim#66]
#### Environment

- OS: CentOS 7.1
- vim: vim 8.0
- neovim: 

#### Problem Description

我在~/.spacevim和~/.vimrc里都设置了set mouse-=a以禁用鼠标，可是没有生效，在vim打开状态下:set mouse -=a则生效，怎么解决呢？对复制粘贴需求大......

**Comment by liuchengxu** [comment]
在 `UserConfig()` 中设置 `set mouse-=a` 无效? 

`:verbose set mouse` 查看最后的设置情况。

**Comment by areaice** [comment]
显示的还是mouse=a    在vim-better-default/default.vim里设置，我直接注释掉这里的就好了，在UserConfig()里设置无效，是不是default.vim在UserConfig()之后生效？

**Comment by areaice** [comment]
我用的是几个月前的老版本，刚用你Reademe里的curl和wget方法重新安装下，出现了这样的错误：

```
error: Your local changes to the following files would be overwritten by merge:
	.vimrc
	layers/+vim/better-defaults/config.vim
Please, commit your changes or stash them before you can merge.
Aborting
[✔] Setting up vim symlinks.
[✔] Now updating/installing plugins using vim-plug

Thanks for installing space-vim. Enjoy!

```
怎么解决呢？

**Comment by liuchengxu** [comment]
这是你因为刚刚注释了 default.vim 的那一行，`~/.vim/plugged/vim-better-default/`目录下执行 `git checkout .` 取消修改，再进行更新。
