### ISSUE TITLE
使用fzf的时候报错

### ISSUE THREAD

**Issue by steinliber** [liuchengxu/space-vim#70]
#### Environment

- OS: macos
- vim: 8.0
- neovim: ???

#### Problem Description

在vim中使用fzf的时会报错误
Error running cat "/var/folders/jq/ll9yxyk53zjc7s2yjjc13bj00000gp/T/vKIlG3X/8"|"fzf" --color=bg+:237,bg:235,spinner:104,hl:168,fg:249,header:30,info:176,pointer:160,marker:36,fg+:36,prompt:134,hl+:81 --prompt "Maps (n)> " --ansi --no-hscr
oll --nth 1,.. --color prompt:12 --height=25 > /var/folders/jq/ll9yxyk53zjc7s2yjjc13bj00000gp/T/vKIlG3X/7
本地跑了下这个命令
cat "/var/folders/jq/ll9yxyk53zjc7s2yjjc13bj00000gp/T/v7sa4Or/3"|"fzf" --color=bg+:237,bg:235,spinner:104,hl:168,fg:249,header:30,info:176,pointer:160,marker:36,fg+:36,prompt:134,hl+:81 --prompt "Maps (n)> " --ansi --no-hscr
cat: /var/folders/jq/ll9yxyk53zjc7s2yjjc13bj00000gp/T/v7sa4Or/3: No such file or directory
unknown option: --no-hscr

**Comment by liuchengxu** [comment]
尝试重新下载 fzf binary, 运行 fzf 的安装脚本 ( ~/.fzf/install) 下载最新版本。

**Comment by steinliber** [comment]
解决了，谢了 @liuchengxu
