### ISSUE TITLE
ycmd layer启用无效

### ISSUE THREAD

**Issue by areaice** [liuchengxu/space-vim#71]
#### Environment

- OS: CentOS 7.1
- vim: vim8.0
- neovim: 

#### Problem Description

启用ycmd后，并不能补全，按照READEME.md里的操作也执行不成功：
```
$ ./install.py --clang-completer
ERROR: some folders in /home/endice/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party are empty; you probably forgot to run:
	git submodule update --init --recursive

[endice@localhost YouCompleteMe]$ git submodule update --init --recursive
正克隆到 'third_party/requests'...
fatal: unable to access 'https://github.com/kennethreitz/requests/': Peer's Certificate has expired.
无法克隆 'https://github.com/kennethreitz/requests' 到子模组路径 'third_party/requests'
无法递归进子模组路径 'third_party/ycmd'

```
vim里有
```
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code 0. Use the ':YcmToggleLogs' command to check the logs.    
```
```
argument can't be <type 'unicode'> 
```
怎么解决这些问题呢 ?

题外话：
我对vim插件不熟，但我喜欢别人已经配置好的即开即用的vim，我以前试过一些，基本可以安装好就支持自动补全等功能，而这个似乎会存在问题，可以麻烦你辛苦下，把自动补全弄的即开即用么~~

**Comment by tracyone** [comment]
插件都没安装好..首先你得找个稳定快速的环境安装ycm，必要时还得翻下墙

**Comment by areaice** [comment]
可是space-vim时PlugInstall显示已经安装了呀

**Comment by tracyone** [comment]
你的issue里面
```
fatal: unable to access 'https://github.com/kennethreitz/requests/': Peer's Certificate has expired.
无法克隆 'https://github.com/kennethreitz/requests' 到子模组路径 'third_party/requests'
无法递归进子模组路径 'third_party/ycmd'
```

这三句表示，没有装好，space-vim里的vim-plug只是检查相关文件夹是否存在，是否是git仓库，仓库地址是否对得上而已，没有检查里面的内容

建议你找个网络环境好的，最好能翻墙的。

**Comment by liuchengxu** [comment]
@areaice 
你这里有些概念没有搞清楚。只要使用 YouCompleteMe 就一定要编译成功后才能按照预期工作。如果不想编译，你也可以启用 auto-completion Layer 进行基本的补全，实际它使用的就是 neocomplete (vim) 与 deoplete (neovim)。

执行 `:PlugInstall` 不代表就能 “一步到位”。比如这里的 YouCompleteMe 就需要编译额外的组件才能正常工作。虽然 vim-plug 有 post-update hooks 可以设置自行安装, 但是由于 YouCompleteMe 过于庞大，仅仅依靠 vim-plug 常常不能完成全部的工作，这时便需要你自行安装 YouCompleteMe 的编译工作。

针对你目前的情况，显然是 `git submodule update --init --recursive` 这里没有成功，安装 YouCompleteMe 其实很简单，几步而已，关键是网络。
