### ISSUE TITLE
Disable line numbers

### ISSUE THREAD

**Issue by brunobottazzini** [liuchengxu/space-vim#72]
#### Environment

- OS: Ubuntu 16.04 LTS
- vim: VIM - Vi IMproved 7.4

#### Problem Description

Hello, I'd like to turn off the line numbers count in the "left panel" of the editor. It bothers me a lot.

I tried running:
```
:set nu!
:set nonumber
:set nonu
```

But the selected column number just transformed as 0. And the others numbers are still there.

I tried to find what plugin makes this configuration but still I did not find it.

See the screenshot here:

![schermata da 2017-02-22 10-44-57](https://cloud.githubusercontent.com/assets/4460234/23205924/045abeb0-f8ec-11e6-83d5-fa730d8821d1.png)

**Comment by liuchengxu** [comment]
You mean the relative number?

`set norelativenumber` in `UserConfig()`.

**Comment by brunobottazzini** [comment]
Yes! I haven't test this command. I knew I was missing something.

Thanks you :+1:
