### ISSUE TITLE
不能查看键位绑定

### ISSUE THREAD

**Issue by imsuwj** [liuchengxu/space-vim#74]
#### Environment

- OS: Arch64

- vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 14 2017 10:57:50)

#### Problem Description

按<spc>+<?>查看快捷键如图

![screenshot_20170223_235056](https://cloud.githubusercontent.com/assets/2463831/23309115/6b961536-fae8-11e6-86db-177cc22da365.png)

**Comment by liuchengxu** [comment]
#61 看起来跟这个问题类似， 在 `UserConfig()`设置 `let $LANG = 'en_US'` 看能够解决问题。

你是不是也启用了 chinese Layer? 可能里面有设置 ` let $LANG = 'zh_CN.UTF-8'` 跟这个冲突了, 我会再看一下。

**Comment by imsuwj** [comment]
@liuchengxu 设置`let $LANG = 'en_US'`问题依旧，而且没有启用chinese Layer

**Comment by liuchengxu** [comment]
这样的话，我建议到 [fzf.vim](https://github.com/junegunn/fzf.vim) 提个 issue 问一下。

@taizilongxu 好像跟你遇到过的一个问题类似，有什么想法吗？

**Comment by taizilongxu** [comment]
@imsuwj 看一下 `:echo $LANG` 是不是 en_US

**Comment by imsuwj** [comment]
@taizilongxu 是的

**Comment by liuchengxu** [comment]
除了 `:Maps` ，fzf.vim 的其他功能都正常？

**Comment by imsuwj** [comment]
@liuchengxu 其它功能正常

**Comment by liuchengxu** [comment]
@imsuwj 因为我这里没有办法重现这个问题，所以还是建议到 fzf.vim 提个 issue 问一下 :(.

**Comment by zhenjun115** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 16 2017 06:56:34)
iterm2 终端下面无法查看键位绑定
<img width="1280" alt="issue_1" src="https://cloud.githubusercontent.com/assets/5096364/23495336/1e56ce5e-ff53-11e6-8e49-b0869f3d5964.png">

Macvim 可以正常查看
<img width="1280" alt="issue_2" src="https://cloud.githubusercontent.com/assets/5096364/23495386/64fa60be-ff53-11e6-9737-8300e8115fb7.png">

**Comment by liuchengxu** [comment]
fzf 是一个命令行工具，不支持 GUI 。 所以在 MacVim 中查看快捷键的命令并不是 fzf.vim 提供的 Maps，而是 vim 自带的 nmap. 

@zhenjun115 你在截图中的问题可以通过重新安装 fzf binary 解决 (~/.fzf/install)，#70 。

**Comment by zhenjun115** [comment]
@liuchengxu 多谢
