### ISSUE TITLE
Win7/Win8的 提示错误消息和Python版本的注意事项

### ISSUE THREAD

**Issue by zqq1314521** [liuchengxu/space-vim#76]
#### Environment

- OS: Win7/Win8 64bit
- vim: 8.0

#### Problem Description
按照教程装完后，会报一组消息：如下

处理 function core_config#end[38]..<SNR>2_post_user_config 
时发生错误:

第   11 行:

E115: 缺少引号: '鈵?

E15: 无效的表达式: '鈵?

第   12 行:

E115: 缺少引号: '鈵?

E15: 无效的表达式: '鈵?

第   14 行:

E115: 缺少引号: '鈳?

E15: 无效的表达式: '鈳?

安装PlugInstall后，就好了。

另外，建议作者 应当标明使用Python2.7 32位，我使用了64位，会提示找不到python36.dll的错误，无法安装。

**Comment by liuchengxu** [comment]
windows 的使用环境我只是在虚拟机中简单测试过，并不日常使用，所以可能会有一些不足。只是因为有windows 用户一直跟我邮件交流，才促成了这个 experimental 的 windows 安装. 

关于错误信息，我也遇到过，不过因为 `:PlugInstall` 后就会解决，可能会由于一些字体的原因，确诊后会进行调整。

关于 python 的版本问题，我的虚拟机使用的是 win8 python 3.5.3 64 位，没有问题。
