### ISSUE TITLE
Lazy loading nerdtree leads to calling NERDTree failed when vim enter

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#8]
我想启动 vim 的时候能打开 NERDTree。

```
autocmd vimenter * if !argc() | NERDTree | endif
```

但是因为现在 nerdtree 是 lazy load 的，导致不能执行 `NERDTree`，见 https://github.com/neovim/neovim/issues/4447#issuecomment-195961894 ，然后我把  `NERDTree` 换成 `NERDTreeToggle` 也不行（neovim 那个 issue 里那人最后也说不行）。

**Comment by liuchengxu** [comment]
这个目前似乎没有什么更好的办法, space-vim 默认只是打开 Startify. 

lazy-loading 是考虑到可能并非立即需要 nerdtree, 还是保持精简为好。进入 vim 后可以手动执行 <kbd>SPC f t</kbd> 打开 nerdtree. 

后期可能会考虑是否有更好的选择。比如自行管理 layer 中的部分插件

**Comment by liuchengxu** [comment]
已经更新，取消了 lazy-loading. 因为发现如果使用 vim 打开一个目录，体验也很不好，干脆取消 lazy-loading 了。现在应该没问题了。
