### ISSUE TITLE
建议添加 'jiangmiao/auto-pairs' 自动括号匹配插件

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#80]

**Comment by liuchengxu** [comment]
目前使用的 Raimondi/delimitaMate 似乎与之功能部分重叠，如果有相关对比就更好了，有待试用。

**Comment by zhenjun115** [comment]
嗨，没有在已安装插件中找到 Raimondi/delimitaMate
<img width="1280" alt="2017-03-02 5 25 38" src="https://cloud.githubusercontent.com/assets/5096364/23501092/75a1b0f6-ff6d-11e6-994a-ce71c65d8622.png">

**Comment by liuchengxu** [comment]
typo....，是 delimitMate ，你需要启用 programming Layer。

**Comment by liuchengxu** [comment]
#98 , 由于这个问题，我已经将 delimitMate 替换为 auto-pairs 了，感谢。
