### ISSUE TITLE
输入时自动出现下划线是什么插件的功能？

### ISSUE THREAD

**Issue by lancelock** [liuchengxu/space-vim#81]
不太想要这个功能，该怎样取消？

**Comment by liuchengxu** [comment]
如果理解正确的话，你指的是红色下划线，它是为了显示末尾多余的空格 
https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/spacevim/config.vim#L48 

hi ExtraWhitespace gui=None cterm=None 即可取消下划线。

**Comment by lancelock** [comment]
不是啊，是输入英文单词时当前输入的单词下面会有下划线，并且文档中匹配项都会出现这个下划
![2017-03-03 12-57-55](https://cloud.githubusercontent.com/assets/13751352/23538807/16239618-0011-11e7-8840-31dfcd1dd7ac.png)
线

**Comment by liuchengxu** [comment]
Layers() 写入 Exclude 'itchyny/vim-cursorword' 即可。
