### ISSUE TITLE
建议在.spacevim添加一个Plug下载目录配置项，鼓励用户为Plug配置一个统一的插件下载目录，避免从git上重复下载

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#82]

**Comment by liuchengxu** [comment]
默认的插件下载位置是 vim-plug 的推荐目录，参见 [vim-plug#559](https://github.com/junegunn/vim-plug/issues/559) .

当然，如果用户想要自定义目录，或者不喜欢 neovim 与 vim 下载两套插件，也是可以的，只需添加一个配置项即可。

**Comment by zhenjun115** [comment]
是不是可以在UserConfig代码块中添加一个显式的配置项？

**Comment by liuchengxu** [comment]
可以在 UserInit() 中添加一个配置项，我会在下次提交时加上。

**Comment by zhenjun115** [comment]
3x

**Comment by liuchengxu** [comment]
直接在 .spacevim 的函数外任意位置写入配置项即可 (推荐放在开头位置更易理解), 比如:

```vim
let g:spacevim_plug_path = '~/.vim/foo/plugged'
```

**Comment by zhenjun115** [comment]
3x
