### ISSUE TITLE
space-vim 和SpaceVim是什么关系？

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#83]

**Comment by liuchengxu** [comment]
从技术层面看，没关系。

至于其他层面，我不屑于与 SpaceVim 的发起者扯上任何关系，其为人实在难以恭维。实在想知道的话，你很容易在 v2ex ，emacs-china， hackernews 上找到一些联系，但这些联系令人难以下咽，不看也罢。
