### ISSUE TITLE
java语法检查，状态栏中的错误提示中文无法正常显示。

### ISSUE THREAD

**Issue by forbreak** [liuchengxu/space-vim#85]
#### Environment

- OS: 10.12.3
- neovim: 0.1.7
引入的 layer 如下：
    Layer 'chinese'
    Layer 'fzf'
    Layer 'unite'
    Layer 'better-defaults'
    Layer 'programming'
    Layer 'text-align'
    Layer 'airline'
    Layer 'java'
    Layer 'html'
    Layer 'javascript'
    Layer 'markdown'
    Layer 'auto-completion'
    Layer 'syntax-checking'

在编辑java 文件的时候，出现语法错误，状态栏下面的错误提示中文不能正常显示，全部为？？？
格式大概如下。
【#javac#】？？：？？？？？【warning】

**Comment by zhenjun115** [comment]
java开发过程中没有遇到这个问题

**Comment by zhenjun115** [comment]
try this: set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1.
you can add that to your userconfig in .spacevim file.

**Comment by zhenjun115** [comment]
当我在macvim下开启airline layer时，出现乱码。

**Comment by liuchengxu** [comment]
出现乱码可能原因有:

- 字体。有些字体对于一些特殊字符的支持比较弱，我使用的 Source Code Pro for Powerline 没有出现乱码的因素。
- 编码设置。无论是 shell 还是 vim, 都有可能。不过这个问题 space-vim 做了一些处理，现在应该比较少了。

**Comment by forbreak** [comment]
@zhenjun115 我在macvim下反而不是乱码。

**Comment by zhenjun115** [comment]
你好，麻烦在乱码的时候查询 ':set encoding', ':set fileencodings', ':set fileencodings', 把结果值分别贴出来。

**Comment by forbreak** [comment]
@zhenjun115 输出了一下
encoding=utf-8
fileencodings=utf-8,ucs-bom,gb18030,gbk,db2312,cp936

**Comment by liuchengxu** [comment]
@zhenjun115 你的字体是什么？感觉像是字体的原因，因为我这里正常，没有乱码。

**Comment by forbreak** [comment]
@zhenjun115  我试着调整了下字体，用这个 Source Code Pro for Powerline 也还是乱码。

**Comment by liuchengxu** [comment]
@forbreak 你的问题我觉得可能是 shell 的某处编码设置。

**Comment by zhenjun115** [comment]
iterm2 上使用的是Monaco 和 Monaco for powerline。Macvim使用的字体是Monaco，我把macvim的字体调整为 Monaco for powerline，乱码消失了。这是我目前使用字体的情况:
<img width="1268" alt="2017-03-16 12 43 48" src="https://cloud.githubusercontent.com/assets/5096364/23982175/b38c3ce0-0a46-11e7-95f3-2c18bb5ac288.png">

**Comment by liuchengxu** [comment]
恩，选用带有 `for Powerline` 样式的字体应该就不会遇到你上图中的乱码问题了。

**Comment by zhenjun115** [comment]
@forbreak 我觉得出现乱码原因应该是使用的终端环境编码的问题。
