### ISSUE TITLE
";"字符作用是重复上一次action，无法使用。

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#86]
按";"键，space-vim将“;”识别为“:”进入命令输入模式。
“;” 正常作用是重复上一次键入的action，譬如，使用“f” 单行搜索字符时，结合";"命令就不需要多次键入"f"命令来搜索重复的字符。
目前“;”无法使用。

**Comment by liuchengxu** [comment]
这是 ”故意“ 设置的，https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L223 , 不喜欢的话，可以恢复默认功能: 在 UserConfig() 中写入 `unmap ;`.

**Comment by zhenjun115** [comment]
3x

**Comment by zhenjun115** [comment]
neovim don't work with "unmap ;"
here is my .spacevim config:
<img width="656" alt="2017-08-28 5 26 27" src="https://user-images.githubusercontent.com/5096364/29767704-0eeee104-8c16-11e7-823b-793505bce42f.png">

and here is the issue when open neovim
<img width="423" alt="2017-08-28 5 26 44" src="https://user-images.githubusercontent.com/5096364/29767713-1687cba6-8c16-11e7-9611-229b0888c7cd.png">

here is my env:
<img width="1263" alt="2017-08-28 5 27 40" src="https://user-images.githubusercontent.com/5096364/29767745-31c5b478-8c16-11e7-910b-1351e608c2a2.png">

**Comment by liuchengxu** [comment]
Try this:

```vim
if !empty(maparg(';', 'n'))
  unmap ;
endif
```

Or you can suppress the error by prepending `silent!` if it makes no differences, i.e., `silent! unmap ;`

**Comment by zhenjun115** [comment]
problem solved, 3x.
