### ISSUE TITLE
"p" is not working

### ISSUE THREAD

**Issue by yesmeck** [liuchengxu/space-vim#9]
Reproduce:

1. Open a file `vim file.txt`;
1. press `yy` on a line;
1. press `p`.

Expect:

Paste that line to the next.

Actual:

Vim shows `E353: Nothing in register *` error.

It works on MacVim, but not  in terminal.

**Comment by liuchengxu** [comment]
Are you in a tmux session?

**Comment by yesmeck** [comment]
Yes.

**Comment by yesmeck** [comment]
It works out of tmux session.

**Comment by liuchengxu** [comment]
You can refer to [here](http://stackoverflow.com/questions/11404800/fix-vim-tmux-yank-paste-on-unnamed-register) for more information and here is my [tmux.conf](https://github.com/liuchengxu/dotfiles/blob/master/tmux.conf).

**Comment by yesmeck** [comment]
我自己运行一次 `set clipboard-=unnamed`可以修正这个问题，但是把这句写在 `UserConfig` 里却没效果。

**Comment by liuchengxu** [comment]
可能因为这里已经设置过了 [clipboard setting](https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L146)

**Comment by yesmeck** [comment]
但是 UserConfig 的加载不是在插件的加载之后吗？

**Comment by liuchengxu** [comment]
额, 这个也许是 set 与 let 的区别了，具体我也不是很清楚。你可以看第二个回答，使用 brew 安装 reattach-to-user-namespace。

**Comment by yesmeck** [comment]
发现 vim-better-default/plugin/default.vim 的执行是在 UserConfig 之前的，这样就有问题了，没办法在 UserConfig 里覆盖已有的配置了。

**Comment by liuchengxu** [comment]
哦，想起来了，插件是在 .vimrc 之后才加载的, 所以会被覆盖。https://github.com/liuchengxu/vim-better-default#how-to-override-the-existing-settings

可以这样做:

```vim
runtime! plugin/default.vim
set set clipboard-=unnamed
```

**Comment by yesmeck** [comment]
`runtime! plugin/default.vim` 这个默认加到 core 里吧，覆盖默认设置应该是常见需求。

**Comment by liuchengxu** [comment]
有道理~

**Comment by yesmeck** [comment]
发现想要覆盖 nerdtree 的配置也不行。

```
let NERDTreeChDirMode = 2
```

**Comment by liuchengxu** [comment]
这个好像我这里是 ok 的，它默认就是 2，在 UserConfig() 中设置是有效的：

```vim
let g:NERDTreeChDirMode = 2
```

你可以 `:echo g:NERDTreeChDirMode` 查看它的值。

**Comment by yesmeck** [comment]
我这里是 0。。。

**Comment by yesmeck** [comment]
默认值就是 0 https://github.com/scrooloose/nerdtree/blob/eee431dbd44111c858c6d33ffd366cae1f17f8b3/doc/NERD_tree.txt#L744

**Comment by yesmeck** [comment]
奥，是我没加 `g:` 的缘故。
