### ISSUE TITLE
Change `Exclude` command to an option to `Layer` command

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/space-vim#90]
In #89, I remove `Exclude` command, and change it to be an option to `Layer` command. I think it's more intuitive to know which plugins you are trying to exclude in a certain Layer.

e.g.,

original version:
```vim
Exclude 'itchyny/vim-cursorword'
Exclude 'terryma/vim-multiple-cursors'
```
now, you use `exclude` to obtain the same goal:
```vim
Layer 'better-defaults', { 'exclude': ['itchyny/vim-cursorword', 'terryma/vim-multiple-cursors'] }
```

Once the PR is merged, some space-vim users using `Exclude` command have to update *.spacevim* to make the transition.

**Comment by zhenjun115** [comment]
Much better.
