### ISSUE TITLE
是否可以将状态单独提出？作为插件发布？

### ISSUE THREAD

**Issue by iuunhao** [liuchengxu/space-vim#92]
#### Environment

- OS: X
- vim: X
- neovim: X

#### Problem Description

您的配置写很漂亮，但是根据个人习惯，也许长时间的使用自己的配置，更偏向于自己的配置文件，但是你配置中的状态栏是我目前见到了最漂亮的，您是否可以将它单独提出来分享？或者单独开一个项目，来分享？也许会有意想不到的效果。

**Comment by liuchengxu** [comment]
因为涉及到一些细节问题，所以我无法承诺何时会有结果，不过我会考虑的。

关于 statusline 设置所需的一些知识，可以在这里找到 https://www.v2ex.com/t/330610#reply27 , 无非是一些颜色的搭配与想要显示的功能部件而已。

**Comment by iuunhao** [comment]
谢谢您的回答。

**Comment by liuchengxu** [comment]
@iuunhao https://github.com/liuchengxu/eleline.vim , I have extracted the statusline part from space-vim, please try it.
