### ISSUE TITLE
使用中的一些问题

### ISSUE THREAD

**Issue by steinliber** [liuchengxu/space-vim#93]
#### Environment

- OS: macos
- vim: macvim 8.0
- neovim: ???

#### Problem Description

1. 使用 vim 时会产生一个以 .un~结尾的隐藏文件
2. python 中使用 YouCompleteMe 并不能跳到对应的定义处

**Comment by liuchengxu** [comment]
1. 在 `UserConfig()` 中设置 `set noundofile` .

2. 关于 YouCompleteMe 跳转定义相关的配置在这里: https://github.com/liuchengxu/space-vim/blob/master/layers/%2Btools/ycmd/config.vim#L56-L68 , space-vim 的设置为 <kbd>, g d</kbd> 跳转到定义处。

具体的话可以查看 YouCompleteMe 的README, 如果说不能跳转，那应该是 YouCompleteMe 的问题了。
