### ISSUE TITLE
how to configure newly added vim-scripts' hot-keys?

### ISSUE THREAD

**Issue by mikeyarthur** [liuchengxu/space-vim#94]
#### Environment

- OS: VMware Ubuntu16.04
- vim: vim8(compiled according to [)](http://blog.csdn.net/a464057216/article/details/52821171)
- neovim: 

#### Problem Description

I attached Plug 'vim-scripts/c.vim' in .spacevim in order to use c.vim. However, I could use only the templates within c.vim with hot-keys unactivated. I assumed the <leader> is \<space> and tried re-making some hot-keys which turned out to be frustrated.
That's why i came here for help. I used to use vim-plug to manage vim-scripts. Back then the c.vim worked out quite well. 

Since space-vim is so attractive to me, I don't wanna give it up. I wonder how to config the newly added vim-scripts to enable hot-keys. 

Thanks a lot.

**Comment by liuchengxu** [comment]
Have you put `Plug 'vim-scripts/c.vim'` in `UserInit()` ?

```vim
function! UserInit()
   Plug 'vim-scripts/c.vim'
endfunction
```

And I'm a little confused about your problem, what do the hot-keys mean? You mean some expected key mappings fail to work?

**Comment by mikeyarthur** [comment]
Yeah, you got my point. I had edited .spacevim just like that. PlugStatus shows c.vim is OK. Templats in c.vim are enabled while key mappings of them failed to work.

**Comment by liuchengxu** [comment]
@mikeyarthur Hi, I have updated the previous comment. You can use `:Maps` to see the whole normal key mappings. Please check it out.

**Comment by mikeyarthur** [comment]
Thank you for enlightening me. Took me a whole night to figure it out.
BTW, am I supposed to attach my former .vimrc to ~/.space-vim/init.vim or ~/.spacevim. I noticed when updated, spacevim will make a backup for .vimrc, while .spacevim seemingly remained the same.

**Comment by liuchengxu** [comment]
space-vim users don't have to take care of `.vimrc`, `.spacevim` can be used to make a full customization. I'll improve this in install.sh.

**Comment by mikeyarthur** [comment]
Fully appreciate your effort. Let's call it a day. 
Thank you again and good night.

**Comment by liuchengxu** [comment]
I forgot one thing: you shouldn't run install.sh to update space-vim, you ought to enter space-vim directory and run `git pull origin master`.

```sh
cd ~/.space-vim
git pull origin master
```
