### ISSUE TITLE
在括号内回车自动换行并且缩进这个功能有没有？

### ISSUE THREAD

**Issue by lancelock** [liuchengxu/space-vim#98]
比如{}在花括号内回车，格式自动变成
{
    cursor
}
光标在cursor位置

**Comment by liuchengxu** [comment]
```vim
function! Layers()
    Layer 'programming', { 'exclude': 'Raimondi/delimitMate' }
endfunction

function! UserInit()
    Plug 'jiangmiao/auto-pairs'
endfunction
```

启用 programming Layer, 并将 delimitMate 换成 auto-pairs.

后期我会考虑在 programming Layer 将默认的 delimitMate 换为 auto-pairs.

**Comment by lancelock** [comment]
需要设置吗？我开了这个插件好像不起效果，而且连括号自动补全都没有了

**Comment by liuchengxu** [comment]
`:PlugStatus` 检查是否安装成功，我在本地测试已测试过。

**Comment by lancelock** [comment]
我一开始是直接修改programming/package.vim文件，把这行
MP 'Raimondi/delimitMate', { 'on': [] } 直接替换成 MP 'jiangmiao/auto-pairs', { 'on': [] }，:PlugStatus查看是装成功了的，但是没起效果
之后我按你给的写法写在.spacevim里，有效果了。
这是什么原因呢？不应该是一样的吗?

**Comment by liuchengxu** [comment]
`MP 'Raimondi/delimitMate', { 'on': [] }` 等同于 `Plug 'Raimondi/delimitMate', { 'on': [] }`, 你后面的设置 `{'on':[]}` 是告诉 vim-plug 不要加载该插件，因此即使你安装成功，但是由于 vim-plug 并未将其加载，因此无效。更多内容可查看 vim-plug README.

**Comment by lancelock** [comment]
那把, { 'on': [] }去掉就可以了吧？
不过为什么delimitMate这个插件这样写却能启用呢？

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/programming/packages.vim#L19-L23  手动加载。

**Comment by liuchengxu** [comment]
auto-pairs 已经替换 delimitMate 成为默认配置，请注意更新。

**Comment by qiqiboy** [comment]
delimitMate多好的插件，加了下面一句配置就可以支持
`let g:delimitMate_expand_cr = 1`

**Comment by liuchengxu** [comment]
@qiqiboy 额，这个之前已经加上了，但是可能由于某些原因并没有生效，所以暂时换到 auto-pairs.

**Comment by BearJean** [comment]
想请教，delimitMate大括号不自动换行能不能设置啊，就是第一条那样
```
比如{}在花括号内回车，格式自动变成
{
cursor
}
光标在cursor位置
```
我想让它输入{时候变成{cursor}的样子，等按下Enter再变成
{
cursor
},因为有时候用大括号初始化多维数组时候总是要一点一点删掉好麻烦。
该怎么设置，谢谢啦~

**Comment by BearJean** [comment]
对了，是原生vim,自己装了五六个插件来用的，不是spacevim.

**Comment by Brodong** [comment]
> ```viml
> function! Layers()
>     Layer 'programming', { 'exclude': 'Raimondi/delimitMate' }
> endfunction
> 
> function! UserInit()
>     Plug 'jiangmiao/auto-pairs'
> endfunction
> ```
> 
> 启用 programming Layer, 并将 delimitMate 换成 auto-pairs.
> 
> 后期我会考虑在 programming Layer 将默认的 delimitMate 换为 auto-pairs.

想问一下，这个是写在哪个文件呢？我这边是ubuntu

**Comment by v-gq** [comment]
同问
- `SpaceVim : 1.7.0`  
- `vim : 8.1`  
按照以上的方法现在花括号有自动换行了  
**方括号自动换行没了**  
是我操作方式有问题么！？
